# Optimization Campaign (HITL)

**Prerequisites:** TermNorm backend at `http://127.0.0.1:8000` | Groq API key in `.env` | Restart kernel after first sync

**Workflow:** Setup → Data → Explore → Optimize → Results

## 1. Setup

In [15]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [16]:
import json
from _campaign_lib import *

svc = await init_services()
TASK_DESCRIPTION = load_task_description(
    r"C:\Users\dsacc\OfficeAddinApps\TermNorm-excel\backend-api\config\LCA_INPUT_PATTERNS.md"
)

Backend: http://127.0.0.1:8000

2026-03-17 16:28:22 INFO     [httpx] HTTP Request: GET http://127.0.0.1:8000/pipeline "HTTP/1.1 200 OK"
2026-03-17 16:28:22 INFO     [api.services.pipeline_discovery] Matched known pipeline 'termnorm'; using enriched schema
2026-03-17 16:28:22 INFO     [api.services.campaign.campaign_init] Pipeline schema loaded: termnorm vv1.1

Pipeline: termnorm (6 steps)
Experiment: production_historical (40 queries, 93 session terms)
Experiment : production_historical
Mappings   : 887 total, 812 with verified ground truth
Queries    : 40  |  Session terms: 93
Loaded task description: 3751 chars from LCA_INPUT_PATTERNS.md

In [17]:
campaign_config = {
    "sample_size": 15,              # queries per eval step (service default: all)
    "exploration_rate": 0.5,             # PRIMARY KNOB: 0.0=conservative, 1.0=aggressive
    "improvement_areas": "profile schema quality, web search relevance",
    "exclude_steps": ["llm_ranking"],    # steps to skip (e.g. ["entity_profiling"])
    "pipeline_overrides": {},
    "optimization": {
        "patience": 2,                   # default: 3
        "max_rounds": 3,                 # default: 10
    },
    "eval_llm": {
        # --- Groq (free tier, open-source models) ---
        "model": "openai/gpt-oss-120b",
        # "model": "moonshotai/kimi-k2-instruct-0905"
        "provider_url": "https://api.groq.com/openai/v1/chat/completions",
        # --- Anthropic (cost: opus >> sonnet >> haiku) ---
        # "model": "claude-opus-4-6",          # best quality
        # "model": "claude-sonnet-4-6",      # good balance
        # "model": "claude-haiku-4-5-20251001",  # cheapest
        # "provider_url": "https://api.anthropic.com",
        "max_tokens": 2000,              # response length budget
    },
    "grid_search": {
        "context": "A terminology normalization pipeline that matches raw material "
                    "descriptions to standardized database terms using entity profiling "
                    "and candidate ranking.",
        "grid_budget": 35,               # default: 0 (full grid)
        "sample_size": 6,     # default: 0 (all queries)
        "shared_queries": False,          # default: True
    },
}

In [18]:
#@title Pipeline snapshot (full config for reproducibility)
pipeline_config_full = await show_pipeline_snapshot(svc)

2026-03-17 16:28:22 INFO     [httpx] HTTP Request: GET http://127.0.0.1:8000/pipeline "HTTP/1.1 200 OK"

======================================================================
  PIPELINE SNAPSHOT: TermNorm v1.1
======================================================================
  Nodes:   ['fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching', 'llm_ranking', 'direct_prompt']
  Schemas: ['entity_profile/1', 'llm_ranking_output/1']
  Prompts: ['entity_profiling/1', 'llm_ranking/1']

{
  "name": "TermNorm",
  "version": "v1.1",
  "available_models": [
    "moonshotai/kimi-k2-instruct-0905",
    "meta-llama/llama-4-scout-17b-16e-instruct",
    "moonshotai/kimi-k2-instruct",
    "openai/gpt-oss-120b"
  ],
  "nodes": {
    "fuzzy_matching": {
      "type": "DeterministicFunction",
      "config": {
        "threshold": 70,
        "scorer": "WRatio",
        "limit": 5
      }
    },
    "web_search": {
      "type": "ExternalService",
      "config": {
        "max_sites": 7,
        "num_results": 20,
        "content_char_limit": 800,
        "url_fetch_multiplier": 2,
        "fallback_keywords_limit": 8,
        "query_prefix": "",
        "query_suffix": "",
        "brave_api_timeout": 10,
        "scrape_timeout": 5,
        "http_content_limit": 50000,
        "min_page_text_length": 200,
        "max_page_text_length": 10000,
        "title_truncate_length": 100,
        "scrape_workers": 10,
        "skip_extensions": [
          ".pdf",
          ".doc",
          ".docx",
          ".ppt",
          ".pptx",
          ".xls",
          ".xlsx"
        ],
        "skip_domains": [
          "academia.edu",
          "researchgate.net",
          "arxiv.org",
          "ieee.org"
        ],
        "search_language": "en",
        "search_country": "US",
        "accept_language": "en-US,en;q=0.9",
        "html_strip_tags": [
          "script",
          "style",
          "nav",
          "header",
          "footer"
        ],
        "min_keyword_length": 3,
        "keyword_split_chars": [
          "/",
          "-"
        ],
        "spellcheck": true,
        "result_filter": "",
        "extra_snippets": false,
        "freshness": ""
      }
    },
    "entity_profiling": {
      "type": "LLMGeneration",
      "config": {
        "model": "moonshotai/kimi-k2-instruct-0905",
        "temperature": 0.3,
        "max_tokens": 1800,
        "raw_content_limit": 5000,
        "per_site_content_limit": 500,
        "prompt_family": "entity_profiling",
        "prompt_version": 1,
        "schema_family": "entity_profile",
        "schema_version": 1
      }
    },
    "token_matching": {
      "type": "DeterministicFunction",
      "config": {
        "max_token_candidates": 20,
        "tokenization_regex": "[a-zA-Z0-9]+"
      }
    },
    "llm_ranking": {
      "type": "LLMGeneration",
      "config": {
        "model": "moonshotai/kimi-k2-instruct-0905",
        "temperature": 0.0,
        "max_tokens": 4000,
        "sample_size": 20,
        "debug_output_limit": 20,
        "relevance_weight_core": 0.7,
        "prompt_family": "llm_ranking",
        "prompt_version": 1,
        "schema_family": "llm_ranking_output",
        "schema_version": 1
      }
    },
    "direct_prompt": {
      "type": "LLMGeneration",
      "config": {
        "model": "moonshotai/kimi-k2-instruct-0905",
        "temperature": 0.0,
        "max_tokens": 300,
        "accept_threshold": 0.75,
        "correction_top_n": 10
      }
    }
  },
  "pipelines": {
    "default": [
      "web_search",
      "entity_profiling",
      "token_matching",
      "llm_ranking"
    ]
  },
  "cache": {
    "high_confidence_threshold": 0.8,
    "verified_methods": [
      "UserChoice",
      "DirectEdit",
      "cached",
      "fuzzy"
    ]
  },
  "llm_defaults": {
    "provider": "groq",
    "model": "moonshotai/kimi-k2-instruct-0905",
    "timeout": 60,
    "retry_attempts": 3,
    "retry_backoff_base": 2,
    "token_estimation_multiplier": 1.3,
    "token_limit": 100000,
    "seed": null,
    "logprobs": null
  },
  "resolved_schemas": {
    "entity_profile/1": {
      "family": "entity_profile",
      "version": 1,
      "description": "Entity profile extraction schema for web research pipeline",
      "fields": [
        "entity_name",
        "core_concept",
        "distinguishing_features",
        "key_properties",
        "technical_specifications",
        "alternative_names",
        "classification_aliases",
        "constituent_materials",
        "manufacturing_processes",
        "applications",
        "notes"
      ],
      "json_schema": {
        "type": "object",
        "properties": {
          "entity_name": {
            "type": "string"
          },
          "core_concept": {
            "type": "string",
            "description": "The single word that defines what this expression represents"
          },
          "distinguishing_features": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "key_properties": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "technical_specifications": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Explicit technical specs, dimensions, codes, ratings, tolerances"
          },
          "alternative_names": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "classification_aliases": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic"
          },
          "constituent_materials": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge"
          },
          "manufacturing_processes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards"
          },
          "applications": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Direct and derived applications based on product characteristics"
          },
          "notes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "entity_name",
          "core_concept",
          "distinguishing_features",
          "key_properties",
          "technical_specifications",
          "alternative_names",
          "classification_aliases",
          "constituent_materials",
          "manufacturing_processes",
          "applications",
          "notes"
        ]
      }
    },
    "llm_ranking_output/1": {
      "family": "llm_ranking_output",
      "version": 1,
      "description": "LLM ranking step output schema \u2014 structured candidate evaluation",
      "fields": [
        "profile_summary",
        "core_concept_description",
        "ranked_candidates"
      ],
      "json_schema": {
        "type": "object",
        "properties": {
          "profile_summary": {
            "type": "string",
            "description": "1-2 sentence summary of the entity profile"
          },
          "core_concept_description": {
            "type": "string",
            "description": "Description of the core concept match"
          },
          "ranked_candidates": {
            "type": "array",
            "description": "Candidates ranked by relevance score",
            "items": {
              "type": "object",
              "properties": {
                "candidate": {
                  "type": "string"
                },
                "core_concept_score": {
                  "type": "number"
                },
                "spec_score": {
                  "type": "number"
                },
                "evaluation_reasoning": {
                  "type": "string"
                },
                "key_match_factors": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "spec_gaps": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "required": [
                "candidate",
                "core_concept_score",
                "spec_score",
                "evaluation_reasoning",
                "key_match_factors"
              ]
            }
          }
        },
        "required": [
          "profile_summary",
          "core_concept_description",
          "ranked_candidates"
        ]
      }
    }
  },
  "resolved_prompts": {
    "entity_profiling/1": {
      "family": "entity_profiling",
      "version": 1,
      "description": "Extract comprehensive entity profile from web research data with US/GB spelling variants",
      "template_variables": [
        "query",
        "format_string",
        "combined_text"
      ],
      "template": "You are a comprehensive technical database API specialized in exhaustive entity profiling. Extract ALL possible information about '{{query}}' from the research data and return it in this exact JSON format:\n{{format_string}}\n\nCRITICAL SPELLING REQUIREMENT: In ALL arrays, after each term, immediately add its US/GB spelling variant if different. Example: [\"colour\", \"color\", \"analyse\", \"analyze\"]. This is MANDATORY for every array field.\n\nCORE CONCEPT IDENTIFICATION: Within '{{query}}', certain words carry more semantic weight than others. Material names, product codes, and specifications describe WHAT is involved, but other terms describe the fundamental NATURE of what is being expressed. Identify the single word that defines the conceptual essence - typically the term that indicates an activity, action, method, or process rather than an object or material. Output only this one defining word.\n\nPROFESSIONAL CLASSIFICATION ALIASES: Generate the full spectrum of expert-level references for this entity, spanning precise technical descriptors to broader categorical terms. These terms stem from domain-specific terminology and industry-standard nomenclature that professionals recognize. Include approximations and near-equivalent terms that experts use when exact terminology doesn't exist, accepting that some terms may not be perfect equivalents but represent the best available expert terminology for referencing similar concepts.\n\nGENERIC TECHNICAL INFERENCE INSTRUCTION: Given the product or technical description '{{query}}', perform comprehensive analysis to extract and infer:\n\n1. **Explicit Information**: Directly stated specifications, dimensions, materials, codes, and properties\n2. **Implicit Information**: Commonly associated materials, manufacturing processes, applications, and technical characteristics that are standard for this type of product/component, even if not explicitly mentioned\n3. **Manufacturing Processes**: Both stated and inferred processes based on product type, materials, and specifications\n4. **Material Composition**: Complete material breakdown including standard/typical materials used in such products\n5. **Applications & Use Cases**: Direct and derived applications based on product characteristics\n\n**Include domain knowledge**: Draw from technical standards, industry practices, and material science to infer missing but relevant information.\n\nCRITICAL INSTRUCTIONS FOR RICH ATTRIBUTE COLLECTION:\n- MAXIMIZE diversity: Include ALL synonyms, trade names, scientific names, abbreviations, acronyms, regional terms, industry terminology\n- COMPREHENSIVE extraction: Capture every property, specification, feature, attribute, including numerical values and compositional data\n- PRIORITIZE completeness over brevity: Aim for 5-10+ items per array field - be thorough, not minimal\n---\nRESEARCH DATA:\n{{combined_text}}\n---\nREMEMBER: Every term must be followed by its US/GB variant if different. Return only the JSON object with ALL fields maximally populated."
    },
    "llm_ranking/1": {
      "family": "llm_ranking",
      "version": 1,
      "description": "Rank candidate matches based on entity profile relevance with core concept weighting",
      "template_variables": [
        "core_concept",
        "entity_profile_json",
        "matches"
      ],
      "template": "You are a candidate evaluation expert.\n\nTASK 1: Analyze profile and core concept (PRIMARY FACTOR - 70% WEIGHT)\n- Summarize the profile in 1-2 sentences capturing key details\n- Identify the entity_category from the profile\n- Think step-by-step: What are the most important distinguishing features of this entity?\n- CRITICAL: Prioritize candidates that match the core_concept: '{{core_concept}}'\n- Higher match = more of the distinguishing features present in the candidate name\n\nTASK 2: Evaluate candidate matches (20 candidates provided)\n- Each candidate will receive a relevance_score from 0.0 to 1.0\n- 0.95+ : Exact or near-perfect semantic match (contains most/all distinguishing features + matches core_concept)\n- 0.80-0.94 : Strong match (contains several key features + aligns with core_concept)\n- 0.50-0.79 : Moderate match (contains some features OR loosely relates to core_concept)\n- 0.00-0.49 : Weak/poor match (missing most features, doesn't match core_concept)\n\nENTITY PROFILE (JSON):\n{{entity_profile_json}}\n\nCANDIDATE MATCHES TO EVALUATE:\n{{matches}}\n\nIMPORTANT: Return a valid JSON response matching this exact structure:\n{\n    \"reasoning\": \"[1-2 sentences explaining profile, entity_category, and key features]\",\n    \"ranked_candidates\": [\n        {\n            \"rank\": 1,\n            \"candidate\": \"...\",\n            \"relevance_score\": 0.95,\n            \"rationale\": \"[Brief explanation - 1 sentence]\"\n        }\n    ]\n}\n\nRules:\n- Include ALL 20 candidates in ranked_candidates array\n- Rank 1 = highest relevance_score\n- relevance_score must decrease or stay equal as rank increases\n- Return ONLY valid JSON, no other text"
    }
  }
}
======================================================================

In [19]:
#@title Build pipeline params
pipeline_params = configure_pipeline(svc, campaign_config)

Active steps: ['cache_lookup', 'fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching']
  Excluded: ['llm_ranking']

## 2. Data

In [20]:
#@title Load datasets
# Set EXCEL_PATH to load from BOM-example.xlsx; leave empty to use stored data
EXCEL_PATH = r"C:\Users\dsacc\Desktop\project-TermNorm\OneDrive_2025-07-02\Austausch Beispiele\Prozessnamen\BOM-example.xlsx"  # e.g. "../data/BOM-example.xlsx"
FORCE_RELOAD = False  # Set True to re-read Excel and overwrite stored datasets

train_data, svc["session_terms"] = prepare_datasets(
    svc["store"], svc["backend_id"],
    excel_path=EXCEL_PATH or None,
    force=FORCE_RELOAD,
)

==================================================
  Train              : 984 queries
  Test (processes)   : 82 queries
  Test (material)    : 165 queries
  ------------------------------------------------
  Combined queries   : 820 (deduplicated)
  Session identifiers: 94 unique targets
==================================================

In [21]:
#@title Prepare evaluation context
campaign_rounds = []
baseline_results = []

baseline, eval_data, backend_status = await prepare_eval_context(
    svc, train_data,
)

RUN_BASELINE = False  # Set True to evaluate baseline before exploration
if RUN_BASELINE:
    campaign_rounds, baseline_results = await run_baseline_eval(
        baseline, eval_data, campaign_config, svc,
    )

2026-03-17 16:28:22 INFO     [httpx] HTTP Request: GET http://127.0.0.1:8000/status "HTTP/1.1 200 OK"

BACKEND STATUS
==================================================
  Session Active                 True
  Active Sessions                1
  Terms Loaded                   89
  Match Database Identifiers     110
  Match Database Aliases         699
  Experiments Count              4
  Mappings Count                 1126
  Pipeline Version               v1.1
  Llm Provider                   groq
  Llm Model                      moonshotai/kimi-k2-instruct-0905
  ------------------------------------------------
  Experiments
    0_production_realtime        0 mappings
    1_production_historical      887 mappings
    2_bom_materials              159 mappings
    3_bom_processing             80 mappings
==================================================

Evaluation data: 984 queries

In [22]:
#@title Experiment dashboard
# Set to a short hex ID (e.g. '68e2c5') to resume a specific experiment.
# The system adds prefixes (cycle_, scan_, etc.) per data type.
# Set to None to auto-detect from current campaign_config + eval_data.
EXPERIMENT_ID = '6c8f5ab73fcd' #None

# When EXPERIMENT_ID is set, load stored config → overrides notebook variables
if EXPERIMENT_ID:
    _stored_cfg = load_experiment_config(svc["store"], svc["backend_id"], EXPERIMENT_ID)
    if _stored_cfg:
        _stored_pp = _stored_cfg.get("pipeline_params")
        if _stored_pp and _stored_pp != (pipeline_params if "pipeline_params" in dir() else None):
            pipeline_params = _stored_pp
            campaign_config["pipeline_params"] = _stored_pp
            print(f"  Loaded pipeline_params from experiment {EXPERIMENT_ID}")

show_experiment_dashboard(
    svc["store"], svc["backend_id"],
    experiment_id=EXPERIMENT_ID,
    campaign_config=campaign_config,
    eval_data=eval_data,
    pipeline_params=pipeline_params if "pipeline_params" in dir() else None,
    baseline_prompt_state=campaign_rounds[0]["prompt_state"].model_dump() if campaign_rounds else None,
)

  Loaded pipeline_params from experiment 6c8f5ab73fcd

========================================================================
  EXPERIMENT: cycle_6c8f5ab73fcd
  Status: active  |  Rounds: 0  |  Best: 0.0%  |  Base: 10.0%
  Updated: 2026-03-17 09:05

  Config (copy to campaign_config to resume):
    max_rounds: 3
    patience: 2
    n_variants: 5
    creativity: 0.7
    improvement_threshold: 0.01
    model: openai/gpt-oss-120b
    temperature: 0.0
    sample_size: 15
    seed: 42
    pipeline_params: {max_token_candidates=30, profiling_schema=..., profiling_temperature=0.3, query_prefix=what material is, steps=...}


Diff: current config vs cycle_6c8f5ab73fcd
============================================================
  (identical — will resume this campaign)
============================================================
  → Config does NOT match — update campaign_config to resume
========================================================================

{'campaign_id': 'cycle_6c8f5ab73fcd',
 'created_at': '2026-03-17T09:05:09.124307+00:00',
 'updated_at': '2026-03-17T09:05:09.124307+00:00',
 'status': 'active',
 'n_trials': 0,
 'best_accuracy': 0.0,
 'best_trial_id': None,
 'baseline_accuracy': 0.1,
 'trials': [],
 'type': 'feedback_cycle',
 'config': {'max_rounds': 3,
  'patience': 2,
  'n_variants': 5,
  'creativity': 0.7,
  'improvement_threshold': 0.01,
  'model': 'openai/gpt-oss-120b',
  'provider': 'groq',
  'backend_url': 'http://127.0.0.1:8000',
  'backend_id': 'termnorm-local',
  'project_root': 'C:\\Users\\dsacc\\Desktop\\PromptPotter\\prompt-potter-optimizer\\.promptpotter\\projects',
  'generate_suggestions': False,
  'pipeline_params': {'steps': ['cache_lookup',
    'fuzzy_matching',
    'web_search',
    'entity_profiling',
    'token_matching'],
   'max_token_candidates': 30,
   'query_prefix': 'what material is',
   'profiling_schema': {'type': 'object',
    'properties': {'entity_name': {'type': 'string'},
     'core_concept': {'type': 'string',
      'description': 'The single word that defines what this expression represents'},
     'distinguishing_features': {'type': 'array', 'items': {'type': 'string'}},
     'key_properties': {'type': 'array', 'items': {'type': 'string'}},
     'technical_specifications': {'type': 'array',
      'items': {'type': 'string'},
      'description': 'Explicit technical specs, dimensions, codes, ratings, tolerances'},
     'alternative_names': {'type': 'array', 'items': {'type': 'string'}},
     'classification_aliases': {'type': 'array',
      'items': {'type': 'string'},
      'description': 'Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic'},
     'constituent_materials': {'type': 'array',
      'items': {'type': 'string'},
      'description': 'All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge'},
     'manufacturing_processes': {'type': 'array',
      'items': {'type': 'string'},
      'description': 'Both stated and inferred manufacturing processes based on product type, materials, and industry standards'},
     'applications': {'type': 'array',
      'items': {'type': 'string'},
      'description': 'Direct and derived applications based on product characteristics'},
     'notes': {'type': 'array', 'items': {'type': 'string'}},
     'lca_database_names': {'type': 'array',
      'items': {'type': 'string'},
      'description': "Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'"}},
    'required': ['entity_name',
     'core_concept',
     'distinguishing_features',
     'key_properties',
     'technical_specifications',
     'alternative_names',
     'classification_aliases',
     'constituent_materials',
     'manufacturing_processes',
     'applications',
     'notes',
     'lca_database_names']},
   'profiling_temperature': 0.3},
  'session_terms': ['--',
   'Acrylic varnish, with water, in 53% solution state {RER}| market for acrylic varnish, with water, in 53% solution state | Cut-off, S',
   'Acrylonitrile-butadiene-styrene copolymer {GLO}| market for acrylonitrile-butadiene-styrene copolymer | Cut-off, S',
   'AgC3 | 83% Silver 17%Graphite /RER',
   'Aluminium, wrought alloy {GLO}| market for aluminium, wrought alloy | Cut-off, S',
   'Brass removed by turning, average, conventional {RER}| brass turning, average, conventional | Cut-off, S',
   'Brass {RoW}| market for brass | Cut-off, S',
   'Brazing solder, cadmium free {GLO}| market for brazing solder, cadmium free | Cut-off, S',
   'Bronze {GLO}| market for bronze | Cut-off, S',
   'Cable, unspecified {GLO}| cable production, PVC insulation, no recycled copper | Cut-off, S',
   'Calendering, rigid sheets {RER}| calendering, rigid sheets | Cut-off, S',
   'Ceramic tile {GLO}| market for ceramic tile | Cut-off, S',
   'Chromium steel removed by milling, small parts {RER}| chromium steel milling, small parts | Cut-off, S',
   'Coating powder {RER}| market for coating powder | Cut-off, S',
   'Coating powder {RoW}| market for coating powder | Cut-off, S',
   'Contouring, brass {RER}| contouring, brass | Cut-off, S',
   'Contouring, bronze {RER}| contouring, bronze | Cut-off, S',
   'Copper, cathode {GLO}| market for copper, cathode | Cut-off, S',
   'Copper, cathode {GLO}| market for copper, cathode | only secondary material, S',
   'Corrugated board box {RER}| market for corrugated board box | Cut-off, S',
   'Corrugated board box {RoW}| market for corrugated board box | Cut-off, S',
   'Cycoloy C2950 /GLO',
   'EUR-flat pallet {RER}| market for EUR-flat pallet in kg | Cut-off, S',
   'Epoxy resin, liquid {RoW}| market for epoxy resin, liquid | Cut-off, S',
   'Extrusion, plastic film {RER}| extrusion, plastic film | Cut-off, S',
   'Extrusion, plastic film {RoW}| extrusion, plastic film | Cut-off, S',
   'Extrusion, plastic pipes {RER}| extrusion, plastic pipes | Cut-off, S',
   'Fibre, polyester {GLO}| market for fibre, polyester | Cut-off, S',
   'Folding boxboard carton {RER}| market for folding boxboard carton | Cut-off, S',
   'Galvanized Copper | 99.6% Copper 0.4% Zinc /GLO',
   'Glass fibre reinforced plastic | 50% PA66 50% GF /RER',
   'Glass fibre reinforced plastic | 60% PA6 40% GF /RER',
   'Glass fibre reinforced plastic | 60% PPS 40% GF /RER',
   'Glass fibre reinforced plastic | 65% PA66 35% GF /RER',
   'Glass fibre reinforced plastic | 75% PA66 25% GF /RER',
   'Glass fibre reinforced plastic | 90% PC 10% GF /GLO',
   'Glass fibre reinforced plastic | 95% PA66 5% GF /RER',
   'Glass fibre reinforced plastic, polyamide, injection moulded {GLO}| market for glass fibre reinforced plastic, polyamide, injection moulded | Cut-off, S',
   'Glass fibre reinforced plastic, polyester resin, hand lay-up {GLO}| market for glass fibre reinforced plastic, polyester resin, hand lay-up | Cut-off, S',
   'Glass fibre {GLO}| market for glass fibre | Cut-off, S',
   'Hot rolling, steel {RoW}| hot rolling, steel | Cut-off, S',
   'Injection moulding {RER}| injection moulding | Cut-off, S',
   'Injection moulding {RoW}| injection moulding | Cut-off, S',
   'Light emitting diode {GLO}| light emitting diode production | Cut-off, S',
   'Lubricating oil {RER}| market for lubricating oil | Cut-off, S',
   'Magnet, Sm1Co5',
   'Metal working, average for aluminium product manufacturing {RER}| metal working, average for aluminium product manufacturing | Cut-off, S',
   'Metal working, average for chromium steel product manufacturing {RER}| metal working, average for chromium steel product manufacturing | Cut-off, S',
   'Metal working, average for chromium steel product manufacturing {RoW}| metal working, average for chromium steel product manufacturing | Cut-off, S',
   'Metal working, average for copper product manufacturing {RER}| metal working, average for copper product manufacturing | Cut-off, S',
   'Metal working, average for copper product manufacturing {RoW}| metal working, average for copper product manufacturing | Cut-off, S',
   'Metal working, average for metal product manufacturing {RER}| metal working, average for metal product manufacturing | Cut-off, S',
   'Metal working, average for steel product manufacturing {RER}| metal working, average for steel product manufacturing | Cut-off, S',
   'Metal working, average for steel product manufacturing {RoW}| metal working, average for steel product manufacturing | Cut-off, S',
   'N-olefins {RER}| N-olefins production | Cut-off, S',
   'Paper, newsprint {RER}| market for paper, newsprint | Cut-off, S',
   'Paper, woodfree, coated {RER}| market for paper, woodfree, coated | Cut-off, S',
   'Placeholder',
   'Polyamide (Nylon) 6.6/EU-27',
   'Polycarbonate {RER}| market for polycarbonate | Cut-off, S',
   'Polyester resin, unsaturated {RER}| market for polyester resin, unsaturated | Cut-off, S',
   'Polyethylene terephthalate, granulate, amorphous {GLO}| market for polyethylene terephthalate, granulate, amorphous | Cut-off, S',
   'Polyethylene, low density, granulate {GLO}| market for polyethylene, low density, granulate | Cut-off, S',
   'Polymethyl methacrylate, beads {GLO}| market for polymethyl methacrylate, beads | Cut-off, S',
   'Polyoxymethylene (POM)/EU-27',
   'Polypropylene, granulate {GLO}| market for polypropylene, granulate | Cut-off, S',
   'Polystyrene, expandable {GLO}| market for polystyrene, expandable | Cut-off, S',
   'Polysulfone {GLO}| market for polysulfone | Cut-off, S',
   'Polyurethane, flexible foam {RoW}| market for polyurethane, flexible foam | Cut-off, S',
   'Polyvinyl chloride, suspension polymerised {RER}| market for polyvinyl chloride, suspension polymerised | Cut-off, S',
   'Polyvinylchloride, emulsion polymerised {GLO}| market for polyvinylchloride, emulsion polymerised | Cut-off, S',
   'Printed wiring board, surface mounted, unspecified, Pb free {GLO}| printed wiring board production, surface mounted, unspecified, Pb free | Cut-off, S',
   'Sheet rolling, chromium steel {RER}| sheet rolling, chromium steel | Cut-off, S',
   'Sheet rolling, copper {RoW}| sheet rolling, copper | Cut-off, S',
   'Sheet rolling, steel {RER}| sheet rolling, steel | Cut-off, S',
   'Sheet rolling, steel {RoW}| sheet rolling, steel | Cut-off, S',
   'Silicone product {RER}| market for silicone product | Cut-off, S',
   'Silver {GLO}| market for silver | Cut-off, S',
   'Solder, bar, Sn95.5Ag3.9Cu0.6, for electronics industry {GLO}| market for solder, bar, Sn95.5Ag3.9Cu0.6, for electronics industry | Cut-off, S',
   'Steel Electrogalvanized {GLO} | blast furnace route | production mix, at plant | 1kg, typical thickness between 0.3 - 3 mm. typical width between 600 - 2100 mm | LCI result',
   'Steel Electrogalvanized {RER} | blast furnace route | production mix, at plant | 1kg, typical thickness between 0.3 - 3 mm. typical width between 600 - 2100 mm | LCI result',
   'Steel removed by milling, small parts {RER}| steel milling, small parts | Cut-off, S',
   'Steel removed by turning, average, conventional {RER}| steel turning, average, conventional | Cut-off, S',
   'Steel, chromium steel 18/8 {GLO}| market for steel, chromium steel 18/8 | Cut-off, S',
   'Steel, low-alloyed {GLO}| market for steel, low-alloyed | Cut-off, S',
   'Steel, unalloyed {GLO}| market for steel, unalloyed | Cut-off, S',
   'Steel, zinc coated /RER',
   'Synthetic rubber {GLO}| market for synthetic rubber | Cut-off, S',
   'Thermoforming of plastic sheets {RoW}| processing | Cut-off, S',
   'Tin plating, pieces {RoW}| tin plating, pieces, 10 micrometer | Cut-off, S',
   'Urea formaldehyde resin {RER}| urea formaldehyde resin production | Cut-off, S',
   'Wire drawing, copper {RER}| wire drawing, copper | Cut-off, S',
   'Wire drawing, copper {RoW}| wire drawing, copper | Cut-off, S',
   'Wire drawing, steel {RER}| wire drawing, steel | Cut-off, S'],
  'temperature': 0.0,
  'sample_size': 15,
  'seed': 42,
  'pipeline_schema': None,
  'enable_critique': True,
  'critique_positive_threshold': 0.7,
  'scan_context': {'leaderboard_text': '  max_token_candidates     30                                       acc=30.0%  delta=+18.0%  hits=3/10\n  profiling_schema         schema(12 fields)                        acc=20.0%  delta=+9.2%  hits=2/10\n  query_prefix             what material is                         acc=20.0%  delta=+9.2%  hits=2/10\n  profiling_temperature    0.3                                      acc=20.0%  delta=+9.0%  hits=2/10\n  max_token_candidates     50                                       acc=20.0%  delta=+9.0%  hits=2/10\n  raw_content_limit        8000                                     acc=10.0%  delta=+0.3%  hits=1/10\n  profiling_schema         schema(11 fields)                        acc=10.0%  delta=+0.3%  hits=1/10\n  profiling_schema         schema(11 fields)                        acc=10.0%  delta=+0.3%  hits=1/10\n  raw_content_limit        1000                                     acc=10.0%  delta=+0.3%  hits=1/10\n  profiling_temperature    0.7                                      acc=10.0%  delta=+0.3%  hits=1/10\n  profiling_schema         schema(10 fields)                        acc=10.0%  delta=+0.0%  hits=1/10 (baseline)\n  profiling_temperature    0.0                                      acc=0.0%  delta=-8.8%  hits=0/10\n  query_prefix             identify LCA database name for           acc=0.0%  delta=-8.8%  hits=0/10\n  raw_content_limit        2500                                     acc=0.0%  delta=-8.8%  hits=0/10\n  profiling_schema         schema(13 fields)                        acc=0.0%  delta=-8.8%  hits=0/10\n  max_token_candidates     10                                       acc=0.0%  delta=-9.0%  hits=0/10\n  query_prefix             translate trade name                     acc=0.0%  delta=-9.2%  hits=0/10',
   'sensitivity_text': '  1. max_token_candidates     type=pipeline_param sensitivity=0.270  card=3  budget=medium  [room: best_delta=+18.0%]\n  2. query_prefix             type=pipeline_param sensitivity=0.185  card=3  budget=medium  [room: best_delta=+9.2%]\n  3. profiling_schema         type=pipeline_param sensitivity=0.180  card=5  budget=medium  [room: best_delta=+9.2%]\n  4. profiling_temperature    type=pipeline_param sensitivity=0.177  card=3  budget=medium  [room: best_delta=+9.0%]\n  5. raw_content_limit        type=pipeline_param sensitivity=0.090  card=3  budget=skip  [room: best_delta=+0.2%]',
   'difficulty_text': '  Query classes: easy: 0 (0%) | discriminating: 5 (1%) | hard: 5 (1%) | error: 718 (99%)',
   'improving_axes': ['max_token_candidates',
    'query_prefix',
    'profiling_schema',
    'profiling_temperature'],
   'has_prompt_axes': False,
   'tested_values': '  max_token_candidates (3 values tested):\n    [1] 30  acc=30.0%\n    [2] 50  acc=20.0%\n    [0] 10  acc=0.0%\n  query_prefix (3 values tested):\n    [0] what material is  acc=20.0%\n    [1] identify LCA database name for  acc=0.0%\n    [2] translate trade name  acc=0.0%\n  profiling_schema (5 values tested):\n    [2] schema(12 fields)  acc=20.0%\n    [0] schema(11 fields)  acc=10.0%\n    [3] schema(10 fields)  acc=10.0% *baseline*\n    [4] schema(11 fields)  acc=10.0%\n    [1] schema(13 fields)  acc=0.0%\n  profiling_temperature (3 values tested):\n    [1] 0.3  acc=20.0%\n    [2] 0.7  acc=10.0%\n    [0] 0.0  acc=0.0%',
   'baseline_accuracy': 0.1},
  'enable_l2': False,
  'enable_l3': False,
  'l2_patience': 2,
  'l3_patience': 1,
  'l2_temperature': 0.3,
  'l3_temperature': 0.5,
  'suggestion_temperature': 0.0}}

## 3. Explore

Two exploration paths: **Smart Search** (scan advisor + sensitivity scan) or **Grid Search** (brute-force sweep). Use one or both.

### 3a. Smart Search

In [23]:
#@title Browse variant library
display_variant_library()
# Filter examples:
# display_variant_library(source="PromptWizard")
# display_variant_library(axes=["thinking_style", "persona"])

Variant Library
  Sources: PromptPotter (16), PromptWizard (40)

  persona (6 variants — PromptPotter: 4, PromptWizard: 2)
    [ 0] [PromptPotter] (empty baseline)
    [ 1] [PromptPotter] You are a domain expert with deep knowledge of this field.
    [ 2] [PromptPotter] You are a precise, analytical system that evaluates candidates methodi...
    [ 3] [PromptPotter] You are a careful assistant that considers all options before deciding...
    [ 4] [PromptWizard 2024] You are a specialist who evaluates candidates based on domain-specific...
    [ 5] [PromptWizard 2024] You are a meticulous researcher who cross-references information befor...

  task_intent (4 variants — PromptPotter: 4)
    [ 0] [PromptPotter] (empty baseline)
    [ 1] [PromptPotter] Your task is to identify the single best match from the candidates.
    [ 2] [PromptPotter] Rank candidates by how well they match the concept described.
    [ 3] [PromptPotter] Evaluate each candidate for semantic equivalence to the query concept,...

  thinking_style (42 variants — PromptPotter: 4, PromptWizard: 38)
    [ 0] [PromptPotter] (empty baseline)
    [ 1] [PromptPotter] Think step by step.
    [ 2] [PromptPotter] Focus on semantic meaning, not surface-level word overlap.
    [ 3] [PromptPotter] First understand the core concept, then evaluate each candidate agains...
    [ 4] [PromptWizard 2024] How could I devise an experiment to help solve that problem?
    [ 5] [PromptWizard 2024] Make a list of ideas for solving this problem, and apply them one by o...
    [ 6] [PromptWizard 2024] How could I measure progress on this problem?
    [ 7] [PromptWizard 2024] How can I simplify the problem so that it is easier to solve?
    [ 8] [PromptWizard 2024] What are the key assumptions underlying this problem?
    [ 9] [PromptWizard 2024] What are the potential risks and drawbacks of each solution?
    [10] [PromptWizard 2024] What are the alternative perspectives or viewpoints on this problem?
    [11] [PromptWizard 2024] What are the long-term implications of this problem and its solutions?
    [12] [PromptWizard 2024] How can I break down this problem into smaller, more manageable parts?
    [13] [PromptWizard 2024] Critical Thinking: This style involves analyzing the problem from diff...
    [14] [PromptWizard 2024] Try creative thinking, generate innovative and out-of-the-box ideas to...
    [15] [PromptWizard 2024] Seek input and collaboration from others to solve the problem. Emphasi...
    [16] [PromptWizard 2024] Use systems thinking: Consider the problem as part of a larger system ...
    [17] [PromptWizard 2024] Use Risk Analysis: Evaluate potential risks, uncertainties, and tradeo...
    [18] [PromptWizard 2024] Use Reflective Thinking: Step back from the problem, take the time for...
    [19] [PromptWizard 2024] What is the core issue or problem that needs to be addressed?
    [20] [PromptWizard 2024] What are the underlying causes or factors contributing to the problem?
    [21] [PromptWizard 2024] Are there any potential solutions or strategies that have been tried b...
    [22] [PromptWizard 2024] What are the potential obstacles or challenges that might arise in sol...
    [23] [PromptWizard 2024] Are there any relevant data or information that can provide insights i...
    [24] [PromptWizard 2024] Are there any stakeholders or individuals who are directly affected by...
    [25] [PromptWizard 2024] What resources (financial, human, technological, etc.) are needed to t...
    [26] [PromptWizard 2024] How can progress or success in solving the problem be measured or eval...
    [27] [PromptWizard 2024] What indicators or metrics can be used?
    [28] [PromptWizard 2024] Is the problem a technical or practical one that requires a specific e...
    [29] [PromptWizard 2024] Does the problem involve a physical constraint, such as limited resour...
    [30] [PromptWizard 2024] Is the problem related to human behavior, such as a social, cultural, ...
    [31] [PromptWizard 2024] Does the problem involve decision-making or planning, where choices ne...
    [32] [PromptWizard 2024] Is the problem an analytical one that requires data analysis, modeling...
    [33] [PromptWizard 2024] Is the problem a design challenge that requires creative solutions and...
    [34] [PromptWizard 2024] Does the problem require addressing systemic or structural issues rath...
    [35] [PromptWizard 2024] Is the problem time-sensitive or urgent, requiring immediate attention...
    [36] [PromptWizard 2024] What kinds of solution typically are produced for this kind of problem...
    [37] [PromptWizard 2024] Given the problem specification and the current best solution, have a ...
    [38] [PromptWizard 2024] Let's imagine the current best solution is totally wrong, what other w...
    [39] [PromptWizard 2024] What is the best way to modify this current best solution, given what ...
    [40] [PromptWizard 2024] Ignoring the current best solution, create an entirely new solution to...
    [41] [PromptWizard 2024] Let's make a step by step plan and implement it with good notion and e...

  answer_format (3 variants — PromptPotter: 3)
    [ 0] [PromptPotter] (empty baseline)
    [ 1] [PromptPotter] Rank all candidates from most to least relevant.
    [ 2] [PromptPotter] Return only the single best match.

  problem_description (1 variants — PromptPotter: 1)
    [ 0] [PromptPotter] (empty baseline)

{'prompt_fields': {'persona': [{'text': '', 'source': 'PromptPotter'},
   {'text': 'You are a domain expert with deep knowledge of this field.',
    'source': 'PromptPotter'},
   {'text': 'You are a precise, analytical system that evaluates candidates methodically.',
    'source': 'PromptPotter'},
   {'text': 'You are a careful assistant that considers all options before deciding.',
    'source': 'PromptPotter'},
   {'text': 'You are a specialist who evaluates candidates based on domain-specific criteria and professional standards.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'You are a meticulous researcher who cross-references information before making judgments.',
    'source': 'PromptWizard',
    'year': 2024}],
  'task_intent': [{'text': '', 'source': 'PromptPotter'},
   {'text': 'Your task is to identify the single best match from the candidates.',
    'source': 'PromptPotter'},
   {'text': 'Rank candidates by how well they match the concept described.',
    'source': 'PromptPotter'},
   {'text': 'Evaluate each candidate for semantic equivalence to the query concept, considering domain context.',
    'source': 'PromptPotter'}],
  'thinking_style': [{'text': '', 'source': 'PromptPotter'},
   {'text': 'Think step by step.', 'source': 'PromptPotter'},
   {'text': 'Focus on semantic meaning, not surface-level word overlap.',
    'source': 'PromptPotter'},
   {'text': 'First understand the core concept, then evaluate each candidate against it.',
    'source': 'PromptPotter'},
   {'text': 'How could I devise an experiment to help solve that problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Make a list of ideas for solving this problem, and apply them one by one to the problem to see if any progress can be made.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'How could I measure progress on this problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'How can I simplify the problem so that it is easier to solve?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What are the key assumptions underlying this problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What are the potential risks and drawbacks of each solution?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What are the alternative perspectives or viewpoints on this problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What are the long-term implications of this problem and its solutions?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'How can I break down this problem into smaller, more manageable parts?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Critical Thinking: This style involves analyzing the problem from different perspectives, questioning assumptions, and evaluating the evidence or information available. It focuses on logical reasoning, evidence-based decision-making, and identifying potential biases or flaws in thinking.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Try creative thinking, generate innovative and out-of-the-box ideas to solve the problem. Explore unconventional solutions, thinking beyond traditional boundaries, and encouraging imagination and originality.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Seek input and collaboration from others to solve the problem. Emphasize teamwork, open communication, and leveraging the diverse perspectives and expertise of a group to come up with effective solutions.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Use systems thinking: Consider the problem as part of a larger system and understanding the interconnectedness of various elements. Focuses on identifying the underlying causes, feedback loops, and interdependencies that influence the problem, and developing holistic solutions that address the system as a whole.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Use Risk Analysis: Evaluate potential risks, uncertainties, and tradeoffs associated with different solutions or approaches to a problem. Emphasize assessing the potential consequences and likelihood of success or failure, and making informed decisions based on a balanced analysis of risks and benefits.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Use Reflective Thinking: Step back from the problem, take the time for introspection and self-reflection. Examine personal biases, assumptions, and mental models that may influence problem-solving, and being open to learning from past experiences to improve future approaches.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What is the core issue or problem that needs to be addressed?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What are the underlying causes or factors contributing to the problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Are there any potential solutions or strategies that have been tried before? If yes, what were the outcomes and lessons learned?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What are the potential obstacles or challenges that might arise in solving this problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Are there any relevant data or information that can provide insights into the problem? If yes, what data sources are available, and how can they be analyzed?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Are there any stakeholders or individuals who are directly affected by the problem? What are their perspectives and needs?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What resources (financial, human, technological, etc.) are needed to tackle the problem effectively?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'How can progress or success in solving the problem be measured or evaluated?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What indicators or metrics can be used?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Is the problem a technical or practical one that requires a specific expertise or skill set? Or is it more of a conceptual or theoretical problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Does the problem involve a physical constraint, such as limited resources, infrastructure, or space?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Is the problem related to human behavior, such as a social, cultural, or psychological issue?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Does the problem involve decision-making or planning, where choices need to be made under uncertainty or with competing objectives?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Is the problem an analytical one that requires data analysis, modeling, or optimization techniques?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Is the problem a design challenge that requires creative solutions and innovation?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Does the problem require addressing systemic or structural issues rather than just individual instances?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Is the problem time-sensitive or urgent, requiring immediate attention and action?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What kinds of solution typically are produced for this kind of problem specification?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Given the problem specification and the current best solution, have a guess about other possible solutions.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': "Let's imagine the current best solution is totally wrong, what other ways are there to think about the problem specification?",
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What is the best way to modify this current best solution, given what you know about these kinds of problem specification?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Ignoring the current best solution, create an entirely new solution to the problem.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': "Let's make a step by step plan and implement it with good notion and explanation.",
    'source': 'PromptWizard',
    'year': 2024}],
  'answer_format': [{'text': '', 'source': 'PromptPotter'},
   {'text': 'Rank all candidates from most to least relevant.',
    'source': 'PromptPotter'},
   {'text': 'Return only the single best match.', 'source': 'PromptPotter'}],
  'problem_description': [{'text': '', 'source': 'PromptPotter'}]}}

In [24]:
# preview_advisor_prompt()
preview_advisor_prompt(campaign_config, svc, task_description="TASK_DESCRIPTION", raw=True)

2026-03-17 16:28:22 INFO     [api.services.search.smart_search] filter_variant_library: dropped all prompt_fields (llm_ranking not active)

You are an expert prompt optimization advisor. Recommend which axes (parameters and prompt fields) to prioritize in a sensitivity scan.

## Constraints (apply strictly)
- Do NOT recommend *_model axes — place them in axes_to_skip.
- Response must fit within 1500 tokens. Be terse.

## Pipeline: TermNorm AI terminology normalization pipeline
Steps execute sequentially — each step's output feeds the next:
[
  {
    "name": "cache_lookup",
    "node_role": "cache",
    "short_circuit": true
  },
  {
    "name": "fuzzy_matching",
    "node_role": "candidate_source",
    "short_circuit": true
  },
  {
    "name": "web_search",
    "node_role": "enricher"
  },
  {
    "name": "entity_profiling",
    "node_role": "enricher"
  },
  {
    "name": "token_matching",
    "node_role": "candidate_source"
  }
]

## Task Context
TASK_DESCRIPTION
## Tunable Parameters (per step)
[
  {
    "name": "fuzzy_matching",
    "param_keys": [
      "fuzzy_scorer",
      "fuzzy_threshold"
    ]
  },
  {
    "name": "web_search",
    "param_keys": [
      "content_char_limit",
      "max_sites",
      "num_results",
      "query_prefix",
      "query_suffix"
    ],
    "current_values": {
      "max_sites": 7,
      "num_results": 20,
      "content_char_limit": 800,
      "query_prefix": "",
      "query_suffix": ""
    }
  },
  {
    "name": "entity_profiling",
    "param_keys": [
      "profiling_max_tokens",
      "profiling_model",
      "profiling_prompt",
      "profiling_schema",
      "profiling_temperature",
      "raw_content_limit"
    ],
    "current_values": {
      "raw_content_limit": 5000
    }
  },
  {
    "name": "token_matching",
    "param_keys": [
      "max_token_candidates"
    ],
    "current_values": {
      "max_token_candidates": 20
    }
  }
]

## Prompt Field Axes
Prompt template fields that can be varied (variant library has pre-defined values):
[]

## LLM Node Details
Output schema fields and prompt metadata for LLM-driven steps:
[
  {
    "name": "entity_profiling",
    "output_schema": {
      "entity_name": "string",
      "core_concept": "string \u2014 The single word that defines what this expression represents",
      "distinguishing_features": "array",
      "key_properties": "array",
      "technical_specifications": "array \u2014 Explicit technical specs, dimensions, codes, ratings, tolerances",
      "alternative_names": "array",
      "classification_aliases": "array \u2014 Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic",
      "constituent_materials": "array \u2014 All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge",
      "manufacturing_processes": "array \u2014 Both stated and inferred manufacturing processes based on product type, materials, and industry standards",
      "applications": "array \u2014 Direct and derived applications based on product characteristics",
      "notes": "array"
    },
    "prompt_meta": {
      "family": "entity_profiling",
      "template_variables": [
        "query",
        "format_string",
        "combined_text"
      ],
      "description": "Extract comprehensive entity profile from web research data with US/GB spelling variants"
    }
  }
]
## Analysis Approach
Work through these steps before producing your recommendation:
1. Trace data flow: UPSTREAM parameters have multiplier effects — poor upstream data cannot be compensated by downstream tuning.
2. Flag high-impact targets: empty or default string params (prefixes, suffixes, query modifiers) that shape what data enters the pipeline.
3. For *_schema axes: identify output fields that are redundant or missing for downstream consumption. Suggest mutations relative to the current output_schema shown in LLM Node Details.
4. Skip axes unlikely to affect accuracy. Prioritize axes with the highest expected impact on end-to-end accuracy.
5. Estimate a diagnostic budget (queries per axis).

## Output Format
For pipeline_param axes, suggest concrete values that meaningfully differ from current_values. For prompt_field axes, just flag them — the variant library already has values.

Return a JSON object with this structure:
{
  "priority_axes": [
    {
      "axis": "<param_name>",
      "source": "pipeline_param",
      "step": "<step_name>",
      "rationale": "...",
      "suggested_values": ["<val>", "..."],
      "importance": "<high|medium|low>"
    },
    {
      "axis": "<field_name>",
      "source": "prompt_field",
      "rationale": "...",
      "importance": "<high|medium|low>"
    }
  ],
  "suggested_n_diagnostic": 6,
  "axes_to_skip": [
    {"axis": "<name>", "reason": "..."}
  ],
  "budget_breakdown": {
    "<axis_name>": <n_queries>,
    "total": <sum>
  },
  "reasoning": "Overall strategy explanation..."
}

Rules:
- rationale: max 15 words
- reasoning: max 2 sentences
- axes_to_skip reason: max 10 words
- suggested_values: 2-4 values, numbers or short strings only
- importance: "high", "medium", or "low"
- source: "pipeline_param" or "prompt_field"
- For pipeline_param axes: include "step" and "suggested_values"
- For prompt_field axes: omit "step" and "suggested_values"
- *_schema mutations: each suggested_value is a JSON array of mutation arrays. Ops: ["-","path"] remove | ["+","path","type",required,"desc"] add | ["~","old","new","type",required,"desc"] replace. Types: string|array|integer|number|boolean|object. required: true|false. Baseline included automatically — do NOT include it. Keep each variant to 1-2 mutations so individual effects are measurable.

Return ONLY the JSON object, no markdown fences or extra text.

In [25]:
#@title Scan advisor
advisory, scan_variants, schema_labels = await run_scan_advisor(
    campaign_config, svc,
    task_description=TASK_DESCRIPTION if "TASK_DESCRIPTION" in dir() else "",
)

2026-03-17 16:28:22 INFO     [api.services.search.smart_search] filter_variant_library: dropped all prompt_fields (llm_ranking not active)

======================================================================
SCAN ADVISOR -- pipeline-aware sensitivity setup
======================================================================
  Pipeline: termnorm (v1.1)
  Steps: ['cache_lookup', 'fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching', 'llm_ranking']
  Excluded: ['llm_ranking']
  Task context: # Domain Context: Life Cycle Assessment (LCA) Terminology

This document capture...
  Calling openai/gpt-oss-120b ...

2026-03-17 16:28:27 INFO     [httpx] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

----------------------------------------------------------------------
PRIORITY AXES (ranked by importance)
----------------------------------------------------------------------
  1. [HIGH] fuzzy_threshold (pipeline_param) -- step: fuzzy_matching
     Controls match acceptance; tight thresholds reduce false positives
     Values: ['0.7', '0.85', '0.95']
  2. [MEDIUM] fuzzy_scorer (pipeline_param) -- step: fuzzy_matching
     Different scorers handle abbreviations vs numbers differently
     Values: ['ratio', 'partial_ratio', 'token_set_ratio']
  3. [HIGH] query_prefix (pipeline_param) -- step: web_search
     Guides search engine toward material context
     Values: ['', 'material', 'chemical']
  4. [HIGH] query_suffix (pipeline_param) -- step: web_search
     Adds domain‑specific qualifiers for better results
     Values: ['', 'datasheet', 'specifications']
  5. [MEDIUM] max_sites (pipeline_param) -- step: web_search
     Limits sites to balance coverage vs noise
     Values: ['5', '10', '15']
  6. [MEDIUM] max_token_candidates (pipeline_param) -- step: token_matching
     More candidates improve recall but increase downstream load
     Values: ['10', '30', '50']

----------------------------------------------------------------------
AXES TO SKIP
----------------------------------------------------------------------
  - profiling_model: model axis
  - profiling_temperature: model axis

----------------------------------------------------------------------
BUDGET BREAKDOWN
----------------------------------------------------------------------
  fuzzy_threshold: 1
  fuzzy_scorer: 1
  query_prefix: 1
  query_suffix: 1
  max_sites: 1
  max_token_candidates: 1
  total: 6

  Suggested n_diagnostic: 6

----------------------------------------------------------------------
REASONING
----------------------------------------------------------------------
  Focus on upstream matching and search shaping; skip model‑specific knobs. Six targeted diagnostics cover high‑impact levers.
======================================================================

--- PROPOSED SCAN VARIANTS (copy-paste into next cell) ---
scan_variants = {
    'fuzzy_threshold': ['0.7', '0.85', '0.95'],
    'fuzzy_scorer': ['ratio', 'partial_ratio', 'token_set_ratio'],
    'query_prefix': ['', 'material', 'chemical'],
    'query_suffix': ['', 'datasheet', 'specifications'],
    'max_sites': ['5', '10', '15'],
    'max_token_candidates': ['10', '30', '50'],
}

In [26]:
#@title Scan variant config (edit suggested values or add your own)
# Schema axes: mutation tuples ("-", path), ("+", path, type, req, desc),
# ("~", old, new, type, req, desc). Non-schema axes: plain value lists.

scan_sample_size = 10  # queries per scan variant (0 = use all)

scan_variants = {
    'max_token_candidates': [10, 30, 50],
    'query_prefix': ['what material is', 'identify LCA database name for', 'translate trade name'],
    'profiling_schema': [
        [['+', 'geography_scope', 'array', False, 'Relevant ecoinvent/SimaPro geography codes inferred from context, e.g. GLO, RER, CH, RNA'], ['+', 'database_format_hint', 'string', False, "Best-guess ecoinvent-style name fragment for this entity, e.g. 'market for polyethylene, high density'"]],
        # [['-', 'manufacturing_processes'], ['-', 'applications'], ['+', 'lca_synonyms', 'array', False, 'Terms likely to appear verbatim in LCA database entry names for this entity'], ['+', 'no_match_signal', 'string', False, 'Brief reasoning on whether a database match is likely to exist or not']],
        # [['~', 'classification_aliases', 'lca_classification_aliases', 'array', False, 'Expert-level aliases specifically aligned with LCA database naming conventions, including ecoinvent activity names and SimaPro process names'], ['+', 'geography_scope', 'array', False, 'Relevant ecoinvent/SimaPro geography codes inferred from context, e.g. GLO, RER, CH, RNA']],
        [['+', 'lca_database_names', 'array', True, "Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'"]], 
        [['-', 'manufacturing_processes'], ['-', 'applications'], ['+', 'lca_database_names', 'array', True, 'Likely ecoinvent or GaBi database entry names for this entity using standard LCA naming conventions']],
        [['~', 'notes', 'material_category', 'string', True, "The broad LCA material category this entity belongs to, e.g. 'polyethylene', 'brass', 'steel'"]]
    ],
    'profiling_temperature': [0.0, 0.3, 0.7],
    # 'profiling_max_tokens': [512, 1024, 2048], # -> Going to cause lots of Errors.
    'raw_content_limit': [1000, 2500, 8000],
}
scan_variants, schema_labels = resolve_scan_variants(scan_variants, svc=svc)

  max_token_candidates: [10, 30, 50]
  query_prefix: ['what material is', 'identify LCA database name for', 'translate trade name']
  profiling_schema: (baseline + 4 mutations)
    [0] (baseline)
    [1] ('+', 'geography_scope', 'array', False, 'Relevant ecoinvent/SimaPro geography codes inferred from context, e.g. GLO, RER, CH, RNA'), ('+', 'database_format_hint', 'string', False, 'Best-guess ecoinvent-style name fragment for this entity, e.g. 'market for polyethylene, high density'')
    [2] ('+', 'lca_database_names', 'array', True, 'Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'')
    [3] ('-', 'manufacturing_processes'), ('-', 'applications'), ('+', 'lca_database_names', 'array', True, 'Likely ecoinvent or GaBi database entry names for this entity using standard LCA naming conventions')
    [4] ('~', 'notes', 'material_category', 'string', True, 'The broad LCA material category this entity belongs to, e.g. 'polyethylene', 'brass', 'steel'')
  profiling_temperature: [0.0, 0.3, 0.7]
  raw_content_limit: [1000, 2500, 8000]

In [ ]:
#@title Prepare scan baseline
# Uses configure_pipeline() output (pre-seeding defaults), not campaign pipeline_params.
# The scan explores from defaults; seeded params are for the feedback cycle.
_scan_pp = configure_pipeline(svc, campaign_config)
baseline_sp, scan_coverage = await prepare_scan_baseline(
    baseline, campaign_config,
    pipeline_params=_scan_pp,
    store=svc["store"], backend_id=svc["backend_id"],
    scan_variants=scan_variants,
)

In [ ]:
#@title Sensitivity scan
scan_df, axis_profiles = await sensitivity_scan(
    baseline_sp, scan_variants, eval_data, svc.get("backend_client"),
    sample_size=scan_sample_size,
    store=svc["store"], backend_id=svc["backend_id"],
    pipeline_schema=svc.get("pipeline_schema"),
    experiment_id=EXPERIMENT_ID if "EXPERIMENT_ID" in dir() and EXPERIMENT_ID else "",
    scan_coverage=scan_coverage if "scan_coverage" in dir() else None,
)

In [ ]:
#@title Scan analytics: variant leaderboard
if scan_df is not None and not scan_df.empty:
    show_scan_leaderboard(scan_df, axis_profiles)

VARIANT LEADERBOARD (all scan combos)
======================================================================

,rank,axis,variant,accuracy,delta,hits/total,errors
0,1,max_token_candidates,30,30.0%,+18.0%,3/10,0
1,2,profiling_schema,schema(12 fields),20.0%,+9.2%,2/10,0
2,3,query_prefix,what material is,20.0%,+9.2%,2/10,0
3,4,profiling_temperature,0.3,20.0%,+9.0%,2/10,0
4,5,max_token_candidates,50,20.0%,+9.0%,2/10,0
5,6,raw_content_limit,8000,10.0%,+0.3%,1/10,0
6,7,profiling_schema,schema(11 fields),10.0%,+0.3%,1/10,0
7,8,profiling_schema,schema(11 fields),10.0%,+0.3%,1/10,0
8,9,raw_content_limit,1000,10.0%,+0.3%,1/10,0
9,10,profiling_temperature,0.7,10.0%,+0.3%,1/10,0
10,11,profiling_schema,schema(10 fields) (baseline),10.0%,-,1/10,0
11,12,profiling_temperature,0.0,0.0%,-8.8%,0/10,0
12,13,query_prefix,identify LCA database name for,0.0%,-8.8%,0/10,0
13,14,raw_content_limit,2500,0.0%,-8.8%,0/10,0
14,15,profiling_schema,schema(13 fields),0.0%,-8.8%,0/10,0
15,16,max_token_candidates,10,0.0%,-9.0%,0/10,0
16,17,query_prefix,translate trade name,0.0%,-9.2%,0/10,0

PER-AXIS STATISTICS
======================================================================

,axis,type,variants,mean_acc,std_acc,best_acc,worst_acc,sensitivity,budget
0,max_token_candidates,pipeline_param,3,16.7%,15.3%,30.0%,0.0%,0.270,medium
1,query_prefix,pipeline_param,3,6.7%,11.5%,20.0%,0.0%,0.185,medium
2,profiling_schema,pipeline_param,5,10.0%,7.1%,20.0%,0.0%,0.180,medium
3,profiling_temperature,pipeline_param,3,10.0%,10.0%,20.0%,0.0%,0.177,medium
4,raw_content_limit,pipeline_param,3,6.7%,5.8%,10.0%,0.0%,0.090,skip

In [ ]:
#@title Scan analytics: query difficulty
if scan_df is not None and not scan_df.empty:
    difficulty_df = show_scan_query_difficulty(
        svc["store"], svc["backend_id"],
    )

QUERY DIFFICULTY (728 queries across 59 scan runs)
======================================================================
  easy: 0 (0%) | discriminating: 5 (1%) | hard: 5 (1%) | error: 718 (99%)

,query,ground_truth,hit_rate,hits/evals,error_rate,classification
0,"BAND EN 10140-1,45x26 GK-DC01+C390-MB","Steel, unalloyed {GLO}| market for steel, unal...",0.000000,0/11,1.000000,error
1,"Kaltband EN 10140-2,5 x ... GK\nStahl EN 10139...","Steel removed by milling, small parts {RER}| s...",0.000000,0/11,1.000000,error
2,Adhesive label 13x5 white\nPolyethylen (PE) we...,"Polyethylene, low density, granulate {GLO}| ma...",0.000000,0/11,1.000000,error
3,"Strip EN13599-CU-PHC-R290-1,8x35-Ag0,3 /stamping","Metal working, average for copper product manu...",0.000000,0/22,1.000000,error
4,PA 66 25% GF V0 RAL 7012/0,Injection moulding {RoW}| injection moulding |...,0.000000,0/70,0.542857,hard
...,...,...,...,...,...,...
723,SJRG0013-PA/molding,Injection moulding {RER}| injection moulding |...,0.025000,1/40,0.550000,discriminating
724,SJRG0010-ABS/molding,Injection moulding {RER}| injection moulding |...,0.050847,3/59,0.457627,discriminating
725,Kingfa NPG25,Glass fibre reinforced plastic | 75% PA66 25% ...,0.220339,13/59,0.457627,discriminating
726,PA66-GF25 ULTRAMID A3UG5 RAL7035 grey,Glass fibre reinforced plastic | 75% PA66 25% ...,0.288136,17/59,0.457627,discriminating
727,Stainless steel EN 10270-3/winding,"Wire drawing, steel {RER}| wire drawing, steel...",0.357143,25/70,0.542857,discriminating

In [ ]:
#@title Select scan winner & seed campaign
best_sp = seed_campaign_from_scan(
    scan_df, axis_profiles, baseline_sp, scan_variants,
    campaign_rounds, campaign_config,
)

2026-03-17 15:43:08 INFO     [api.services.search.scan_winner] select_scan_winner: 0 prompt changes, 4 param changes from 4 improving axes

Selected best from 4 improving axes:
  max_token_candidates      best_delta=+18.0%  value_idx=1  acc=30.0%
  query_prefix              best_delta=+9.2%  value_idx=0  acc=20.0%
  profiling_schema          best_delta=+9.2%  value_idx=2  acc=20.0%
  profiling_temperature     best_delta=+9.0%  value_idx=1  acc=20.0%
Pipeline params updated: {'steps': ['cache_lookup', 'fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching'], 'max_token_candidates': 30, 'query_prefix': 'what material is', 'profiling_schema': {'type': 'object', 'properties': {'entity_name': {'type': 'string'}, 'core_concept': {'type': 'string', 'description': 'The single word that defines what this expression represents'}, 'distinguishing_features': {'type': 'array', 'items': {'type': 'string'}}, 'key_properties': {'type': 'array', 'items': {'type': 'string'}}, 'technical_specifications': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Explicit technical specs, dimensions, codes, ratings, tolerances'}, 'alternative_names': {'type': 'array', 'items': {'type': 'string'}}, 'classification_aliases': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic'}, 'constituent_materials': {'type': 'array', 'items': {'type': 'string'}, 'description': 'All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge'}, 'manufacturing_processes': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Both stated and inferred manufacturing processes based on product type, materials, and industry standards'}, 'applications': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Direct and derived applications based on product characteristics'}, 'notes': {'type': 'array', 'items': {'type': 'string'}}, 'lca_database_names': {'type': 'array', 'items': {'type': 'string'}, 'description': "Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'"}}, 'required': ['entity_name', 'core_concept', 'distinguishing_features', 'key_properties', 'technical_specifications', 'alternative_names', 'classification_aliases', 'constituent_materials', 'manufacturing_processes', 'applications', 'notes', 'lca_database_names']}, 'profiling_temperature': 0.3}
Updated pipeline_params: {'steps': ['cache_lookup', 'fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching'], 'max_token_candidates': 30, 'query_prefix': 'what material is', 'profiling_schema': {'type': 'object', 'properties': {'entity_name': {'type': 'string'}, 'core_concept': {'type': 'string', 'description': 'The single word that defines what this expression represents'}, 'distinguishing_features': {'type': 'array', 'items': {'type': 'string'}}, 'key_properties': {'type': 'array', 'items': {'type': 'string'}}, 'technical_specifications': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Explicit technical specs, dimensions, codes, ratings, tolerances'}, 'alternative_names': {'type': 'array', 'items': {'type': 'string'}}, 'classification_aliases': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic'}, 'constituent_materials': {'type': 'array', 'items': {'type': 'string'}, 'description': 'All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge'}, 'manufacturing_processes': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Both stated and inferred manufacturing processes based on product type, materials, and industry standards'}, 'applications': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Direct and derived applications based on product characteristics'}, 'notes': {'type': 'array', 'items': {'type': 'string'}}, 'lca_database_names': {'type': 'array', 'items': {'type': 'string'}, 'description': "Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'"}}, 'required': ['entity_name', 'core_concept', 'distinguishing_features', 'key_properties', 'technical_specifications', 'alternative_names', 'classification_aliases', 'constituent_materials', 'manufacturing_processes', 'applications', 'notes', 'lca_database_names']}, 'profiling_temperature': 0.3}

Round    Accuracy   Rolling Avg    Trend
  search    10.0%        10.0%  -

### 3b. Grid Search

<details>
<summary>Skip if you used Smart Search above.</summary>

Systematic sweep of the prompt configuration space. Maps the accuracy landscape before hill-climbing.

</details>

In [ ]:
# #@title Grid campaign overview (existing plans)
# merge_plans = False  # Set True to combine results from multiple plans
# grid_overview = show_grid_overview(svc, campaign_config, merge_plans=merge_plans)
# merged_grid_df = grid_overview.get("merged_grid_df")

In [ ]:
# #@title Build or resume grid plan
# gs = campaign_config["grid_search"]

# llm_client, llm_model = setup_llm(campaign_config)

# (
#     grid_plan_id, grid_points, grid_state_lookup,
#     grid_axes, layer1_fields, grid_baseline,
# ) = await resume_or_build_grid(
#     campaign_config, baseline, llm_client, llm_model,
#     svc["store"], svc["backend_id"],
#     improvement_areas=campaign_config.get("improvement_areas", ""),
# )

# print(f"Grid points: {len(grid_points)}")
# print(f"Plan ID: {grid_plan_id}")

In [ ]:
# #@title Run grid search
# grid_df = await run_grid_search(
#     grid_points, grid_state_lookup, eval_data,
#     campaign_config["eval_llm"],
#     plan_id=grid_plan_id,
#     store=svc["store"], backend_id=svc["backend_id"],
#     backend_client=svc.get("backend_client"),
#     session_terms=svc.get("session_terms"),
#     pipeline_params=campaign_config.get("pipeline_params"),
#     sample_size=gs.get("sample_size", 1),
#     shared_queries=gs.get("shared_queries", False),
#     grid_seed=gs.get("seed", 42),
# )

In [ ]:
# #@title Display grid results
# _display_df = merged_grid_df if merged_grid_df is not None else grid_df
# display_grid_results(_display_df, grid_axes, top_k=gs.get("top_k", 5))

In [ ]:
# #@title LLM analysis of grid results
# _analysis_df = merged_grid_df if merged_grid_df is not None else grid_df
# llm_client, llm_model = setup_llm(campaign_config)
# grid_analysis = await analyze_grid_results(
#     _analysis_df, grid_axes, llm_client, model=llm_model,
# )

In [ ]:
# #@title Select grid winner and seed campaign
# grid_winner = select_and_seed_grid_winner(
#     grid_df, merged_grid_df, grid_state_lookup,
#     grid_overview.get("plan_dfs", {}), svc, campaign_rounds,
# )

## 4. Optimize

Two modes: **Semi-automatic** (feedback cycle with patience-based auto-stop) or **Manual** (one round at a time).

In [ ]:
#@title Feedback cycle preflight
scan_context = show_feedback_preflight(
    campaign_rounds, eval_data, campaign_config,
    pipeline_params=pipeline_params,
    scan_df=scan_df if "scan_df" in dir() else None,
    axis_profiles=axis_profiles if "axis_profiles" in dir() else None,
    scan_variants=scan_variants if "scan_variants" in dir() else None,
    difficulty_df=difficulty_df if "difficulty_df" in dir() else None,
)

In [ ]:
#@title Run optimization (feedback cycle)
campaign_rounds = await run_feedback_cycle_notebook(
    campaign_rounds, eval_data, campaign_config,
    store=svc["store"], backend_id=svc["backend_id"],
    backend_url=svc["backend_client"].base_url,
    pipeline_params=pipeline_params,
    session_terms=svc.get("session_terms"),
    scan_context=scan_context if "scan_context" in dir() else None,
    experiment_id=EXPERIMENT_ID if "EXPERIMENT_ID" in dir() else None,
)

In [ ]:
#@title Run optimization round (manual)
round_entry = await run_manual_round(
    campaign_rounds, eval_data, campaign_config, svc,
    experiment_id=EXPERIMENT_ID if "EXPERIMENT_ID" in dir() else None,
)

## 5. Results

In [ ]:
#@title Campaign comparison table
show_campaign_summary(campaign_rounds)

In [ ]:
#@title Per-query flip tracking (baseline vs final)
show_flip_tracking(campaign_rounds)

In [ ]:
#@title PromptState lineage chain
show_lineage_chain(campaign_rounds)

In [ ]:
#@title Save winner
save_campaign_winner(campaign_rounds, campaign_config, svc["store"], svc["backend_id"])

In [ ]:
#@title Generate LLM suggestions for next round
llm_client, llm_model = setup_llm(campaign_config)
suggestions = await generate_suggestions(
    campaign_rounds, eval_data, campaign_config,
    llm_client, model=llm_model,
)
display_suggestions(suggestions, len(campaign_rounds))
print("--- SUGGESTED CONFIG (copy to Setup) ---")
print(json.dumps(suggestions.get("suggested_config", campaign_config), indent=2))

In [ ]:
#@title Sync evaluation history to Langfuse
# Safe to re-run — already-pushed runs are skipped automatically.
stats = sync_langfuse(
    svc["store"], svc["backend_id"],
    dataset_name="termnorm_ground_truth",
)