# Optimization Campaign (HITL)

**Prerequisites:** TermNorm backend at `http://127.0.0.1:8000` | Groq API key in `.env` | Restart kernel after first sync

**Workflow:** Setup → Data → Explore → Optimize → Results

## 1. Setup

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import json
from _campaign_lib import *

svc = await init_services()
TASK_DESCRIPTION = load_task_description(
    r"C:\Users\dsacc\OfficeAddinApps\TermNorm-excel\backend-api\config\LCA_INPUT_PATTERNS.md"
)

2026-03-13 15:40:54 INFO     [httpx] HTTP Request: GET http://127.0.0.1:8000/pipeline "HTTP/1.1 200 OK"
2026-03-13 15:40:54 INFO     [api.services.pipeline_discovery] Matched known pipeline 'termnorm'; using enriched schema
2026-03-13 15:40:54 INFO     [api.services.campaign.campaign_init] Pipeline schema loaded: termnorm vv1.1

Experiment : production_historical
Mappings   : 887 total, 812 with verified ground truth
Queries    : 40  |  Session terms: 93
Loaded task description: 3751 chars from LCA_INPUT_PATTERNS.md

In [3]:
campaign_config = {
    "sample_size": 15,              # queries per eval step (service default: all)
    "exploration_rate": 0.5,             # PRIMARY KNOB: 0.0=conservative, 1.0=aggressive
    "improvement_areas": "profile schema quality, web search relevance",
    "exclude_steps": ["llm_ranking"],    # steps to skip (e.g. ["entity_profiling"])
    "pipeline_overrides": {},
    "optimization": {
        "patience": 2,                   # default: 3
        "max_rounds": 3,                 # default: 10
    },
    "eval_llm": {
        # --- Groq (free tier, open-source models) ---
        "model": "openai/gpt-oss-120b",
        # "model": "moonshotai/kimi-k2-instruct-0905"
        "provider_url": "https://api.groq.com/openai/v1/chat/completions",
        # --- Anthropic (cost: opus >> sonnet >> haiku) ---
        # "model": "claude-opus-4-6",          # best quality
        # "model": "claude-sonnet-4-6",      # good balance
        # "model": "claude-haiku-4-5-20251001",  # cheapest
        # "provider_url": "https://api.anthropic.com",
        "max_tokens": 2000,              # response length budget
    },
    "grid_search": {
        "context": "A terminology normalization pipeline that matches raw material "
                    "descriptions to standardized database terms using entity profiling "
                    "and candidate ranking.",
        "grid_budget": 35,               # default: 0 (full grid)
        "sample_size": 6,     # default: 0 (all queries)
        "shared_queries": False,          # default: True
    },
}

In [4]:
#@title Pipeline snapshot (full config for reproducibility)
pipeline_config_full = await show_pipeline_snapshot(svc)

2026-03-13 15:40:54 INFO     [httpx] HTTP Request: GET http://127.0.0.1:8000/pipeline "HTTP/1.1 200 OK"

======================================================================
  PIPELINE SNAPSHOT: TermNorm v1.1
======================================================================
  Nodes:   ['fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching', 'llm_ranking', 'direct_prompt']
  Schemas: ['entity_profile/1', 'llm_ranking_output/1']
  Prompts: ['entity_profiling/1', 'llm_ranking/1']

{
  "name": "TermNorm",
  "version": "v1.1",
  "available_models": [
    "moonshotai/kimi-k2-instruct-0905",
    "meta-llama/llama-4-scout-17b-16e-instruct",
    "moonshotai/kimi-k2-instruct",
    "openai/gpt-oss-120b"
  ],
  "nodes": {
    "fuzzy_matching": {
      "type": "DeterministicFunction",
      "config": {
        "threshold": 70,
        "scorer": "WRatio",
        "limit": 5
      }
    },
    "web_search": {
      "type": "ExternalService",
      "config": {
        "max_sites": 7,
        "num_results": 20,
        "content_char_limit": 800,
        "url_fetch_multiplier": 2,
        "fallback_keywords_limit": 8,
        "query_prefix": "",
        "query_suffix": "",
        "brave_api_timeout": 10,
        "scrape_timeout": 5,
        "http_content_limit": 50000,
        "min_page_text_length": 200,
        "max_page_text_length": 10000,
        "title_truncate_length": 100,
        "scrape_workers": 10,
        "skip_extensions": [
          ".pdf",
          ".doc",
          ".docx",
          ".ppt",
          ".pptx",
          ".xls",
          ".xlsx"
        ],
        "skip_domains": [
          "academia.edu",
          "researchgate.net",
          "arxiv.org",
          "ieee.org"
        ],
        "search_language": "en",
        "search_country": "US",
        "accept_language": "en-US,en;q=0.9",
        "html_strip_tags": [
          "script",
          "style",
          "nav",
          "header",
          "footer"
        ],
        "min_keyword_length": 3,
        "keyword_split_chars": [
          "/",
          "-"
        ],
        "spellcheck": true,
        "result_filter": "",
        "extra_snippets": false,
        "freshness": ""
      }
    },
    "entity_profiling": {
      "type": "LLMGeneration",
      "config": {
        "model": "moonshotai/kimi-k2-instruct-0905",
        "temperature": 0.3,
        "max_tokens": 1800,
        "raw_content_limit": 5000,
        "per_site_content_limit": 500,
        "prompt_family": "entity_profiling",
        "prompt_version": 1,
        "schema_family": "entity_profile",
        "schema_version": 1
      }
    },
    "token_matching": {
      "type": "DeterministicFunction",
      "config": {
        "max_token_candidates": 20,
        "tokenization_regex": "[a-zA-Z0-9]+"
      }
    },
    "llm_ranking": {
      "type": "LLMGeneration",
      "config": {
        "model": "moonshotai/kimi-k2-instruct-0905",
        "temperature": 0.0,
        "max_tokens": 4000,
        "sample_size": 20,
        "debug_output_limit": 20,
        "relevance_weight_core": 0.7,
        "prompt_family": "llm_ranking",
        "prompt_version": 1,
        "schema_family": "llm_ranking_output",
        "schema_version": 1
      }
    },
    "direct_prompt": {
      "type": "LLMGeneration",
      "config": {
        "model": "moonshotai/kimi-k2-instruct-0905",
        "temperature": 0.0,
        "max_tokens": 300,
        "accept_threshold": 0.75,
        "correction_top_n": 10
      }
    }
  },
  "pipelines": {
    "default": [
      "web_search",
      "entity_profiling",
      "token_matching",
      "llm_ranking"
    ]
  },
  "cache": {
    "high_confidence_threshold": 0.8,
    "verified_methods": [
      "UserChoice",
      "DirectEdit",
      "cached",
      "fuzzy"
    ]
  },
  "llm_defaults": {
    "provider": "groq",
    "model": "moonshotai/kimi-k2-instruct-0905",
    "timeout": 60,
    "retry_attempts": 3,
    "retry_backoff_base": 2,
    "token_estimation_multiplier": 1.3,
    "token_limit": 100000,
    "seed": null,
    "logprobs": null
  },
  "resolved_schemas": {
    "entity_profile/1": {
      "family": "entity_profile",
      "version": 1,
      "description": "Entity profile extraction schema for web research pipeline",
      "fields": [
        "entity_name",
        "core_concept",
        "distinguishing_features",
        "key_properties",
        "technical_specifications",
        "alternative_names",
        "classification_aliases",
        "constituent_materials",
        "manufacturing_processes",
        "applications",
        "notes"
      ],
      "json_schema": {
        "type": "object",
        "properties": {
          "entity_name": {
            "type": "string"
          },
          "core_concept": {
            "type": "string",
            "description": "The single word that defines what this expression represents"
          },
          "distinguishing_features": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "key_properties": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "technical_specifications": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Explicit technical specs, dimensions, codes, ratings, tolerances"
          },
          "alternative_names": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "classification_aliases": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic"
          },
          "constituent_materials": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge"
          },
          "manufacturing_processes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards"
          },
          "applications": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Direct and derived applications based on product characteristics"
          },
          "notes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "entity_name",
          "core_concept",
          "distinguishing_features",
          "key_properties",
          "technical_specifications",
          "alternative_names",
          "classification_aliases",
          "constituent_materials",
          "manufacturing_processes",
          "applications",
          "notes"
        ]
      }
    },
    "llm_ranking_output/1": {
      "family": "llm_ranking_output",
      "version": 1,
      "description": "LLM ranking step output schema \u2014 structured candidate evaluation",
      "fields": [
        "profile_summary",
        "core_concept_description",
        "ranked_candidates"
      ],
      "json_schema": {
        "type": "object",
        "properties": {
          "profile_summary": {
            "type": "string",
            "description": "1-2 sentence summary of the entity profile"
          },
          "core_concept_description": {
            "type": "string",
            "description": "Description of the core concept match"
          },
          "ranked_candidates": {
            "type": "array",
            "description": "Candidates ranked by relevance score",
            "items": {
              "type": "object",
              "properties": {
                "candidate": {
                  "type": "string"
                },
                "core_concept_score": {
                  "type": "number"
                },
                "spec_score": {
                  "type": "number"
                },
                "evaluation_reasoning": {
                  "type": "string"
                },
                "key_match_factors": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "spec_gaps": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "required": [
                "candidate",
                "core_concept_score",
                "spec_score",
                "evaluation_reasoning",
                "key_match_factors"
              ]
            }
          }
        },
        "required": [
          "profile_summary",
          "core_concept_description",
          "ranked_candidates"
        ]
      }
    }
  },
  "resolved_prompts": {
    "entity_profiling/1": {
      "family": "entity_profiling",
      "version": 1,
      "description": "Extract comprehensive entity profile from web research data with US/GB spelling variants",
      "template_variables": [
        "query",
        "format_string",
        "combined_text"
      ],
      "template": "You are a comprehensive technical database API specialized in exhaustive entity profiling. Extract ALL possible information about '{{query}}' from the research data and return it in this exact JSON format:\n{{format_string}}\n\nCRITICAL SPELLING REQUIREMENT: In ALL arrays, after each term, immediately add its US/GB spelling variant if different. Example: [\"colour\", \"color\", \"analyse\", \"analyze\"]. This is MANDATORY for every array field.\n\nCORE CONCEPT IDENTIFICATION: Within '{{query}}', certain words carry more semantic weight than others. Material names, product codes, and specifications describe WHAT is involved, but other terms describe the fundamental NATURE of what is being expressed. Identify the single word that defines the conceptual essence - typically the term that indicates an activity, action, method, or process rather than an object or material. Output only this one defining word.\n\nPROFESSIONAL CLASSIFICATION ALIASES: Generate the full spectrum of expert-level references for this entity, spanning precise technical descriptors to broader categorical terms. These terms stem from domain-specific terminology and industry-standard nomenclature that professionals recognize. Include approximations and near-equivalent terms that experts use when exact terminology doesn't exist, accepting that some terms may not be perfect equivalents but represent the best available expert terminology for referencing similar concepts.\n\nGENERIC TECHNICAL INFERENCE INSTRUCTION: Given the product or technical description '{{query}}', perform comprehensive analysis to extract and infer:\n\n1. **Explicit Information**: Directly stated specifications, dimensions, materials, codes, and properties\n2. **Implicit Information**: Commonly associated materials, manufacturing processes, applications, and technical characteristics that are standard for this type of product/component, even if not explicitly mentioned\n3. **Manufacturing Processes**: Both stated and inferred processes based on product type, materials, and specifications\n4. **Material Composition**: Complete material breakdown including standard/typical materials used in such products\n5. **Applications & Use Cases**: Direct and derived applications based on product characteristics\n\n**Include domain knowledge**: Draw from technical standards, industry practices, and material science to infer missing but relevant information.\n\nCRITICAL INSTRUCTIONS FOR RICH ATTRIBUTE COLLECTION:\n- MAXIMIZE diversity: Include ALL synonyms, trade names, scientific names, abbreviations, acronyms, regional terms, industry terminology\n- COMPREHENSIVE extraction: Capture every property, specification, feature, attribute, including numerical values and compositional data\n- PRIORITIZE completeness over brevity: Aim for 5-10+ items per array field - be thorough, not minimal\n---\nRESEARCH DATA:\n{{combined_text}}\n---\nREMEMBER: Every term must be followed by its US/GB variant if different. Return only the JSON object with ALL fields maximally populated."
    },
    "llm_ranking/1": {
      "family": "llm_ranking",
      "version": 1,
      "description": "Rank candidate matches based on entity profile relevance with core concept weighting",
      "template_variables": [
        "core_concept",
        "entity_profile_json",
        "matches"
      ],
      "template": "You are a candidate evaluation expert.\n\nTASK 1: Analyze profile and core concept (PRIMARY FACTOR - 70% WEIGHT)\n- Summarize the profile in 1-2 sentences capturing key details\n- Identify the entity_category from the profile\n- Think step-by-step: What are the most important distinguishing features of this entity?\n- CRITICAL: Prioritize candidates that match the core_concept: '{{core_concept}}'\n- Higher match = more of the distinguishing features present in the candidate name\n\nTASK 2: Evaluate candidate matches (20 candidates provided)\n- Each candidate will receive a relevance_score from 0.0 to 1.0\n- 0.95+ : Exact or near-perfect semantic match (contains most/all distinguishing features + matches core_concept)\n- 0.80-0.94 : Strong match (contains several key features + aligns with core_concept)\n- 0.50-0.79 : Moderate match (contains some features OR loosely relates to core_concept)\n- 0.00-0.49 : Weak/poor match (missing most features, doesn't match core_concept)\n\nENTITY PROFILE (JSON):\n{{entity_profile_json}}\n\nCANDIDATE MATCHES TO EVALUATE:\n{{matches}}\n\nIMPORTANT: Return a valid JSON response matching this exact structure:\n{\n    \"reasoning\": \"[1-2 sentences explaining profile, entity_category, and key features]\",\n    \"ranked_candidates\": [\n        {\n            \"rank\": 1,\n            \"candidate\": \"...\",\n            \"relevance_score\": 0.95,\n            \"rationale\": \"[Brief explanation - 1 sentence]\"\n        }\n    ]\n}\n\nRules:\n- Include ALL 20 candidates in ranked_candidates array\n- Rank 1 = highest relevance_score\n- relevance_score must decrease or stay equal as rank increases\n- Return ONLY valid JSON, no other text"
    }
  }
}
======================================================================

In [5]:
#@title Build pipeline params
pipeline_params = configure_pipeline(svc, campaign_config)

Active steps: ['cache_lookup', 'fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching']
  Excluded: ['llm_ranking']

## 2. Data

In [6]:
#@title Load datasets
# Set EXCEL_PATH to load from BOM-example.xlsx; leave empty to use stored data
EXCEL_PATH = r"C:\Users\dsacc\Desktop\project-TermNorm\OneDrive_2025-07-02\Austausch Beispiele\Prozessnamen\BOM-example.xlsx"  # e.g. "../data/BOM-example.xlsx"
FORCE_RELOAD = False  # Set True to re-read Excel and overwrite stored datasets

train_data, svc["session_terms"] = prepare_datasets(
    svc["store"], svc["backend_id"],
    excel_path=EXCEL_PATH or None,
    force=FORCE_RELOAD,
)

==================================================
  Train              : 984 queries
  Test (processes)   : 82 queries
  Test (material)    : 165 queries
  ------------------------------------------------
  Combined queries   : 820 (deduplicated)
  Session identifiers: 94 unique targets
==================================================

In [7]:
#@title Prepare evaluation context
campaign_rounds = []
baseline_results = []

baseline, eval_data, backend_status = await prepare_eval_context(
    svc, train_data,
)

RUN_BASELINE = False  # Set True to evaluate baseline before exploration
if RUN_BASELINE:
    campaign_rounds, baseline_results = await run_baseline_eval(
        baseline, eval_data, campaign_config, svc,
    )

2026-03-13 15:40:55 INFO     [httpx] HTTP Request: GET http://127.0.0.1:8000/status "HTTP/1.1 200 OK"

BACKEND STATUS
==================================================
  Session Active                 True
  Active Sessions                1
  Terms Loaded                   94
  Match Database Identifiers     110
  Match Database Aliases         694
  Experiments Count              4
  Mappings Count                 1126
  Pipeline Version               v1.1
  Llm Provider                   groq
  Llm Model                      moonshotai/kimi-k2-instruct-0905
  ------------------------------------------------
  Experiments
    0_production_realtime        0 mappings
    1_production_historical      887 mappings
    2_bom_materials              159 mappings
    3_bom_processing             80 mappings
==================================================

Evaluation data: 984 queries

In [8]:
#@title Candidate coverage (post-eval diagnostic)
cov_df = run_coverage_diagnostic(
    baseline_results,
    svc["store"], svc["backend_id"], svc["experiment_id"],
)

Loaded 40 eval queries
Eval runs: 72 completed runs, 20 in-progress
  run_id                name           model                      temp  accuracy  queries
  scan_15a5c1e9         scan                                      0.0   50.0%     6
  scan_86f17bab         scan                                      0.0   66.7%     6
  scan_fcb7bf9b         scan                                      0.0   50.0%     6
  scan_01c3382c         scan                                      0.0   66.7%     6
  scan_7d0c905a         scan                                      0.0   33.3%     6
  scan_e9f03615         scan                                      0.0   66.7%     6
  scan_3aff5881         scan                                      0.0   33.3%     6
  scan_39b9fc27         scan                                      0.0   50.0%     6
  scan_dff96710         scan                                      0.0   33.3%     6
  scan_3dbc066d         scan                                      0.0   33.3%     6
  scan_473d0e91         scan                                      0.0   50.0%     6
  scan_fa108623         scan                                      0.0   50.0%     6
  scan_d2e3bedc         scan                                      0.0   50.0%     6
  scan_c91e1a6c         scan                                      0.0   50.0%     6
  candidate_0_9e840bcc  candidate_0    meta-llama/llama-4-mav...  0.0   26.7%     15
  candidate_1_56c8ab63  candidate_1    meta-llama/llama-4-mav...  0.0   26.7%     15
  candidate_2_bc44210c  candidate_2    meta-llama/llama-4-mav...  0.0   20.0%     15
  grid_bc173e5e         grid_point_0                              0.0   50.0%     6
  scan_3003e64c         scan                                      0.0   0.0%      6
  scan_21819e5d         scan                                      0.0   0.0%      6
  scan_e8bf58c1         scan                                      0.0   0.0%      6
  scan_d9ad416a         scan                                      0.0   0.0%      6
  scan_3bb3eb8b         scan                                      0.0   0.0%      6
  scan_b6938e04         scan                                      0.0   0.0%      6
  scan_89904321         scan                                      0.0   0.0%      6
  scan_f5043a6e         scan                                      0.0   0.0%      6
  scan_2a7923e7         scan                                      0.0   0.0%      6
  scan_ceffb77a         scan                                      0.0   0.0%      6
  scan_119dd94e         scan                                      0.0   0.0%      6
  scan_6f08fc2b         scan                                      0.0   0.0%      6
  scan_6135a7e8         scan                                      0.0   0.0%      6
  scan_3b79712d         scan                                      0.0   0.0%      6
  scan_5ef02893         scan                                      0.0   0.0%      6
  scan_5f839a2b         scan                                      0.0   0.0%      6
  scan_f35b458f         scan                                      0.0   0.0%      984
  scan_9f9695bf         scan                                      0.0   0.0%      984
  scan_7ffda8d4         scan                                      0.0   0.0%      984
  scan_5e6a3766         scan                                      0.0   0.0%      984
  scan_24289a7d         scan                                      0.0   0.0%      984
  scan_d7c7f1bb         scan                                      0.0   0.0%      984
  scan_79f73432         scan                                      0.0   0.0%      984
  scan_8b14c1ec         scan                                      0.0   0.0%      984
  scan_1224c150         scan                                      0.0   0.0%      984
  scan_f7cf8e67         scan                                      0.0   0.0%      984
  scan_2f3b7061         scan                                      0.0   0.0%      984
  scan_297ac6e7         scan                                      0.0   10.0%     10
  scan_c5d479cd         scan                                      0.0   0.0%      10
  scan_de9fe30d         scan                                      0.0   30.0%     10
  scan_20143da7         scan                                      0.0   20.0%     10
  scan_2a0b358e         scan                                      0.0   20.0%     10
  scan_6d51e472         scan                                      0.0   0.0%      10
  scan_4e9374b2         scan                                      0.0   0.0%      10
  scan_e672f931         scan                                      0.0   10.0%     10
  scan_1689c8b4         scan                                      0.0   0.0%      10
  scan_774596a7         scan                                      0.0   20.0%     10
  scan_2b166fb8         scan                                      0.0   10.0%     10
  scan_79746fe2         scan                                      0.0   10.0%     10
  scan_0305673a         scan                                      0.0   0.0%      10
  scan_5ed2679e         scan                                      0.0   20.0%     10
  scan_e52fa56d         scan                                      0.0   10.0%     10
  scan_e455eedc         scan                                      0.0   10.0%     10
  scan_caefbaa1         scan                                      0.0   0.0%      10
  scan_9de298dc         scan                                      0.0   10.0%     10
  candidate_0_3ed7db6b  candidate_0    openai/gpt-oss-120b        0.0   13.3%     15
  candidate_0_86d9b034  candidate_0    openai/gpt-oss-120b        0.0   6.7%      15
  candidate_1_cb97cc60  candidate_1    openai/gpt-oss-120b        0.0   6.7%      15
  candidate_2_8afc649a  candidate_2    openai/gpt-oss-120b        0.0   13.3%     15
  candidate_3_ad1ffb8b  candidate_3    openai/gpt-oss-120b        0.0   20.0%     15
  candidate_4_c2297062  candidate_4    openai/gpt-oss-120b        0.0   6.7%      15
  candidate_0_ade9d1fe  candidate_0    openai/gpt-oss-120b        0.0   0.0%      15
  candidate_1_1e68c739  candidate_1    openai/gpt-oss-120b        0.0   13.3%     15
  candidate_2_99a89e95  candidate_2    openai/gpt-oss-120b        0.0   6.7%      15
  candidate_0_004b481f  (in-progress)                             --    --        7/?
  candidate_0_8277ab30  (in-progress)                             --    --        12/?
  candidate_0_901de31e  (in-progress)                             --    --        2/?
  candidate_0_a0d35258  (in-progress)                             --    --        13/?
  candidate_1_1315a85b  (in-progress)                             --    --        8/?
  candidate_1_709d1988  (in-progress)                             --    --        2/?
  candidate_3_9a7a8a0f  (in-progress)                             --    --        12/?
  candidate_3_a9459dd0  (in-progress)                             --    --        9/?
  grid_ad849bc4         (in-progress)                             --    --        5/?
  scan_0fd4d949         (in-progress)                             --    --        3/?
  scan_22a0525f         (in-progress)                             --    --        18/?
  scan_385b9e5b         (in-progress)                             --    --        16/?
  scan_6a5db238         (in-progress)                             --    --        5/?
  scan_763109b5         (in-progress)                             --    --        14/?
  scan_7645047e         (in-progress)                             --    --        5/?
  scan_9a9ca472         (in-progress)                             --    --        2/?
  scan_a7f0fb3f         (in-progress)                             --    --        32/?
  scan_b4665cda         (in-progress)                             --    --        8/?
  scan_c68507a6         (in-progress)                             --    --        6/?
  scan_e0b3c630         (in-progress)                             --    --        5/?
CANDIDATE COVERAGE
==================================================
  Ground truth in candidates: 37/40 (92.5%)
  Missing from candidates:    3/40

Rank distribution (ground truth position in candidate list):
  Rank 1 (already top):  7
  Rank 2-5:              12
  Rank 6-10:             14
  Rank 11-20:            4
  Rank >20:              0
  Mean rank:             5.6
  Median rank:           5

DECISION: Coverage 92% > 50% threshold -> Reranker optimization is VIABLE.
  The ground truth exists in the candidate set; a better reranker prompt can promote it.
--- Sample 1: PMC ISO 14530-UP (GF10+MD65),M,FR Ralupol UP 804 7035.00 M/Q ---
  Core concept: molding
  Profile keys: ['entity_name', 'core_concept', 'distinguishing_features', 'key_properties', 'technical_specifications', 'alternative_names', 'classification_sourcees', 'constituent_materials', 'manufacturing_processes', 'applications', 'notes', '_metadata']
  Ground truth: Glass fibre reinforced plastic, polyester resin, hand lay-up {GLO}| market for glass fibre reinforced plastic, polyester resin, hand lay-up | Cut-off, S
  Top 5 candidates: ['Glass fibre reinforced plastic, polyester resin, hand lay-up {GLO}| market for glass fibre reinforced plastic, polyester resin, hand lay-up | Cut-off, S', 'Glass fibre reinforced plastic, polyamide, injection moulded {GLO}| market for glass fibre reinforced plastic, polyamide, injection moulded | Cut-off, S', 'Glass fibre reinforced plastic | 50% PA66 50% GF /RER', 'Glass fibre reinforced plastic | 90% PC 10% GF /GLO', 'Glass fibre reinforced plastic | 65% PA66 35% GF /RER']

--- Sample 2: Round couper wire 2,5mm²/pre-welded braid ---
  Core concept: Braid
  Profile keys: ['entity_name', 'core_concept', 'distinguishing_features', 'key_properties', 'technical_specifications', 'alternative_names', 'classification_sourcees', 'constituent_materials', 'manufacturing_processes', 'applications', 'notes', '_metadata']
  Ground truth: Copper, cathode {GLO}| market for copper, cathode | Cut-off, S
  Top 5 candidates: ['Wire drawing, copper {RER}| wire drawing, copper | Cut-off, S', 'Wire drawing, copper {RoW}| wire drawing, copper | Cut-off, S', 'Copper, cathode {GLO}| market for copper, cathode | only secondary material, S', 'Wire drawing, steel {RER}| wire drawing, steel | Cut-off, S', 'Cable, unspecified {GLO}| cable production, PVC insulation, no recycled copper | Cut-off, S']

--- Sample 3: PA66-GF35 Bergamid A700 G35 H RAL3000/molding ---
  Core concept: molding
  Profile keys: ['entity_name', 'core_concept', 'distinguishing_features', 'key_properties', 'technical_specifications', 'alternative_names', 'classification_sourcees', 'constituent_materials', 'manufacturing_processes', 'applications', 'notes', '_metadata']
  Ground truth: Glass fibre reinforced plastic | 75% PA66 25% GF /RER
  Top 5 candidates: ['Glass fibre reinforced plastic | 65% PA66 35% GF /RER', 'Glass fibre reinforced plastic | 50% PA66 50% GF /RER', 'Glass fibre reinforced plastic | 95% PA66 5% GF /RER', 'Glass fibre reinforced plastic | 75% PA66 25% GF /RER', 'Glass fibre reinforced plastic, polyamide, injection moulded {GLO}| market for glass fibre reinforced plastic, polyamide, injection moulded | Cut-off, S']

In [ ]:
#@title Campaign explorer (overview / detail / diff)
# Overview: see all campaigns
list_campaigns(store=svc["store"], backend_id=svc["backend_id"])

# Detail: uncomment and paste a campaign_id
# list_campaigns(store=svc["store"], backend_id=svc["backend_id"],
#                campaign_id="cycle_68e2c53845c3")

# Diff: compare current config vs stored campaign
# diff_campaign_config(svc["store"], svc["backend_id"],
#                      "cycle_68e2c53845c3", campaign_config,
#                      pipeline_params=pipeline_params)

## 3. Explore

Two exploration paths: **Smart Search** (scan advisor + sensitivity scan) or **Grid Search** (brute-force sweep). Use one or both.

### 3a. Smart Search

In [9]:
#@title Browse variant library
display_variant_library()
# Filter examples:
# display_variant_library(source="PromptWizard")
# display_variant_library(axes=["thinking_style", "persona"])

Variant Library
  Sources: PromptPotter (16), PromptWizard (40)

  persona (6 variants — PromptPotter: 4, PromptWizard: 2)
    [ 0] [PromptPotter] (empty baseline)
    [ 1] [PromptPotter] You are a domain expert with deep knowledge of this field.
    [ 2] [PromptPotter] You are a precise, analytical system that evaluates candidates methodi...
    [ 3] [PromptPotter] You are a careful assistant that considers all options before deciding...
    [ 4] [PromptWizard 2024] You are a specialist who evaluates candidates based on domain-specific...
    [ 5] [PromptWizard 2024] You are a meticulous researcher who cross-references information befor...

  task_intent (4 variants — PromptPotter: 4)
    [ 0] [PromptPotter] (empty baseline)
    [ 1] [PromptPotter] Your task is to identify the single best match from the candidates.
    [ 2] [PromptPotter] Rank candidates by how well they match the concept described.
    [ 3] [PromptPotter] Evaluate each candidate for semantic equivalence to the query concept,...

  thinking_style (42 variants — PromptPotter: 4, PromptWizard: 38)
    [ 0] [PromptPotter] (empty baseline)
    [ 1] [PromptPotter] Think step by step.
    [ 2] [PromptPotter] Focus on semantic meaning, not surface-level word overlap.
    [ 3] [PromptPotter] First understand the core concept, then evaluate each candidate agains...
    [ 4] [PromptWizard 2024] How could I devise an experiment to help solve that problem?
    [ 5] [PromptWizard 2024] Make a list of ideas for solving this problem, and apply them one by o...
    [ 6] [PromptWizard 2024] How could I measure progress on this problem?
    [ 7] [PromptWizard 2024] How can I simplify the problem so that it is easier to solve?
    [ 8] [PromptWizard 2024] What are the key assumptions underlying this problem?
    [ 9] [PromptWizard 2024] What are the potential risks and drawbacks of each solution?
    [10] [PromptWizard 2024] What are the alternative perspectives or viewpoints on this problem?
    [11] [PromptWizard 2024] What are the long-term implications of this problem and its solutions?
    [12] [PromptWizard 2024] How can I break down this problem into smaller, more manageable parts?
    [13] [PromptWizard 2024] Critical Thinking: This style involves analyzing the problem from diff...
    [14] [PromptWizard 2024] Try creative thinking, generate innovative and out-of-the-box ideas to...
    [15] [PromptWizard 2024] Seek input and collaboration from others to solve the problem. Emphasi...
    [16] [PromptWizard 2024] Use systems thinking: Consider the problem as part of a larger system ...
    [17] [PromptWizard 2024] Use Risk Analysis: Evaluate potential risks, uncertainties, and tradeo...
    [18] [PromptWizard 2024] Use Reflective Thinking: Step back from the problem, take the time for...
    [19] [PromptWizard 2024] What is the core issue or problem that needs to be addressed?
    [20] [PromptWizard 2024] What are the underlying causes or factors contributing to the problem?
    [21] [PromptWizard 2024] Are there any potential solutions or strategies that have been tried b...
    [22] [PromptWizard 2024] What are the potential obstacles or challenges that might arise in sol...
    [23] [PromptWizard 2024] Are there any relevant data or information that can provide insights i...
    [24] [PromptWizard 2024] Are there any stakeholders or individuals who are directly affected by...
    [25] [PromptWizard 2024] What resources (financial, human, technological, etc.) are needed to t...
    [26] [PromptWizard 2024] How can progress or success in solving the problem be measured or eval...
    [27] [PromptWizard 2024] What indicators or metrics can be used?
    [28] [PromptWizard 2024] Is the problem a technical or practical one that requires a specific e...
    [29] [PromptWizard 2024] Does the problem involve a physical constraint, such as limited resour...
    [30] [PromptWizard 2024] Is the problem related to human behavior, such as a social, cultural, ...
    [31] [PromptWizard 2024] Does the problem involve decision-making or planning, where choices ne...
    [32] [PromptWizard 2024] Is the problem an analytical one that requires data analysis, modeling...
    [33] [PromptWizard 2024] Is the problem a design challenge that requires creative solutions and...
    [34] [PromptWizard 2024] Does the problem require addressing systemic or structural issues rath...
    [35] [PromptWizard 2024] Is the problem time-sensitive or urgent, requiring immediate attention...
    [36] [PromptWizard 2024] What kinds of solution typically are produced for this kind of problem...
    [37] [PromptWizard 2024] Given the problem specification and the current best solution, have a ...
    [38] [PromptWizard 2024] Let's imagine the current best solution is totally wrong, what other w...
    [39] [PromptWizard 2024] What is the best way to modify this current best solution, given what ...
    [40] [PromptWizard 2024] Ignoring the current best solution, create an entirely new solution to...
    [41] [PromptWizard 2024] Let's make a step by step plan and implement it with good notion and e...

  answer_format (3 variants — PromptPotter: 3)
    [ 0] [PromptPotter] (empty baseline)
    [ 1] [PromptPotter] Rank all candidates from most to least relevant.
    [ 2] [PromptPotter] Return only the single best match.

  problem_description (1 variants — PromptPotter: 1)
    [ 0] [PromptPotter] (empty baseline)

{'prompt_fields': {'persona': [{'text': '', 'source': 'PromptPotter'},
   {'text': 'You are a domain expert with deep knowledge of this field.',
    'source': 'PromptPotter'},
   {'text': 'You are a precise, analytical system that evaluates candidates methodically.',
    'source': 'PromptPotter'},
   {'text': 'You are a careful assistant that considers all options before deciding.',
    'source': 'PromptPotter'},
   {'text': 'You are a specialist who evaluates candidates based on domain-specific criteria and professional standards.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'You are a meticulous researcher who cross-references information before making judgments.',
    'source': 'PromptWizard',
    'year': 2024}],
  'task_intent': [{'text': '', 'source': 'PromptPotter'},
   {'text': 'Your task is to identify the single best match from the candidates.',
    'source': 'PromptPotter'},
   {'text': 'Rank candidates by how well they match the concept described.',
    'source': 'PromptPotter'},
   {'text': 'Evaluate each candidate for semantic equivalence to the query concept, considering domain context.',
    'source': 'PromptPotter'}],
  'thinking_style': [{'text': '', 'source': 'PromptPotter'},
   {'text': 'Think step by step.', 'source': 'PromptPotter'},
   {'text': 'Focus on semantic meaning, not surface-level word overlap.',
    'source': 'PromptPotter'},
   {'text': 'First understand the core concept, then evaluate each candidate against it.',
    'source': 'PromptPotter'},
   {'text': 'How could I devise an experiment to help solve that problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Make a list of ideas for solving this problem, and apply them one by one to the problem to see if any progress can be made.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'How could I measure progress on this problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'How can I simplify the problem so that it is easier to solve?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What are the key assumptions underlying this problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What are the potential risks and drawbacks of each solution?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What are the alternative perspectives or viewpoints on this problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What are the long-term implications of this problem and its solutions?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'How can I break down this problem into smaller, more manageable parts?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Critical Thinking: This style involves analyzing the problem from different perspectives, questioning assumptions, and evaluating the evidence or information available. It focuses on logical reasoning, evidence-based decision-making, and identifying potential biases or flaws in thinking.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Try creative thinking, generate innovative and out-of-the-box ideas to solve the problem. Explore unconventional solutions, thinking beyond traditional boundaries, and encouraging imagination and originality.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Seek input and collaboration from others to solve the problem. Emphasize teamwork, open communication, and leveraging the diverse perspectives and expertise of a group to come up with effective solutions.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Use systems thinking: Consider the problem as part of a larger system and understanding the interconnectedness of various elements. Focuses on identifying the underlying causes, feedback loops, and interdependencies that influence the problem, and developing holistic solutions that address the system as a whole.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Use Risk Analysis: Evaluate potential risks, uncertainties, and tradeoffs associated with different solutions or approaches to a problem. Emphasize assessing the potential consequences and likelihood of success or failure, and making informed decisions based on a balanced analysis of risks and benefits.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Use Reflective Thinking: Step back from the problem, take the time for introspection and self-reflection. Examine personal biases, assumptions, and mental models that may influence problem-solving, and being open to learning from past experiences to improve future approaches.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What is the core issue or problem that needs to be addressed?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What are the underlying causes or factors contributing to the problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Are there any potential solutions or strategies that have been tried before? If yes, what were the outcomes and lessons learned?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What are the potential obstacles or challenges that might arise in solving this problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Are there any relevant data or information that can provide insights into the problem? If yes, what data sources are available, and how can they be analyzed?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Are there any stakeholders or individuals who are directly affected by the problem? What are their perspectives and needs?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What resources (financial, human, technological, etc.) are needed to tackle the problem effectively?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'How can progress or success in solving the problem be measured or evaluated?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What indicators or metrics can be used?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Is the problem a technical or practical one that requires a specific expertise or skill set? Or is it more of a conceptual or theoretical problem?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Does the problem involve a physical constraint, such as limited resources, infrastructure, or space?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Is the problem related to human behavior, such as a social, cultural, or psychological issue?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Does the problem involve decision-making or planning, where choices need to be made under uncertainty or with competing objectives?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Is the problem an analytical one that requires data analysis, modeling, or optimization techniques?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Is the problem a design challenge that requires creative solutions and innovation?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Does the problem require addressing systemic or structural issues rather than just individual instances?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Is the problem time-sensitive or urgent, requiring immediate attention and action?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What kinds of solution typically are produced for this kind of problem specification?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Given the problem specification and the current best solution, have a guess about other possible solutions.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': "Let's imagine the current best solution is totally wrong, what other ways are there to think about the problem specification?",
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'What is the best way to modify this current best solution, given what you know about these kinds of problem specification?',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': 'Ignoring the current best solution, create an entirely new solution to the problem.',
    'source': 'PromptWizard',
    'year': 2024},
   {'text': "Let's make a step by step plan and implement it with good notion and explanation.",
    'source': 'PromptWizard',
    'year': 2024}],
  'answer_format': [{'text': '', 'source': 'PromptPotter'},
   {'text': 'Rank all candidates from most to least relevant.',
    'source': 'PromptPotter'},
   {'text': 'Return only the single best match.', 'source': 'PromptPotter'}],
  'problem_description': [{'text': '', 'source': 'PromptPotter'}]}}

In [10]:
# preview_advisor_prompt()
preview_advisor_prompt(campaign_config, svc, task_description="TASK_DESCRIPTION", raw=True)

2026-03-13 15:40:55 INFO     [api.services.search.smart_search] filter_variant_library: dropped all prompt_fields (llm_ranking not active)

You are an expert prompt optimization advisor. Recommend which axes (parameters and prompt fields) to prioritize in a sensitivity scan.

## Constraints (apply strictly)
- Do NOT recommend *_model axes — place them in axes_to_skip.
- Response must fit within 1500 tokens. Be terse.

## Pipeline: TermNorm AI terminology normalization pipeline
Steps execute sequentially — each step's output feeds the next:
[
  {
    "name": "cache_lookup",
    "node_role": "cache",
    "short_circuit": true
  },
  {
    "name": "fuzzy_matching",
    "node_role": "candidate_source",
    "short_circuit": true
  },
  {
    "name": "web_search",
    "node_role": "enricher"
  },
  {
    "name": "entity_profiling",
    "node_role": "enricher"
  },
  {
    "name": "token_matching",
    "node_role": "candidate_source"
  }
]

## Task Context
TASK_DESCRIPTION
## Tunable Parameters (per step)
[
  {
    "name": "fuzzy_matching",
    "param_keys": [
      "fuzzy_scorer",
      "fuzzy_threshold"
    ]
  },
  {
    "name": "web_search",
    "param_keys": [
      "content_char_limit",
      "max_sites",
      "num_results",
      "query_prefix",
      "query_suffix"
    ],
    "current_values": {
      "max_sites": 7,
      "num_results": 20,
      "content_char_limit": 800,
      "query_prefix": "",
      "query_suffix": ""
    }
  },
  {
    "name": "entity_profiling",
    "param_keys": [
      "profiling_max_tokens",
      "profiling_model",
      "profiling_prompt",
      "profiling_schema",
      "profiling_temperature",
      "raw_content_limit"
    ],
    "current_values": {
      "raw_content_limit": 5000
    }
  },
  {
    "name": "token_matching",
    "param_keys": [
      "max_token_candidates"
    ],
    "current_values": {
      "max_token_candidates": 20
    }
  }
]

## Prompt Field Axes
Prompt template fields that can be varied (variant library has pre-defined values):
[]

## LLM Node Details
Output schema fields and prompt metadata for LLM-driven steps:
[
  {
    "name": "entity_profiling",
    "output_schema": {
      "entity_name": "string",
      "core_concept": "string \u2014 The single word that defines what this expression represents",
      "distinguishing_features": "array",
      "key_properties": "array",
      "technical_specifications": "array \u2014 Explicit technical specs, dimensions, codes, ratings, tolerances",
      "alternative_names": "array",
      "classification_aliases": "array \u2014 Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic",
      "constituent_materials": "array \u2014 All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge",
      "manufacturing_processes": "array \u2014 Both stated and inferred manufacturing processes based on product type, materials, and industry standards",
      "applications": "array \u2014 Direct and derived applications based on product characteristics",
      "notes": "array"
    },
    "prompt_meta": {
      "family": "entity_profiling",
      "template_variables": [
        "query",
        "format_string",
        "combined_text"
      ],
      "description": "Extract comprehensive entity profile from web research data with US/GB spelling variants"
    }
  }
]
## Analysis Approach
Work through these steps before producing your recommendation:
1. Trace data flow: UPSTREAM parameters have multiplier effects — poor upstream data cannot be compensated by downstream tuning.
2. Flag high-impact targets: empty or default string params (prefixes, suffixes, query modifiers) that shape what data enters the pipeline.
3. For *_schema axes: identify output fields that are redundant or missing for downstream consumption. Suggest mutations relative to the current output_schema shown in LLM Node Details.
4. Skip axes unlikely to affect accuracy. Prioritize axes with the highest expected impact on end-to-end accuracy.
5. Estimate a diagnostic budget (queries per axis).

## Output Format
For pipeline_param axes, suggest concrete values that meaningfully differ from current_values. For prompt_field axes, just flag them — the variant library already has values.

Return a JSON object with this structure:
{
  "priority_axes": [
    {
      "axis": "<param_name>",
      "source": "pipeline_param",
      "step": "<step_name>",
      "rationale": "...",
      "suggested_values": ["<val>", "..."],
      "importance": "<high|medium|low>"
    },
    {
      "axis": "<field_name>",
      "source": "prompt_field",
      "rationale": "...",
      "importance": "<high|medium|low>"
    }
  ],
  "suggested_n_diagnostic": 6,
  "axes_to_skip": [
    {"axis": "<name>", "reason": "..."}
  ],
  "budget_breakdown": {
    "<axis_name>": <n_queries>,
    "total": <sum>
  },
  "reasoning": "Overall strategy explanation..."
}

Rules:
- rationale: max 15 words
- reasoning: max 2 sentences
- axes_to_skip reason: max 10 words
- suggested_values: 2-4 values, numbers or short strings only
- importance: "high", "medium", or "low"
- source: "pipeline_param" or "prompt_field"
- For pipeline_param axes: include "step" and "suggested_values"
- For prompt_field axes: omit "step" and "suggested_values"
- *_schema mutations: each suggested_value is a JSON array of mutation arrays. Ops: ["-","path"] remove | ["+","path","type",required,"desc"] add | ["~","old","new","type",required,"desc"] replace. Types: string|array|integer|number|boolean|object. required: true|false. Baseline included automatically — do NOT include it. Keep each variant to 1-2 mutations so individual effects are measurable.

Return ONLY the JSON object, no markdown fences or extra text.

In [11]:
#@title Scan advisor
advisory, scan_variants, schema_labels = await run_scan_advisor(
    campaign_config, svc,
    task_description=TASK_DESCRIPTION if "TASK_DESCRIPTION" in dir() else "",
)

2026-03-13 15:40:55 INFO     [api.services.search.smart_search] filter_variant_library: dropped all prompt_fields (llm_ranking not active)

======================================================================
SCAN ADVISOR -- pipeline-aware sensitivity setup
======================================================================
  Pipeline: termnorm (v1.1)
  Steps: ['cache_lookup', 'fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching', 'llm_ranking']
  Excluded: ['llm_ranking']
  Task context: # Domain Context: Life Cycle Assessment (LCA) Terminology

This document capture...
  Calling openai/gpt-oss-120b ...

2026-03-13 15:41:00 INFO     [httpx] HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-03-13 15:41:00 WARNING  [api.services.search.scan_advisor] Scan advisor validation: pipeline_param axis 'entity_profiling_schema' not found in PipelineSchema param_keys: ['content_char_limit', 'fuzzy_scorer', 'fuzzy_threshold', 'max_sites', 'max_token_candidates', 'num_results', 'profiling_max_tokens', 'profiling_model', 'profiling_prompt', 'profiling_schema', 'profiling_temperature', 'query_prefix', 'query_suffix', 'ranking_max_tokens', 'ranking_model', 'ranking_prompt', 'ranking_sample_size', 'ranking_schema', 'ranking_temperature', 'raw_content_limit', 'relevance_weight_core']

----------------------------------------------------------------------
PRIORITY AXES (ranked by importance)
----------------------------------------------------------------------
  1. [HIGH] fuzzy_threshold (pipeline_param) -- step: fuzzy_matching
     Controls candidate inclusion sensitivity
     Values: ['0.6', '0.75', '0.9']
  2. [MEDIUM] fuzzy_scorer (pipeline_param) -- step: fuzzy_matching
     Scorer choice impacts similarity scoring
     Values: ['ratio', 'partial_ratio', 'token_set_ratio']
  3. [HIGH] query_prefix (pipeline_param) -- step: web_search
     Adds context to search queries
     Values: ['"material"', '"LCA"']
  4. [MEDIUM] query_suffix (pipeline_param) -- step: web_search
     Filters results to technical sources
     Values: ['"datasheet"', '"specification"']
  5. [MEDIUM] content_char_limit (pipeline_param) -- step: web_search
     Limits retrieved text for profiling
     Values: ['500', '800', '1200']
  6. [HIGH] profiling_prompt (pipeline_param) -- step: entity_profiling
     Guides extraction detail level
     Values: ['concise', 'detailed']
  7. [MEDIUM] entity_profiling_schema (pipeline_param) -- step: entity_profiling
     Remove redundant fields or add useful ones
     Values: [[['-', 'notes']], [['+', 'source_url', 'string', True, 'URL of source document']]]
  8. [MEDIUM] max_token_candidates (pipeline_param) -- step: token_matching
     Limits candidate pool size
     Values: ['10', '20', '30']

----------------------------------------------------------------------
AXES TO SKIP
----------------------------------------------------------------------
  - profiling_model: model selection not in scope

----------------------------------------------------------------------
BUDGET BREAKDOWN
----------------------------------------------------------------------
  fuzzy_threshold: 3
  query_prefix: 3
  profiling_prompt: 3
  fuzzy_scorer: 1
  query_suffix: 1
  content_char_limit: 1
  entity_profiling_schema: 1
  max_token_candidates: 1
  total: 14

  Suggested n_diagnostic: 6

----------------------------------------------------------------------
REASONING
----------------------------------------------------------------------
  Focus upstream similarity and query shaping, then improve extraction prompt and schema. Skip model tuning as out of scope.

----------------------------------------------------------------------
VALIDATION WARNINGS
----------------------------------------------------------------------
  [!] pipeline_param axis 'entity_profiling_schema' not found in PipelineSchema param_keys: ['content_char_limit', 'fuzzy_scorer', 'fuzzy_threshold', 'max_sites', 'max_token_candidates', 'num_results', 'profiling_max_tokens', 'profiling_model', 'profiling_prompt', 'profiling_schema', 'profiling_temperature', 'query_prefix', 'query_suffix', 'ranking_max_tokens', 'ranking_model', 'ranking_prompt', 'ranking_sample_size', 'ranking_schema', 'ranking_temperature', 'raw_content_limit', 'relevance_weight_core']
======================================================================

--- PROPOSED SCAN VARIANTS (copy-paste into next cell) ---
scan_variants = {
    'fuzzy_threshold': ['0.6', '0.75', '0.9'],
    'fuzzy_scorer': ['ratio', 'partial_ratio', 'token_set_ratio'],
    'query_prefix': ['"material"', '"LCA"'],
    'query_suffix': ['"datasheet"', '"specification"'],
    'content_char_limit': ['500', '800', '1200'],
    'profiling_prompt': ['concise', 'detailed'],
    'entity_profiling_schema': [[['-', 'notes']], [['+', 'source_url', 'string', True, 'URL of source document']]],
    'max_token_candidates': ['10', '20', '30'],
}

In [12]:
#@title Scan variant config (edit suggested values or add your own)
# Schema axes: mutation tuples ("-", path), ("+", path, type, req, desc),
# ("~", old, new, type, req, desc). Non-schema axes: plain value lists.

scan_sample_size = 10  # queries per scan variant (0 = use all)

scan_variants = {
    'max_token_candidates': [10, 30, 50],
    'query_prefix': ['what material is', 'identify LCA database name for', 'translate trade name'],
    'profiling_schema': [
        [['+', 'geography_scope', 'array', False, 'Relevant ecoinvent/SimaPro geography codes inferred from context, e.g. GLO, RER, CH, RNA'], ['+', 'database_format_hint', 'string', False, "Best-guess ecoinvent-style name fragment for this entity, e.g. 'market for polyethylene, high density'"]],
        # [['-', 'manufacturing_processes'], ['-', 'applications'], ['+', 'lca_synonyms', 'array', False, 'Terms likely to appear verbatim in LCA database entry names for this entity'], ['+', 'no_match_signal', 'string', False, 'Brief reasoning on whether a database match is likely to exist or not']],
        # [['~', 'classification_aliases', 'lca_classification_aliases', 'array', False, 'Expert-level aliases specifically aligned with LCA database naming conventions, including ecoinvent activity names and SimaPro process names'], ['+', 'geography_scope', 'array', False, 'Relevant ecoinvent/SimaPro geography codes inferred from context, e.g. GLO, RER, CH, RNA']],
        [['+', 'lca_database_names', 'array', True, "Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'"]], 
        [['-', 'manufacturing_processes'], ['-', 'applications'], ['+', 'lca_database_names', 'array', True, 'Likely ecoinvent or GaBi database entry names for this entity using standard LCA naming conventions']],
        [['~', 'notes', 'material_category', 'string', True, "The broad LCA material category this entity belongs to, e.g. 'polyethylene', 'brass', 'steel'"]]
    ],
    'profiling_temperature': [0.0, 0.3, 0.7],
    # 'profiling_max_tokens': [512, 1024, 2048], # -> Going to cause lots of Errors.
    'raw_content_limit': [1000, 2500, 8000],
}
scan_variants, schema_labels = resolve_scan_variants(scan_variants, svc=svc)

  max_token_candidates: [10, 30, 50]
  query_prefix: ['what material is', 'identify LCA database name for', 'translate trade name']
  profiling_schema: (baseline + 4 mutations)
    [0] (baseline)
    [1] ('+', 'geography_scope', 'array', False, 'Relevant ecoinvent/SimaPro geography codes inferred from context, e.g. GLO, RER, CH, RNA'), ('+', 'database_format_hint', 'string', False, 'Best-guess ecoinvent-style name fragment for this entity, e.g. 'market for polyethylene, high density'')
    [2] ('+', 'lca_database_names', 'array', True, 'Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'')
    [3] ('-', 'manufacturing_processes'), ('-', 'applications'), ('+', 'lca_database_names', 'array', True, 'Likely ecoinvent or GaBi database entry names for this entity using standard LCA naming conventions')
    [4] ('~', 'notes', 'material_category', 'string', True, 'The broad LCA material category this entity belongs to, e.g. 'polyethylene', 'brass', 'steel'')
  profiling_temperature: [0.0, 0.3, 0.7]
  raw_content_limit: [1000, 2500, 8000]

In [13]:
#@title Prepare scan baseline
baseline_sp = await prepare_scan_baseline(
    baseline, campaign_config,
    pipeline_params=campaign_config.get("pipeline_params"),
    store=svc["store"], backend_id=svc["backend_id"],
    scan_variants=scan_variants,
)

2026-03-13 15:41:00 INFO     [api.services.search.context] restructure_context_cached: hit (alias group)

  Restructured baseline fields (cached):
    persona: You are a candidate evaluation expert.
    task_intent: Summarize the entity profile, identify its category and key distinguishing featu...
    problem_description: Given an entity_profile_json and a list of candidate matches, produce a concise ...
    instruction: TASK 1: Summarize the profile in 1‑2 sentences, identify entity_category, and li...
    thinking_style: Think step by step.
    answer_format: JSON with keys "reasoning" (string) and "ranked_candidates" (array of objects co...
  Search baseline: a1e9133ac23c (render: 1154 chars)

2026-03-13 15:41:01 INFO     [api.services.search.coverage] build_prompt_result_index: 72 runs -> 15 unique prompts, 3027 total query results

  Historical data: 3027 results across 15 unique prompts
  Baseline alias group: 14889901 ↔ 239cefb8 ↔ 24aeb9e7 ↔ 2c14e76c ↔ 2d9d15f6 ↔ 41f88bae ↔ 44eb12a0 ↔ 4ff72b79 ↔ 61ad2b63 ↔ 82f3e7e2 ↔ 830faccd ↔ 9e4f0633 ↔ adb2589d ↔ aeb18154 ↔ bcdc7b72 ↔ c2a36fe9 ↔ c311136d ↔ cec84ce0 ↔ d018a6dc ↔ e169ed86 (20 prompts linked)
  Matching runs: 71, 3012 cached results

  Scan variant coverage (71 matching runs):
    max_token_candidates     10→4 ✓  30→8 ✓  50→4 ✓  (+7 other)
    query_prefix             what material is→5 ✓  identify LCA database name for→1 ✓  translate trade name→1 ✓  (+4 other)
    profiling_schema         {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "applications": {"description": "Direct and derived applications based on product characteristics", "items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "manufacturing_processes": {"description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards", "items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "manufacturing_processes", "applications", "notes"], "type": "object"}→5 ✓  {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "applications": {"description": "Direct and derived applications based on product characteristics", "items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "database_format_hint": {"description": "Best-guess ecoinvent-style name fragment for this entity, e.g. 'market for polyethylene, high density'", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "geography_scope": {"description": "Relevant ecoinvent/SimaPro geography codes inferred from context, e.g. GLO, RER, CH, RNA", "items": {"type": "string"}, "type": "array"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "manufacturing_processes": {"description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards", "items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "manufacturing_processes", "applications", "notes"], "type": "object"}→3 ✓  {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "applications": {"description": "Direct and derived applications based on product characteristics", "items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "lca_database_names": {"description": "Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'", "items": {"type": "string"}, "type": "array"}, "manufacturing_processes": {"description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards", "items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "manufacturing_processes", "applications", "notes", "lca_database_names"], "type": "object"}→4 ✓  {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "lca_database_names": {"description": "Likely ecoinvent or GaBi database entry names for this entity using standard LCA naming conventions", "items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "notes", "lca_database_names"], "type": "object"}→2 ✓  {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "applications": {"description": "Direct and derived applications based on product characteristics", "items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "manufacturing_processes": {"description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards", "items": {"type": "string"}, "type": "array"}, "material_category": {"description": "The broad LCA material category this entity belongs to, e.g. 'polyethylene', 'brass', 'steel'", "type": "string"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "manufacturing_processes", "applications", "material_category"], "type": "object"}→1 ✓  (+7 other)
    profiling_temperature    0.0→2 ✓  0.3→7 ✓  0.7→2 ✓  (+3 other)
    raw_content_limit        1000→1 ✓  2500→1 ✓  8000→1 ✓  (+2 other)

In [14]:
#@title Sensitivity scan
scan_df, axis_profiles = await sensitivity_scan(
    baseline_sp, scan_variants, eval_data, svc.get("backend_client"),
    sample_size=scan_sample_size,
    store=svc["store"], backend_id=svc["backend_id"],
    pipeline_schema=svc.get("pipeline_schema"),
)

Running sensitivity scan...

  Baseline field values:
    persona: You are a candidate evaluation expert.
    task_intent: Summarize the entity profile, identify its category and key distinguishing featu...
    problem_description: Given an entity_profile_json and a list of candidate matches, produce a concise ...
    instruction: TASK 1: Summarize the profile in 1‑2 sentences, identify entity_category, and li...
    thinking_style: Think step by step.
    answer_format: JSON with keys "reasoning" (string) and "ranked_candidates" (array of objects co...

  Axes: 5, variants: 17, queries/variant: 10, cached results: 11370
  Estimated calls: ~170

2026-03-13 15:41:01 INFO     [httpx] HTTP Request: POST http://127.0.0.1:8000/sessions "HTTP/1.1 200 OK"

  Evaluating baseline...
        MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95 4.0s
        HIT   [token] ⚡  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra 4.1s
        MISS 5/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 4.2s
        MISS --/20  [token] ⚡  Kingfa NPG25                                   -> Polyamide (Nylon) 6.6/EU-27 5.2s
        MISS 13/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 4.9s
        MISS 6/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 4.5s
        MISS 10/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 3.9s
        MISS 6/20  [token] ⚡  Copper Wire/cold forming                       -> Galvanized Copper | 99.6% Copper 0. 4.0s
        MISS 10/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 4.8s
        MISS 3/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 3.3s
  Baseline: 1/10 (10.0%) [cached]

======================================================================
  Axis 1/5: max_token_candidates (pipeline_param, 3 values)
======================================================================
        MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 50 5.9s
        MISS 2/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Wire drawing, copper {RER}| wire dr 5.5s
        MISS 5/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 4.2s
        MISS 7/20  [token] ⚡  Kingfa NPG25                                   -> Injection moulding {RER}| injection 5.4s
        MISS 9/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 4.5s
        MISS 10/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 3.1s
        MISS 10/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 3.8s
        MISS 5/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RER}| wire dr 3.4s
        MISS 6/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 5.0s
        MISS --/20  [token] ⚡  SJRG0013-PA/molding                            -> Glass fibre reinforced plastic | 95 3.5s
  [0] 10                                         0/10  0.0%  -9.0% v [cached]
        HIT   [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75 5.0s
        HIT   [token] ⚡  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra 3.7s
        MISS --/20  [token] ⚡  SJRG0010-ABS/molding                           -> Glass fibre reinforced plastic | 90 5.8s
        MISS 4/20  [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 90 4.9s
        MISS 12/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 3.9s
        MISS 10/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 3.9s
        MISS 9/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 4.5s
        MISS 10/20  [token] ⚡  Copper Wire/cold forming                       -> Magnet, Sm1Co5 3.5s
        MISS 4/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 4.7s
        HIT   [token] ⚡  SJRG0013-PA/molding                            -> Injection moulding {RER}| injection 5.7s
  [1] 30                                         3/10  30.0%  +18.0% ^ [cached]
        HIT   [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75 4.6s
        HIT   [token] ⚡  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra 3.7s
        MISS 7/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 4.7s
        MISS 20/20  [token] ⚡  Kingfa NPG25                                   -> Galvanized Copper | 99.6% Copper 0. 4.7s
        MISS 13/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 3.9s
        MISS 10/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 3.1s
        MISS 9/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 4.7s
        MISS 7/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RER}| wire dr 2.8s
        MISS --/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Wire drawing, steel {RER}| wire dra 4.6s
        MISS 9/20  [token] ⚡  SJRG0013-PA/molding                            -> Glass fibre reinforced plastic | 75 6.3s
  [2] 50                                         2/10  20.0%  +9.0% ^ [cached]

======================================================================
  Axis 2/5: query_prefix (pipeline_param, 3 values)
======================================================================
        MISS 3/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 65 4.2s
        HIT   [token] ⚡  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra 4.1s
        MISS 12/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 3.0s
        HIT   [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 75 5.0s
        MISS 12/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 4.5s
        MISS 10/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 3.5s
        MISS 10/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 3.1s
        MISS 9/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RER}| wire dr 4.2s
        MISS 3/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Wire drawing, steel {RER}| wire dra 2.9s
        MISS 9/20  [token] ⚡  SJRG0013-PA/molding                            -> Glass fibre reinforced plastic | 60 6.2s
  [0] what material is                           2/10  20.0%  +9.2% ^ [cached]
        MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95 6.0s
        MISS 3/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER 4.2s
        MISS 6/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 3.9s
        MISS 4/20  [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 90 3.9s
        MISS 9/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 75 4.1s
        MISS 10/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 3.8s
        MISS 10/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 4.5s
        MISS 7/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RER}| wire dr 4.8s
        MISS 7/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, zinc coated /RER 10.5s
        MISS 11/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 3.7s
  [1] identify LCA database name for             0/10  0.0%  -8.8% v [cached]
        MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95 4.3s
        MISS 3/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m 4.4s
        MISS --/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 3.6s
        MISS 20/20  [token] ⚡  Kingfa NPG25                                   -> Galvanized Copper | 99.6% Copper 0. 4.7s
        MISS 7/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 4.2s
        MISS 10/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 4.3s
        MISS 11/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 6.3s
        MISS 15/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RER}| wire dr 3.3s
        MISS --/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Wire drawing, steel {RER}| wire dra 9.2s
        MISS 6/20  [token] ⚡  SJRG0013-PA/molding                            -> Glass fibre reinforced plastic | 50 3.5s
  [2] translate trade name                       0/10  0.0%  -9.2% v [cached]

======================================================================
  Axis 3/5: profiling_schema (pipeline_param, 5 values)
======================================================================
        MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95 3.7s
        HIT   [token] ⚡  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra 3.4s
        MISS 8/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 5.5s
        MISS 8/20  [token] ⚡  Kingfa NPG25                                   -> Acrylonitrile-butadiene-styrene cop 3.9s
        MISS 11/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 50 4.8s
        MISS 3/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 3.9s
        MISS 13/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 4.8s
        MISS 10/20  [token] ⚡  Copper Wire/cold forming                       -> Galvanized Copper | 99.6% Copper 0. 3.7s
        MISS 8/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 4.1s
        MISS 6/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 2.8s
  [0] schema(11 fields)                          1/10  10.0%  +0.3% ^ [cached]
        MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95 4.1s
        MISS 2/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m 4.5s
        MISS 11/20  [token] ⚡  SJRG0010-ABS/molding                           -> Glass fibre reinforced plastic | 90 5.0s
        MISS 5/20  [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 90 4.0s
        MISS 12/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 4.4s
        MISS 9/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 3.8s
        MISS 10/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 3.3s
        MISS 5/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RER}| wire dr 3.5s
        MISS 10/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Wire drawing, steel {RER}| wire dra 5.0s
        MISS 7/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 3.0s
  [1] schema(13 fields)                          0/10  0.0%  -8.8% v [cached]
        MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95 4.5s
        HIT   [token] ⚡  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra 3.6s
        MISS 3/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 3.2s
        HIT   [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 75 3.2s
        MISS 7/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 50 4.4s
        MISS 11/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 3.7s
        MISS 10/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 3.2s
        MISS 17/20  [token] ⚡  Copper Wire/cold forming                       -> Galvanized Copper | 99.6% Copper 0. 3.7s
        MISS 11/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 4.4s
        MISS 2/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 3.8s
  [2] schema(12 fields)                          2/10  20.0%  +9.2% ^ [cached]
        MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95 3.9s
        HIT   [token] ⚡  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra 3.4s
        MISS 3/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 3.1s
        MISS 17/20  [token] ⚡  Kingfa NPG25                                   -> Acrylonitrile-butadiene-styrene cop 3.9s
        MISS 12/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 4.5s
        MISS 10/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 4.3s
        MISS 12/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 6.4s
        MISS 6/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RER}| wire dr 3.4s
        MISS 11/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 4.1s
        MISS --/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 3.1s
  [3] schema(10 fields)                          1/10  10.0%  +0.0% [cached]
        MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95 4.2s
        MISS 3/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m 4.1s
        MISS 3/20  [token] ⚡  SJRG0010-ABS/molding                           -> Extrusion, plastic pipes {RER}| ext 3.2s
        HIT   [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 75 3.6s
        MISS 6/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 4.1s
        MISS 2/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 3.8s
        MISS 12/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 4.2s
        MISS 3/20  [token] ⚡  Copper Wire/cold forming                       -> Metal working, average for steel pr 4.1s
        MISS 6/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Wire drawing, steel {RER}| wire dra 3.7s
        MISS 6/20  [token] ⚡  SJRG0013-PA/molding                            -> Glass fibre {GLO}| market for glass 4.0s
  [4] schema(11 fields)                          1/10  10.0%  +0.3% ^ [cached]

======================================================================
  Axis 4/5: profiling_temperature (pipeline_param, 3 values)
======================================================================
        MISS 3/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 50 4.8s
        MISS 2/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m 4.6s
        MISS 17/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 4.8s
        MISS 3/20  [token] ⚡  Kingfa NPG25                                   -> Injection moulding {RoW}| injection 4.0s
        MISS 7/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 4.5s
        MISS 5/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 3.4s
        MISS 11/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 5.8s
        MISS 5/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RER}| wire dr 3.9s
        MISS 11/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 10.2s
        MISS 9/20  [token] ⚡  SJRG0013-PA/molding                            -> Glass fibre reinforced plastic | 60 4.6s
  [0] 0.0                                        0/10  0.0%  -8.8% v [cached]
        HIT   [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75 4.2s
        HIT   [token] ⚡  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra 3.6s
        MISS 2/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 3.6s
        MISS --/20  [token] ⚡  Kingfa NPG25                                   -> Injection moulding {RER}| injection 5.2s
        MISS 12/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 50 3.9s
        MISS 10/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 3.6s
        MISS 12/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 3.5s
        MISS 2/20  [token] ⚡  Copper Wire/cold forming                       -> Metal working, average for copper p 3.4s
        MISS 15/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 10.4s
        MISS 8/20  [token] ⚡  SJRG0013-PA/molding                            -> Glass fibre reinforced plastic | 95 3.4s
  [1] 0.3                                        2/10  20.0%  +9.0% ^ [cached]
        MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95 3.5s
        HIT   [token] ⚡  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra 3.4s
        MISS 12/20  [token] ⚡  SJRG0010-ABS/molding                           -> Glass fibre reinforced plastic | 60 6.1s
        MISS 4/20  [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 95 4.8s
        MISS 13/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 5.3s
        MISS 3/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 3.9s
        MISS 11/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 2.6s
        MISS 13/20  [token] ⚡  Copper Wire/cold forming                       -> Galvanized Copper | 99.6% Copper 0. 3.7s
        MISS 7/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Wire drawing, steel {RER}| wire dra 10.4s
        MISS 6/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 4.9s
  [2] 0.7                                        1/10  10.0%  +0.3% ^ [cached]

======================================================================
  Axis 5/5: raw_content_limit (pipeline_param, 3 values)

In [15]:
#@title Scan analytics: variant leaderboard
if scan_df is not None and not scan_df.empty:
    show_scan_leaderboard(scan_df, axis_profiles)

VARIANT LEADERBOARD (all scan combos)
======================================================================

,rank,axis,variant,accuracy,delta,hits/total,errors
0,1,max_token_candidates,30,30.0%,+18.0%,3/10,0
1,2,profiling_schema,schema(12 fields),20.0%,+9.2%,2/10,0
2,3,query_prefix,what material is,20.0%,+9.2%,2/10,0
3,4,profiling_temperature,0.3,20.0%,+9.0%,2/10,0
4,5,max_token_candidates,50,20.0%,+9.0%,2/10,0
5,6,raw_content_limit,8000,10.0%,+0.3%,1/10,0
6,7,profiling_schema,schema(11 fields),10.0%,+0.3%,1/10,0
7,8,profiling_schema,schema(11 fields),10.0%,+0.3%,1/10,0
8,9,raw_content_limit,1000,10.0%,+0.3%,1/10,0
9,10,profiling_temperature,0.7,10.0%,+0.3%,1/10,0
10,11,profiling_schema,schema(10 fields) (baseline),10.0%,-,1/10,0
11,12,profiling_temperature,0.0,0.0%,-8.8%,0/10,0
12,13,query_prefix,identify LCA database name for,0.0%,-8.8%,0/10,0
13,14,raw_content_limit,2500,0.0%,-8.8%,0/10,0
14,15,profiling_schema,schema(13 fields),0.0%,-8.8%,0/10,0
15,16,max_token_candidates,10,0.0%,-9.0%,0/10,0
16,17,query_prefix,translate trade name,0.0%,-9.2%,0/10,0

PER-AXIS STATISTICS
======================================================================

,axis,type,variants,mean_acc,std_acc,best_acc,worst_acc,sensitivity,budget
0,max_token_candidates,pipeline_param,3,16.7%,15.3%,30.0%,0.0%,0.270,medium
1,query_prefix,pipeline_param,3,6.7%,11.5%,20.0%,0.0%,0.185,medium
2,profiling_schema,pipeline_param,5,10.0%,7.1%,20.0%,0.0%,0.180,medium
3,profiling_temperature,pipeline_param,3,10.0%,10.0%,20.0%,0.0%,0.177,medium
4,raw_content_limit,pipeline_param,3,6.7%,5.8%,10.0%,0.0%,0.090,skip

In [16]:
#@title Scan analytics: query difficulty
if scan_df is not None and not scan_df.empty:
    difficulty_df = show_scan_query_difficulty(
        svc["store"], svc["backend_id"],
    )

QUERY DIFFICULTY (728 queries across 59 scan runs)
======================================================================
  easy: 0 (0%) | discriminating: 5 (1%) | hard: 5 (1%) | error: 718 (99%)

,query,ground_truth,hit_rate,hits/evals,error_rate,classification
0,"BAND EN 10140-1,45x26 GK-DC01+C390-MB","Steel, unalloyed {GLO}| market for steel, unal...",0.000000,0/11,1.000000,error
1,"Kaltband EN 10140-2,5 x ... GK\nStahl EN 10139...","Steel removed by milling, small parts {RER}| s...",0.000000,0/11,1.000000,error
2,Adhesive label 13x5 white\nPolyethylen (PE) we...,"Polyethylene, low density, granulate {GLO}| ma...",0.000000,0/11,1.000000,error
3,"Strip EN13599-CU-PHC-R290-1,8x35-Ag0,3 /stamping","Metal working, average for copper product manu...",0.000000,0/22,1.000000,error
4,PA 66 25% GF V0 RAL 7012/0,Injection moulding {RoW}| injection moulding |...,0.000000,0/70,0.542857,hard
...,...,...,...,...,...,...
723,SJRG0013-PA/molding,Injection moulding {RER}| injection moulding |...,0.025000,1/40,0.550000,discriminating
724,SJRG0010-ABS/molding,Injection moulding {RER}| injection moulding |...,0.050847,3/59,0.457627,discriminating
725,Kingfa NPG25,Glass fibre reinforced plastic | 75% PA66 25% ...,0.220339,13/59,0.457627,discriminating
726,PA66-GF25 ULTRAMID A3UG5 RAL7035 grey,Glass fibre reinforced plastic | 75% PA66 25% ...,0.288136,17/59,0.457627,discriminating
727,Stainless steel EN 10270-3/winding,"Wire drawing, steel {RER}| wire drawing, steel...",0.357143,25/70,0.542857,discriminating

In [17]:
#@title Select scan winner & seed campaign
best_sp = seed_campaign_from_scan(
    scan_df, axis_profiles, baseline_sp, scan_variants,
    campaign_rounds, campaign_config,
)

2026-03-13 15:41:02 INFO     [api.services.search.smart_search] select_scan_winner: 0 prompt changes, 4 param changes from 4 improving axes

Selected best from 4 improving axes:
  max_token_candidates      best_delta=+18.0%  value_idx=1  acc=30.0%
  query_prefix              best_delta=+9.2%  value_idx=0  acc=20.0%
  profiling_schema          best_delta=+9.2%  value_idx=2  acc=20.0%
  profiling_temperature     best_delta=+9.0%  value_idx=1  acc=20.0%
Pipeline params updated: {'steps': ['cache_lookup', 'fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching'], 'max_token_candidates': 30, 'query_prefix': 'what material is', 'profiling_schema': {'type': 'object', 'properties': {'entity_name': {'type': 'string'}, 'core_concept': {'type': 'string', 'description': 'The single word that defines what this expression represents'}, 'distinguishing_features': {'type': 'array', 'items': {'type': 'string'}}, 'key_properties': {'type': 'array', 'items': {'type': 'string'}}, 'technical_specifications': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Explicit technical specs, dimensions, codes, ratings, tolerances'}, 'alternative_names': {'type': 'array', 'items': {'type': 'string'}}, 'classification_aliases': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic'}, 'constituent_materials': {'type': 'array', 'items': {'type': 'string'}, 'description': 'All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge'}, 'manufacturing_processes': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Both stated and inferred manufacturing processes based on product type, materials, and industry standards'}, 'applications': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Direct and derived applications based on product characteristics'}, 'notes': {'type': 'array', 'items': {'type': 'string'}}, 'lca_database_names': {'type': 'array', 'items': {'type': 'string'}, 'description': "Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'"}}, 'required': ['entity_name', 'core_concept', 'distinguishing_features', 'key_properties', 'technical_specifications', 'alternative_names', 'classification_aliases', 'constituent_materials', 'manufacturing_processes', 'applications', 'notes', 'lca_database_names']}, 'profiling_temperature': 0.3}
Updated pipeline_params: {'steps': ['cache_lookup', 'fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching'], 'max_token_candidates': 30, 'query_prefix': 'what material is', 'profiling_schema': {'type': 'object', 'properties': {'entity_name': {'type': 'string'}, 'core_concept': {'type': 'string', 'description': 'The single word that defines what this expression represents'}, 'distinguishing_features': {'type': 'array', 'items': {'type': 'string'}}, 'key_properties': {'type': 'array', 'items': {'type': 'string'}}, 'technical_specifications': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Explicit technical specs, dimensions, codes, ratings, tolerances'}, 'alternative_names': {'type': 'array', 'items': {'type': 'string'}}, 'classification_aliases': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic'}, 'constituent_materials': {'type': 'array', 'items': {'type': 'string'}, 'description': 'All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge'}, 'manufacturing_processes': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Both stated and inferred manufacturing processes based on product type, materials, and industry standards'}, 'applications': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Direct and derived applications based on product characteristics'}, 'notes': {'type': 'array', 'items': {'type': 'string'}}, 'lca_database_names': {'type': 'array', 'items': {'type': 'string'}, 'description': "Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'"}}, 'required': ['entity_name', 'core_concept', 'distinguishing_features', 'key_properties', 'technical_specifications', 'alternative_names', 'classification_aliases', 'constituent_materials', 'manufacturing_processes', 'applications', 'notes', 'lca_database_names']}, 'profiling_temperature': 0.3}

Round    Accuracy   Rolling Avg    Trend
  search    10.0%        10.0%  -

### 3b. Grid Search

<details>
<summary>Skip if you used Smart Search above.</summary>

Systematic sweep of the prompt configuration space. Maps the accuracy landscape before hill-climbing.

</details>

In [18]:
# #@title Grid campaign overview (existing plans)
# merge_plans = False  # Set True to combine results from multiple plans
# grid_overview = show_grid_overview(svc, campaign_config, merge_plans=merge_plans)
# merged_grid_df = grid_overview.get("merged_grid_df")

In [19]:
# #@title Build or resume grid plan
# gs = campaign_config["grid_search"]

# llm_client, llm_model = setup_llm(campaign_config)

# (
#     grid_plan_id, grid_points, grid_state_lookup,
#     grid_axes, layer1_fields, grid_baseline,
# ) = await resume_or_build_grid(
#     campaign_config, baseline, llm_client, llm_model,
#     svc["store"], svc["backend_id"],
#     improvement_areas=campaign_config.get("improvement_areas", ""),
# )

# print(f"Grid points: {len(grid_points)}")
# print(f"Plan ID: {grid_plan_id}")

In [20]:
# #@title Run grid search
# grid_df = await run_grid_search(
#     grid_points, grid_state_lookup, eval_data,
#     campaign_config["eval_llm"],
#     plan_id=grid_plan_id,
#     store=svc["store"], backend_id=svc["backend_id"],
#     backend_client=svc.get("backend_client"),
#     session_terms=svc.get("session_terms"),
#     pipeline_params=campaign_config.get("pipeline_params"),
#     sample_size=gs.get("sample_size", 1),
#     shared_queries=gs.get("shared_queries", False),
#     grid_seed=gs.get("seed", 42),
# )

In [21]:
# #@title Display grid results
# _display_df = merged_grid_df if merged_grid_df is not None else grid_df
# display_grid_results(_display_df, grid_axes, top_k=gs.get("top_k", 5))

In [22]:
# #@title LLM analysis of grid results
# _analysis_df = merged_grid_df if merged_grid_df is not None else grid_df
# llm_client, llm_model = setup_llm(campaign_config)
# grid_analysis = await analyze_grid_results(
#     _analysis_df, grid_axes, llm_client, model=llm_model,
# )

In [23]:
# #@title Select grid winner and seed campaign
# grid_winner = select_and_seed_grid_winner(
#     grid_df, merged_grid_df, grid_state_lookup,
#     grid_overview.get("plan_dfs", {}), svc, campaign_rounds,
# )

## 4. Optimize

Two modes: **Semi-automatic** (feedback cycle with patience-based auto-stop) or **Manual** (one round at a time).

In [24]:
#@title Feedback cycle preflight
scan_context = show_feedback_preflight(
    campaign_rounds, eval_data, campaign_config,
    pipeline_params=campaign_config.get("pipeline_params"),
    scan_df=scan_df if "scan_df" in dir() else None,
    axis_profiles=axis_profiles if "axis_profiles" in dir() else None,
    scan_variants=scan_variants if "scan_variants" in dir() else None,
    difficulty_df=difficulty_df if "difficulty_df" in dir() else None,
)

======================================================================
  FEEDBACK CYCLE PRE-FLIGHT
======================================================================
  Baseline accuracy      : 10.0%
  Baseline prompt        : TASK 1: Summarize the profile in 1‑2 sentences, identify entity_category, and li...
  ------------------------------------------------------------------
  Max rounds             : 3
  Candidates per round   : 5
  Queries per eval       : 15 of 984
  Improvement threshold  : 1.0%
  Patience (L1)          : 2 rounds
  L2 (refine context)    : disabled
  L3 (modify plan)       : disabled
  ------------------------------------------------------------------
  Candidate model        : openai/gpt-oss-120b
  Creativity             : 0.7
  Pipeline               : 5 of 6 steps
    Steps                : cache_lookup, fuzzy_matching, web_search, entity_profiling, token_matching
    Excluded             : llm_ranking
  Strategy               : SCAN-AWARE

  ROUND PIPELINE (what happens each round)
  ------------------------------------------------------------------
  1. BASELINE INPUT
     Prompt: TASK 1: Summarize the profile in 1‑2 sentences, identify entity_category, and li...
     Accuracy: 10.0%  |  Prior results: 0
  2. FAILURE ANALYSIS
     Up to 15 failures extracted (currently 0 available)
  3. CONTEXT ASSEMBLY
     Strategy: SCAN-AWARE
     Scan leaderboard: 17 entries
     Top performer: max_token_candidates     30                                       acc=30.0%  delta=+18.0%  hits=3/10
     Sensitivity axes: 5
     Difficulty: Query classes: easy: 0 (0%) | discriminating: 5 (1%) | hard: 5 (1%) | error: 718 (99%)
     Improving axes: 4 (max_token_candidates, query_prefix, profiling_schema, profiling_temperature)
     Tested values: 4 axes with per-value data
  4. LLM CANDIDATE GENERATION
     Model: openai/gpt-oss-120b  |  Temperature: 0.7
     Candidates: 5
     Output: prompt + pipeline_params_override per candidate
  5. BACKEND EVALUATION
     Queries per candidate: 15 of 984
     Scoring: accuracy
  6. WINNER SELECTION
     Criterion: best accuracy >= baseline + 1.0%
  7. LOOP CONTROL
     Patience: 2 stalls → stop  |  L2: disabled  |  L3: disabled
  ------------------------------------------------------------------
  Est. backend calls     : 225  (3r x 5c x 15q)

  SCAN CONTEXT PREVIEW (injected into LLM meta-prompt)
  ------------------------------------------------------------------
  Leaderboard:
  max_token_candidates     30                                       acc=30.0%  delta=+18.0%  hits=3/10
    profiling_schema         schema(12 fields)                        acc=20.0%  delta=+9.2%  hits=2/10
    query_prefix             what material is                         acc=20.0%  delta=+9.2%  hits=2/10
    profiling_temperature    0.3                                      acc=20.0%  delta=+9.0%  hits=2/10
    max_token_candidates     50                                       acc=20.0%  delta=+9.0%  hits=2/10
    raw_content_limit        8000                                     acc=10.0%  delta=+0.3%  hits=1/10
    profiling_schema         schema(11 fields)                        acc=10.0%  delta=+0.3%  hits=1/10
    profiling_schema         schema(11 fields)                        acc=10.0%  delta=+0.3%  hits=1/10
    raw_content_limit        1000                                     acc=10.0%  delta=+0.3%  hits=1/10
    profiling_temperature    0.7                                      acc=10.0%  delta=+0.3%  hits=1/10
    ... 7 more
  Axis sensitivity:
  1. max_token_candidates     type=pipeline_param sensitivity=0.270  card=3  budget=medium  [room: best_delta=+18.0%]
    2. query_prefix             type=pipeline_param sensitivity=0.185  card=3  budget=medium  [room: best_delta=+9.2%]
    3. profiling_schema         type=pipeline_param sensitivity=0.180  card=5  budget=medium  [room: best_delta=+9.2%]
    4. profiling_temperature    type=pipeline_param sensitivity=0.177  card=3  budget=medium  [room: best_delta=+9.0%]
    5. raw_content_limit        type=pipeline_param sensitivity=0.090  card=3  budget=skip  [room: best_delta=+0.2%]
  Query difficulty:
  Query classes: easy: 0 (0%) | discriminating: 5 (1%) | hard: 5 (1%) | error: 718 (99%)
  Improving axes: max_token_candidates, query_prefix, profiling_schema, profiling_temperature
  Tested values:
  max_token_candidates (3 values tested):
      [1] 30  acc=30.0%
      [2] 50  acc=20.0%
      [0] 10  acc=0.0%
    query_prefix (3 values tested):
      [0] what material is  acc=20.0%
      [1] identify LCA database name for  acc=0.0%
      [2] translate trade name  acc=0.0%
    profiling_schema (5 values tested):
      [2] schema(12 fields)  acc=20.0%
      [0] schema(11 fields)  acc=10.0%
      [3] schema(10 fields)  acc=10.0% *baseline*
      [4] schema(11 fields)  acc=10.0%
      [1] schema(13 fields)  acc=0.0%
    profiling_temperature (3 values tested):
    ... 3 more lines
======================================================================

In [26]:
#@title Run optimization (feedback cycle)
campaign_rounds = await run_feedback_cycle_notebook(
    campaign_rounds, eval_data, campaign_config,
    store=svc["store"], backend_id=svc["backend_id"],
    backend_url=svc["backend_client"].base_url,
    pipeline_params=campaign_config.get("pipeline_params"),
    session_terms=svc.get("session_terms"),
    scan_context=scan_context if "scan_context" in dir() else None,
)

2026-03-13 15:48:54 INFO     [api.services.campaign.feedback_cycle] Using provided baseline (acc=0.200)
2026-03-13 15:48:54 INFO     [api.services.campaign.feedback_cycle] Cycle identity: cycle_68e2c53845c3

╔════════════════════════════════════════════════════════════════════╗
║  FEEDBACK CYCLE STARTING                                           ║
╠════════════════════════════════════════════════════════════════════╣
║  Baseline       20.0%                                              ║
║  Max rounds     3              Patience    2                       ║
║  Candidates     5                                                  ║
║  Sample size    15 of 984                                          ║
║  Min detectable ±36.2% (α=0.05, 80% power)                         ║
║  Model          openai/gpt-oss-120b                                ║
║  L2 (refine)    disabled           L3 (plan)   disabled            ║
║  Scan context   YES                                                ║
╚════════════════════════════════════════════════════════════════════╝

2026-03-13 15:48:54 INFO     [api.services.campaign.feedback_cycle] Resuming cycle cycle_68e2c53845c3 from round 1 (best_acc=0.200)
2026-03-13 15:48:55 INFO     [api.services.obs.observability_logger] Dataset 'termnorm_ground_truth': 728 items registered, 256 duplicates/empty skipped (from 984 input)
2026-03-13 15:48:55 WARNING  [api.services.obs.observability_logger] Skipping Langfuse cloud dataset registration for 984 items (rate-limit risk). Use the dedicated Langfuse sync cell instead.
2026-03-13 15:48:55 INFO     [api.services.campaign.feedback_cycle] Registered 728 dataset items for 'termnorm_ground_truth'
2026-03-13 15:48:55 INFO     [api.services.campaign.feedback_cycle] Feedback cycle round 0 (acc=0.200, stall=0/2)
2026-03-13 15:48:55 INFO     [api.services.campaign.feedback_cycle] Loaded 5 persisted candidates for round 0

  ✓ Initialized  cycle=cycle_68e2c5  samples=15  obs=ON
    Resumed from round 1 (1 rounds cached)

┌─ Round 1/3 ───────────────────────────────────────── patience 0/2 ─┐
│  GENERATING CANDIDATES                                             │
│  Current best    20.0%                                             │
│  Prompt          You are a candidate evaluation expert.  Summari...│
│  Candidates      5   Creativity: 0.7   Scan: YES                   │
│  Model           openai/gpt-oss-120b                               │
└────────────────────────────────────────────────────────────────────┘
  Scan focus: 4 improving axes [max_token_candidates, query_prefix, profiling_schema, profiling_temperature]
  Scan baseline: 10.0%
  ✓ 5 candidates generated (loaded from disk)
    C1: Increase max_token_candidates to 40 and set pro... pp=[max_token_candidates, profiling_temperature, query_prefix, +1]
    C2: Swap query_prefix to a semantic variant and exp... pp=[query_prefix, profiling_schema, max_token_candidates, +1]
    C3: Raise raw_content_limit to 12000 while keeping ... pp=[raw_content_limit, max_token_candidates, query_prefix, +2]
    C4: Combine a higher max_token_candidates (50) with... pp=[max_token_candidates, profiling_temperature, profiling_schema, +1]
    C5: Explore a larger token budget (70) and higher t... pp=[max_token_candidates, profiling_temperature, query_prefix, +2]
  Evaluating 5 x 15 = 75 backend calls

  EVALUATING  5 candidates x 15 queries  |  beat 20.0% + 1.0%
  [  1] HIT   [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75 9.4s
  [  2] MISS 2/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER 6.4s
  [  3] MISS 2/20  [token] ⚡  SJRG0010-ABS/molding                           -> Injection moulding {RoW}| injection 7.5s
  [  4] MISS 7/20  [token] ⚡  Kingfa NPG25                                   -> Polyamide (Nylon) 6.6/EU-27 12.1s
  [  5] MISS 13/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 75 8.9s
  [  6] MISS 4/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 9.4s
  [  7] MISS 13/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 6.9s
  [  8] MISS --/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RER}| wire dr 10.8s
  [  9] MISS 7/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Galvanized Copper | 99.6% Copper 0. 7.2s
  [ 10] MISS 8/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 6.3s
  [ 11] MISS 6/20  [token] ⚡  Halbzeug: 5.8 ISO 898-1/threat rolling         -> Wire drawing, steel {RER}| wire dra 10.7s
  [ 12] MISS --/20  [token] ⚡  Strip EN 1652-Cu-DHP-R220-2.0x100              -> Galvanized Copper | 99.6% Copper 0. 7.9s
  [ 13] MISS 10/20  [token] ⚡  Cu + AgNi                                      -> Galvanized Copper | 99.6% Copper 0. 12.0s
  [ 14] MISS --/20  [token] ⚡  Strip Berylco 07 HT R770-0,4x35/stamping       -> Galvanized Copper | 99.6% Copper 0. 10.8s
                    ⚠ web_search: Web search failed (inferred from pre-diagnostics cache)
  [ 15] MISS 5/20  [token] ⚡  PA66 Ultramid A3SK/injection moulding          -> Polyamide (Nylon) 6.6/EU-27 7.7s

  ┌─ C1/5 ───────────────────────────────────── 6.7% [1.2%-29.8%] ─┐
  │  Increase max_token_candidates to 40 and se...  pp=[max_token_candidates, profiling_temperature, +2]│
  │  1/15 hits  composite=0.0600  ⚠ 1/15 degraded  vs baseline: -13.3%│
  │  best so far: C1 6.7%                                          │
  └────────────────────────────────────────────────────────────────┘
  [ 16] HIT   [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75 8.2s
  [ 17] MISS 2/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER 7.5s
  [ 18] MISS 7/20  [token] ⚡  SJRG0010-ABS/molding                           -> Glass fibre reinforced plastic | 60 10.5s
  [ 19] MISS 4/20  [token] ⚡  Kingfa NPG25                                   -> Polyamide (Nylon) 6.6/EU-27 8.0s
  [ 20] MISS 15/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 75 10.9s
  [ 21] MISS 4/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 8.6s
  [ 22] MISS 10/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 5.9s
  [ 23] MISS 4/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RER}| wire dr 10.1s
  [ 24] MISS 8/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Wire drawing, copper {RER}| wire dr 7.7s
  [ 25] MISS 12/20  [token] ⚡  SJRG0013-PA/molding                            -> Glass fibre reinforced plastic | 50 7.3s
  [ 26] MISS 5/20  [token] ⚡  Halbzeug: 5.8 ISO 898-1/threat rolling         -> Hot rolling, steel {RoW}| hot rolli 10.4s
  [ 27] MISS 12/20  [token] ⚡  Strip EN 1652-Cu-DHP-R220-2.0x100              -> Galvanized Copper | 99.6% Copper 0. 6.4s
  [ 28] MISS 7/20  [token] ⚡  Cu + AgNi                                      -> Galvanized Copper | 99.6% Copper 0. 10.7s
  [ 29] MISS --/20  [token] ⚡  Strip Berylco 07 HT R770-0,4x35/stamping       -> Steel, zinc coated /RER 11.2s
                    ⚠ web_search: Web search failed (inferred from pre-diagnostics cache)
  [ 30] MISS 5/20  [token] ⚡  PA66 Ultramid A3SK/injection moulding          -> Polyamide (Nylon) 6.6/EU-27 8.4s

  ┌─ C2/5 ───────────────────────────────────── 6.7% [1.2%-29.8%] ─┐
  │  Swap query_prefix to a semantic variant an...  pp=[query_prefix, profiling_schema, +2]│
  │  1/15 hits  composite=0.0600  ⚠ 1/15 degraded  vs baseline: -13.3%│
  │  best so far: C1 6.7%                                          │
  └────────────────────────────────────────────────────────────────┘
  [ 31] MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 50 9.4s
  [ 32] HIT   [token] ⚡  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra 5.9s
  [ 33] MISS 8/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 10.0s
  [ 34] HIT   [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 75 6.4s
  [ 35] MISS 15/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 50 12.3s
  [ 36] MISS 2/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 9.7s
  [ 37] MISS 13/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 6.8s
  [ 38] MISS --/20  [token] ⚡  Copper Wire/cold forming                       -> Galvanized Copper | 99.6% Copper 0. 11.6s
  [ 39] MISS --/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Wire drawing, steel {RER}| wire dra 6.6s
  [ 40] MISS 12/20  [token] ⚡  SJRG0013-PA/molding                            -> Glass fibre reinforced plastic | 50 8.6s
  [ 41] MISS 5/20  [token] ⚡  Halbzeug: 5.8 ISO 898-1/threat rolling         -> Sheet rolling, chromium steel {RER} 16.5s
  [ 42] MISS 12/20  [token] ⚡  Strip EN 1652-Cu-DHP-R220-2.0x100              -> Galvanized Copper | 99.6% Copper 0. 6.3s
  [ 43] MISS 19/20  [token] ⚡  Cu + AgNi                                      -> Galvanized Copper | 99.6% Copper 0. 8.4s
  [ 44] MISS 10/20  [token] ⚡  Strip Berylco 07 HT R770-0,4x35/stamping       -> Galvanized Copper | 99.6% Copper 0. 12.3s
  [ 45] MISS 6/20  [token] ⚡  PA66 Ultramid A3SK/injection moulding          -> Glass fibre reinforced plastic | 75 8.1s

  ┌─ C3/5 ──────────────────────────────────── 13.3% [3.7%-37.9%] ─┐
  │  Raise raw_content_limit to 12000 while kee...  pp=[raw_content_limit, max_token_candidates, +3]│
  │  2/15 hits  composite=0.1200  vs baseline: -6.7%               │
  │  best so far: C3 13.3%                                         │
  └────────────────────────────────────────────────────────────────┘
  [ 46] HIT   [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75 10.0s
  [ 47] HIT   [token] ⚡  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra 6.5s
  [ 48] MISS 3/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 7.3s
  [ 49] HIT   [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 75 6.7s
  [ 50] MISS 15/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Polyamide (Nylon) 6.6/EU-27 11.3s
  [ 51] MISS 2/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 10.1s
  [ 52] MISS 13/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 6.0s
  [ 53] MISS 19/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, steel {RER}| wire dra 10.9s
  [ 54] MISS 7/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Wire drawing, steel {RER}| wire dra 7.6s
  [ 55] MISS 8/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 9.2s
  [ 56] MISS 3/20  [token] ⚡  Halbzeug: 5.8 ISO 898-1/threat rolling         -> Hot rolling, steel {RoW}| hot rolli 13.3s
  [ 57] MISS 19/20  [token] ⚡  Strip EN 1652-Cu-DHP-R220-2.0x100              -> Galvanized Copper | 99.6% Copper 0. 7.6s
  [ 58] MISS 13/20  [token] ⚡  Cu + AgNi                                      -> Galvanized Copper | 99.6% Copper 0. 9.2s
  [ 59] MISS --/20  [token] ⚡  Strip Berylco 07 HT R770-0,4x35/stamping       -> Hot rolling, steel {RoW}| hot rolli 13.1s
  [ 60] MISS 2/20  [token] ⚡  PA66 Ultramid A3SK/injection moulding          -> Polyamide (Nylon) 6.6/EU-27 8.3s

  ┌─ C4/5 ──────────────────────────────────── 20.0% [7.0%-45.2%] ─┐
  │  Combine a higher max_token_candidates (50)...  pp=[max_token_candidates, profiling_temperature, +2]│
  │  3/15 hits  composite=0.1800  vs baseline: +0.0%               │
  │  best so far: C4 20.0%                                         │
  └────────────────────────────────────────────────────────────────┘
  [ 61] MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 65 11.6s
  [ 62] MISS 3/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Hot rolling, steel {RoW}| hot rolli 14.1s
  [ 63] MISS 2/20  [token] ⚡  SJRG0010-ABS/molding                           -> Injection moulding {RoW}| injection 13.7s
  [ 64] HIT   [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 75 7.9s
  [ 65] MISS 11/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 75 12.8s
  [ 66] MISS 5/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 15.2s
  [ 67] MISS 12/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 8.7s
  [ 68] MISS 16/20  [token] ⚡  Copper Wire/cold forming                       -> Galvanized Copper | 99.6% Copper 0. 13.0s
  [ 69] MISS 13/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 12.3s
  [ 70] MISS 12/20  [token] ⚡  SJRG0013-PA/molding                            -> Glass fibre reinforced plastic | 50 11.6s
  [ 71] MISS 3/20  [token] ⚡  Halbzeug: 5.8 ISO 898-1/threat rolling         -> Steel, zinc coated /RER 13.4s
  [ 72] MISS --/20  [token] ⚡  Strip EN 1652-Cu-DHP-R220-2.0x100              -> Sheet rolling, copper {RoW}| sheet  12.2s
  [ 73] MISS 5/20  [token] ⚡  Cu + AgNi                                      -> Copper, cathode {GLO}| market for c 9.7s
  [ 74] MISS --/20  [token] ⚡  Strip Berylco 07 HT R770-0,4x35/stamping       -> Steel, zinc coated /RER 14.6s
  [ 75] MISS 4/20  [token] ⚡  PA66 Ultramid A3SK/injection moulding          -> Polyamide (Nylon) 6.6/EU-27 11.0s

2026-03-13 15:48:55 INFO     [api.services.campaign.feedback_cycle] Feedback cycle round 1 (acc=0.200, stall=1/2)
2026-03-13 15:48:55 INFO     [api.services.campaign.feedback_cycle] Loaded 5 persisted candidates for round 1

  ┌─ C5/5 ───────────────────────────────────── 6.7% [1.2%-29.8%] ─┐
  │  Explore a larger token budget (70) and hig...  pp=[max_token_candidates, profiling_temperature, +3]│
  │  1/15 hits  composite=0.0600  vs baseline: -13.3%              │
  │  best so far: C4 20.0%                                         │
  └────────────────────────────────────────────────────────────────┘
  ┌─ SCOREBOARD ───────────────────────────────────────────────────────────────┐
  │  #   Label    Accuracy            95% CI  Composite    Delta               │
  │  1   C4         20.0%       [7.0%-45.2%]     0.1800       ---  *           │
  │  2   C3         13.3%       [3.7%-37.9%]     0.1200     -6.7%              │
  │  3   C1          6.7%       [1.2%-29.8%]     0.0600    -13.3%              │
  │  4   C2          6.7%       [1.2%-29.8%]     0.0600    -13.3%              │
  │  5   C5          6.7%       [1.2%-29.8%]     0.0600    -13.3%              │
  └────────────────────────────────────────────────────────────────────────────┘
  ⚠ NO IMPROVEMENT  best candidate 20.0%  ->  patience 1/2

├─ Round 1 complete ─────────────────────────────────────────────────┤

Round    Accuracy  Composite   Rolling Avg    Trend
  search    10.0%    0.1000        10.0%  -
  1        20.0%    0.1800        15.0%  +10.0%
  2        20.0%    0.2000        16.7%  +0.0%  <-- plateau
  hits: 3/15  |  evaluated: 5 candidates
  ⚠ No improvement (1/2 patience)

┌─ Round 2/3 ───────────────────────────────────────── patience 1/2 ─┐
│  GENERATING CANDIDATES                                             │
│  Current best    20.0%                                             │
│  Prompt          You are a candidate evaluation expert.  Summari...│
│  Candidates      5   Creativity: 0.7   Scan: YES                   │
│  Model           openai/gpt-oss-120b                               │
└────────────────────────────────────────────────────────────────────┘
  Scan focus: 4 improving axes [max_token_candidates, query_prefix, profiling_schema, profiling_temperature]
  Scan baseline: 10.0%
  ✓ 5 candidates generated (loaded from disk)
    C1: Increase max_token_candidates to explore larger... pp=[max_token_candidates]
    C2: Use a semantically similar query prefix pp=[query_prefix]
    C3: Expand profiling_schema to 14 fields pp=[profiling_schema]
    C4: Lower profiling_temperature slightly pp=[profiling_temperature]
    C5: Increase raw_content_limit to allow more context pp=[raw_content_limit]
  Evaluating 5 x 15 = 75 backend calls

  EVALUATING  5 candidates x 15 queries  |  beat 20.0% + 1.0%
  [  1] MISS 3/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 90 12.2s
  [  2] MISS 4/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER 10.5s
  [  3] MISS 3/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 11.8s
  [  4] MISS 2/20  [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 90 9.7s
  [  5] MISS 10/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 50 14.2s
  [  6] MISS 17/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 12.3s
  [  7] MISS 12/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 8.0s
  [  8] MISS 2/20  [token] ⚡  Copper Wire/cold forming                       -> Galvanized Copper | 99.6% Copper 0. 11.8s
  [  9] MISS 9/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 9.1s
  [ 10] MISS 17/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 10.8s
  [ 11] MISS 14/20  [token] ⚡  Halbzeug: 5.8 ISO 898-1/threat rolling         -> Galvanized Copper | 99.6% Copper 0. 13.8s
  [ 12] MISS 11/20  [token] ⚡  Strip EN 1652-Cu-DHP-R220-2.0x100              -> Hot rolling, steel {RoW}| hot rolli 15.2s
  [ 13] MISS 5/20  [token] ⚡  Cu + AgNi                                      -> Copper, cathode {GLO}| market for c 10.0s
  [ 14] MISS 16/20  [token] ⚡  Strip Berylco 07 HT R770-0,4x35/stamping       -> Galvanized Copper | 99.6% Copper 0. 13.3s
  [ 15] MISS 4/20  [token] ⚡  PA66 Ultramid A3SK/injection moulding          -> Polyamide (Nylon) 6.6/EU-27 7.3s

  ┌─ C1/5 ───────────────────────────────────── 0.0% [0.0%-20.4%] ─┐
  │  Increase max_token_candidates to explore l...  pp=[max_token_candidates]│
  │  0/15 hits  vs baseline: -20.0%                                │
  │  best so far: C1 0.0%                                          │
  └────────────────────────────────────────────────────────────────┘
  [ 16] HIT   [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75 8.7s
  [ 17] MISS 2/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER 8.5s
  [ 18] MISS 3/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 18.6s
  [ 19] HIT   [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 75 7.9s
  [ 20] MISS 10/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 90 12.8s
  [ 21] MISS 4/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 11.2s
  [ 22] MISS 9/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 8.9s
  [ 23] MISS 19/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RoW}| wire dr 9.3s
  [ 24] MISS 8/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 7.8s
  [ 25] MISS 11/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 10.4s
  [ 26] MISS 14/20  [token] ⚡  Halbzeug: 5.8 ISO 898-1/threat rolling         -> Hot rolling, steel {RoW}| hot rolli 12.3s
  [ 27] MISS 12/20  [token] ⚡  Strip EN 1652-Cu-DHP-R220-2.0x100              -> Brazing solder, cadmium free {GLO}| 7.4s
  [ 28] MISS 5/20  [token] ⚡  Cu + AgNi                                      -> Copper, cathode {GLO}| market for c 6.7s
  [ 29] MISS 9/20  [token] ⚡  Strip Berylco 07 HT R770-0,4x35/stamping       -> Galvanized Copper | 99.6% Copper 0. 11.2s
  [ 30] MISS 3/20  [token] ⚡  PA66 Ultramid A3SK/injection moulding          -> Polyamide (Nylon) 6.6/EU-27 8.9s

  ┌─ C2/5 ──────────────────────────────────── 13.3% [3.7%-37.9%] ─┐
  │  Use a semantically similar query prefix  pp=[query_prefix]    │
  │  2/15 hits  composite=0.1200  vs baseline: -6.7%               │
  │  best so far: C2 13.3%                                         │
  └────────────────────────────────────────────────────────────────┘
  [ 31] HIT   [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75 8.8s
  [ 32] MISS 2/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER 5.7s
  [ 33] MISS --/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 9.9s
  [ 34] MISS 2/20  [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 65 7.5s
  [ 35] MISS 11/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 75 10.6s
  [ 36] MISS 7/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 10.6s
  [ 37] MISS 11/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 6.0s
  [ 38] MISS 20/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RoW}| wire dr 10.3s
  [ 39] MISS 13/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 7.1s
  [ 40] MISS 10/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 9.1s
  [ 41] MISS 11/20  [token] ⚡  Halbzeug: 5.8 ISO 898-1/threat rolling         -> Metal working, average for steel pr 12.7s
  [ 42] MISS --/20  [token] ⚡  Strip EN 1652-Cu-DHP-R220-2.0x100              -> Galvanized Copper | 99.6% Copper 0. 8.9s
                    ⚠ web_search: 5 of 6 URLs scraped successfully
  [ 43] MISS 17/20  [token] ⚡  Cu + AgNi                                      -> Galvanized Copper | 99.6% Copper 0. 8.0s
  [ 44] MISS --/20  [token] ⚡  Strip Berylco 07 HT R770-0,4x35/stamping       -> Galvanized Copper | 99.6% Copper 0. 13.3s
                    ⚠ web_search: All scraping failed (1 attempts)
  [ 45] MISS 3/20  [token] ⚡  PA66 Ultramid A3SK/injection moulding          -> Polyamide (Nylon) 6.6/EU-27 9.1s

  ┌─ C3/5 ───────────────────────────────────── 6.7% [1.2%-29.8%] ─┐
  │  Expand profiling_schema to 14 fields  pp=[profiling_schema]   │
  │  1/15 hits  composite=0.0600  ⚠ 2/15 degraded  vs baseline: -13.3%│
  │  best so far: C2 13.3%                                         │
  └────────────────────────────────────────────────────────────────┘
  [ 46] MISS 2/20  [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 65 8.9s
  [ 47] MISS 2/20  [token] ⚡  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m 7.9s
  [ 48] MISS 3/20  [token] ⚡  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 9.7s
                    ⚠ web_search: 2 of 14 fetched URLs returned content
  [ 49] MISS 9/20  [token] ⚡  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 95 12.4s
  [ 50] MISS 12/20  [token] ⚡  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 13.0s
                    ⚠ web_search: 7 of 9 fetched URLs returned content
  [ 51] MISS 9/20  [token] ⚡  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 9.0s
  [ 52] MISS 10/20  [token] ⚡  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 6.5s
                    ⚠ web_search: 3 of 14 fetched URLs returned content
  [ 53] MISS 4/20  [token] ⚡  Copper Wire/cold forming                       -> Wire drawing, copper {RoW}| wire dr 9.1s
  [ 54] MISS 7/20  [token] ⚡  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Wire drawing, steel {RER}| wire dra 9.0s
  [ 55] MISS 12/20  [token] ⚡  SJRG0013-PA/molding                            -> Polyamide (Nylon) 6.6/EU-27 10.2s
  [ 56] MISS 4/20  [token] ⚡  Halbzeug: 5.8 ISO 898-1/threat rolling         -> Sheet rolling, chromium steel {RER} 11.3s
                    ⚠ web_search: 4 of 14 fetched URLs returned content
  [ 57] MISS --/20  [token] ⚡  Strip EN 1652-Cu-DHP-R220-2.0x100              -> Galvanized Copper | 99.6% Copper 0. 8.4s
                    ⚠ web_search: 5 of 14 fetched URLs returned content
  [ 58] MISS 13/20  [token] ⚡  Cu + AgNi                                      -> Galvanized Copper | 99.6% Copper 0. 8.8s
  [ 59] MISS --/20  [token] ⚡  Strip Berylco 07 HT R770-0,4x35/stamping       -> Sheet rolling, copper {RoW}| sheet  11.7s
                    ⚠ web_search: 0 of 14 fetched URLs returned content (1 error, 13 filtered)
  [ 60] MISS 4/20  [token] ⚡  PA66 Ultramid A3SK/injection moulding          -> Polyamide (Nylon) 6.6/EU-27 12.9s

2026-03-13 15:48:55 INFO     [api.services.prompt_eval] Resuming candidate_4_b9f19189: 1 cached results, 14 remaining

  ┌─ C4/5 ───────────────────────────────────── 0.0% [0.0%-20.4%] ─┐
  │  Lower profiling_temperature slightly  pp=[profiling_temperature]│
  │  0/15 hits  ⚠ 6/15 degraded  vs baseline: -20.0%               │
  │  best so far: C2 13.3%                                         │
  └────────────────────────────────────────────────────────────────┘
  [ 61] HIT   [token] ⚡  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75 7.2s
  [ 62] HIT   [token]  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra 5.9s
  [ 63] MISS --/20  [token]  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop 8.3s
                  ⚠ web_search: 2 of 14 fetched URLs returned content
  [ 64] MISS 4/20  [token]  Kingfa NPG25                                   -> Glass fibre reinforced plastic | 50 21.1s
                  ⚠ web_search: 3 of 14 fetched URLs returned content
  [ 65] MISS 11/20  [token]  PA 66 25% GF V0 RAL 7012/0                     -> Glass fibre reinforced plastic | 95 7.1s
                  ⚠ web_search: 7 of 11 fetched URLs returned content
  [ 66] MISS 13/20  [token]  PA6/66 Ultramid C3U/molding                    -> Polyamide (Nylon) 6.6/EU-27 10.6s
                  ⚠ web_search: 4 of 14 fetched URLs returned content
  [ 67] MISS 11/20  [token]  PC  GF10  makrolon material/0                  -> Glass fibre reinforced plastic | 90 6.4s
                  ⚠ web_search: 3 of 14 fetched URLs returned content
  [ 68] MISS 18/20  [token]  Copper Wire/cold forming                       -> Wire drawing, copper {RoW}| wire dr 10.8s
                  ⚠ web_search: 7 of 12 fetched URLs returned content
  [ 69] MISS 5/20  [token]  EN 10270-3-1.4568
X7CrNi17-7 (DIN17224 4.4568  -> Steel, chromium steel 18/8 {GLO}| m 7.3s
  [ 70] MISS 11/20  [token]  SJRG0013-PA/molding                            -> Glass fibre reinforced plastic | 50 8.9s
  [ 71] MISS 10/20  [token]  Halbzeug: 5.8 ISO 898-1/threat rolling         -> Galvanized Copper | 99.6% Copper 0. 12.6s
                  ⚠ web_search: 5 of 14 fetched URLs returned content
  [ 72] MISS 14/20  [token]  Strip EN 1652-Cu-DHP-R220-2.0x100              -> Galvanized Copper | 99.6% Copper 0. 8.8s
                  ⚠ web_search: 4 of 14 fetched URLs returned content
  [ 73] MISS 17/20  [token]  Cu + AgNi                                      -> Galvanized Copper | 99.6% Copper 0. 7.4s
  [ 74] MISS 11/20  [token]  Strip Berylco 07 HT R770-0,4x35/stamping       -> Galvanized Copper | 99.6% Copper 0. 11.3s
                  ⚠ web_search: 0 of 14 fetched URLs returned content (1 error, 13 filtered)
  [ 75] MISS 3/17  [token]  PA66 Ultramid A3SK/injection moulding          -> Polyamide (Nylon) 6.6/EU-27 6.0s

2026-03-13 15:51:11 INFO     [api.services.campaign.feedback_cycle] Patience exhausted after 2 stalls at round 1

  ┌─ C5/5 ──────────────────────────────────── 13.3% [3.7%-37.9%] ─┐
  │  Increase raw_content_limit to allow more c...  pp=[raw_content_limit]│
  │  2/15 hits  composite=0.1200  ⚠ 9/15 degraded  vs baseline: -6.7%│
  │  best so far: C2 13.3%                                         │
  └────────────────────────────────────────────────────────────────┘
  ┌─ SCOREBOARD ───────────────────────────────────────────────────────────────┐
  │  #   Label    Accuracy            95% CI  Composite    Delta               │
  │  1   C2         13.3%       [3.7%-37.9%]     0.1200     -6.7%  *           │
  │  2   C5         13.3%       [3.7%-37.9%]     0.1200     -6.7%              │
  │  3   C3          6.7%       [1.2%-29.8%]     0.0600    -13.3%              │
  │  4   C1          0.0%       [0.0%-20.4%]     0.0000    -20.0%              │
  │  5   C4          0.0%       [0.0%-20.4%]     0.0000    -20.0%              │
  └────────────────────────────────────────────────────────────────────────────┘
  ⚠ NO IMPROVEMENT  best candidate 20.0%  ->  patience 2/2

├─ Round 2 complete ─────────────────────────────────────────────────┤

Round    Accuracy  Composite   Rolling Avg    Trend
  search    10.0%    0.1000        10.0%  -
  1        20.0%    0.1800        15.0%  +10.0%
  2        20.0%    0.2000        16.7%  +0.0%  <-- plateau
  3        20.0%    0.2000        17.5%  +0.0%  <-- plateau
  -- Plateau: rolling avg stable at 20.0% for 3 rounds
  hits: 3/15  |  evaluated: 5 candidates
  ⚠ No improvement (2/2 patience)
  Stopping: patience exhausted (2 consecutive stalls)

╔════════════════════════════════════════════════════════════════════╗
║  OPTIMIZATION COMPLETE                                             ║
╠════════════════════════════════════════════════════════════════════╣
║  Rounds       2              Best         20.0% (round 1)          ║
║  Stop reason  patience_exhausted                                   ║
║  Cycle ID     cycle_68e2c53845c3                                   ║
║  Langfuse     effecc94b003c45501262d24df088241                     ║
╚════════════════════════════════════════════════════════════════════╝

In [ ]:
#@title Run optimization round (manual)
round_entry = await run_manual_round(
    campaign_rounds, eval_data, campaign_config, svc,
)

## 5. Results

In [ ]:
#@title Campaign comparison table
show_campaign_summary(campaign_rounds)

In [ ]:
#@title Per-query flip tracking (baseline vs final)
show_flip_tracking(campaign_rounds)

In [ ]:
#@title PromptState lineage chain
show_lineage_chain(campaign_rounds)

In [ ]:
#@title Save winner
save_campaign_winner(campaign_rounds, campaign_config, svc["store"], svc["backend_id"])

In [ ]:
#@title Generate LLM suggestions for next round
llm_client, llm_model = setup_llm(campaign_config)
suggestions = await generate_suggestions(
    campaign_rounds, eval_data, campaign_config,
    llm_client, model=llm_model,
)
display_suggestions(suggestions, len(campaign_rounds))
print("--- SUGGESTED CONFIG (copy to Setup) ---")
print(json.dumps(suggestions.get("suggested_config", campaign_config), indent=2))

In [ ]:
#@title Sync evaluation history to Langfuse
# Safe to re-run — already-pushed runs are skipped automatically.
stats = sync_langfuse(
    svc["store"], svc["backend_id"],
    dataset_name="termnorm_ground_truth",
)