# Optimization Campaign (HITL)

**Prerequisites:** TermNorm backend at `http://127.0.0.1:8000` | Groq API key in `.env` | Restart kernel after first sync

**Workflow:** Setup → Data → Explore → Optimize → Results

In [ ]:
%load_ext autoreload
%autoreload 2

from campaign_lib import *

# --- Services ---
svc = await init_services()
TASK_DESCRIPTION = load_task_description(
    r"C:\Users\dsacc\OfficeAddinApps\TermNorm-excel\backend-api\config\LCA_INPUT_PATTERNS.md"
)

# --- Campaign config ---
# ALL experiment knobs live here — no hidden defaults in service code.
campaign_config = {
    "sample_size": 15,              # queries per eval step (0 = all)
    "exploration_sample_size": 10,  # queries per scan/grid point (can be smaller)
    "exploration_rate": 0.5,        # PRIMARY KNOB: 0.0=conservative, 1.0=aggressive
    "exclude_nodes": ["llm_ranking"],    # nodes to skip (e.g. ["entity_profiling"])
    # --- Backend node overrides ---
    # Override values from GET /pipeline. Flat names resolved via schema override_map.
    # See show_pipeline_snapshot() output for available params per node.
    "pipeline_overrides": {
        "ranking_model": "openai/gpt-oss-120b",     # llm_ranking LLM model
        "profiling_model": "openai/gpt-oss-120b",   # entity_profiling LLM model
        "profiling_max_tokens": 4000,             # entity_profiling max output tokens
    },
    "optimization": {
        # --- Core loop ---
        "patience": 2,                   # consecutive non-improvements before stop/escalate
        "max_rounds": None,              # None = unlimited
        "n_variants": 5,                 # candidates per round
        "creativity": 0.7,               # temperature for candidate generation
        "improvement_threshold": 0.01,   # accuracy delta to count as improvement
        "seed": 42,                      # subsampling seed (reproducibility)
        "max_failures": 15,              # failure examples fed to LLM candidate generation
        # --- Escalation ---
        "degradation_threshold": 0.4,    # fraction of degraded queries to trigger escalation
        "backend_warning_threshold": 2,  # degradation resets before backend advisory
        "enable_l2": True,               # L2 refine_context on escalation
        "enable_l3": True,               # L3 modify_plan on L2 stall
        "l2_patience": 2,               # L2 stalls before L3
        "l3_patience": 1,               # L3 stalls before stop
        "l2_temperature": 0.3,           # LLM temperature for L2 transitions
        "l3_temperature": 0.5,           # LLM temperature for L3 transitions
        # --- Critique ---
        "enable_critique": True,         # critique agent between generate/evaluate
    },
    "eval_llm": {
        # "model":       "moonshotai/kimi-k2-instruct-0905",  # 10x more expensive
        "model":       "openai/gpt-oss-120b",
        "provider":    "groq",
        "temperature": 0.4,
        # --- Anthropic (cost: opus >> sonnet >> haiku) ---
        # "model": "claude-opus-4-6",
        # "model": "claude-sonnet-4-6",
        # "model": "claude-haiku-4-5-20251001",
        "max_tokens": 2000,
    },
    "pipeline_params": None        # set by configure_pipeline()
}

# --- Pipeline snapshot & params ---
pipeline_config_full = await show_pipeline_snapshot(svc)
pipeline_params = configure_pipeline(svc, campaign_config)

In [2]:
#@title Load data & evaluation context
RUN_BASELINE = False

train_data, session_terms = prepare_datasets(
    svc["store"], svc["backend_id"],
    excel_path=r"C:\Users\dsacc\Desktop\project-TermNorm\OneDrive_2025-07-02\Austausch Beispiele\Prozessnamen\BOM-example.xlsx",
)
svc["session_terms"] = session_terms

baseline_ps, eval_data, campaign_rounds, baseline_results = await prepare_eval_context(
    svc, train_data, campaign_config, run_baseline=RUN_BASELINE,
)

==================================================
  Train              : 984 queries
  Test (processes)   : 82 queries
  Test (material)    : 165 queries
  ------------------------------------------------
  Combined queries   : 820 (deduplicated)
  Session identifiers: 94 unique targets
==================================================

Evaluation data: 984 queries

In [3]:
#@title Experiment dashboard
EXPERIMENT_ID = None  # Set to hex ID to resume (e.g. '68e2c5')

pipeline_params = show_experiment_dashboard(
    svc=svc, experiment_id=EXPERIMENT_ID,
    campaign_config=campaign_config, eval_data=eval_data,
    baseline_prompt_fields=campaign_rounds[0]["prompt_fields"].model_dump() if campaign_rounds else None,
)

========================================================================
  EXPERIMENT DASHBOARD (termnorm-local)
========================================================================
  Dataset runs: 111 total (2 77e7e77777e7, 1 be8c4d8229f6, 1 dbb05e948b53, 107 other)
  Best result: 66.7% (scan)

  Campaigns (most recent first):
    cycle_be8c4d8229f6  interrupted  0 rounds  best=33.3%  base=33.3%
      patience=2  rounds=None  sample=15  model=openai/gpt-oss-120b

    cycle_dbb05e948b53  interrupted  0 rounds  best=33.3%  base=33.3%
      patience=2  rounds=None  sample=15  model=moonshotai/kimi-k2-instruct-09

========================================================================
  Set experiment_id="<short_id>" to see full config and diff
  Active: cycle_13e908d28487

## 3. Explore

Exploration via **Smart Search** (scan advisor + sensitivity scan).

In [4]:
#@title Task context + scan advisor
ADVISOR_MODEL = "openai/gpt-oss-120b"  # model for scan advisor LLM call

task_context = await decompose_task_context(TASK_DESCRIPTION, campaign_config, svc)

# preview_advisor_prompt(campaign_config, svc, task_description=task_context, raw=True)
advisory, scan_variants, schema_labels = await run_scan_advisor(
    campaign_config, svc,
    task_description=task_context,
    model=ADVISOR_MODEL,
)

TASK CONTEXT DECOMPOSITION
--------------------------------------------------
  domain: Life Cycle Assessment (LCA) terminology normalization
  pipeline_purpose: Normalize user‑provided material, process, and geographic descriptors to exact entries in LCA databases (e.g., ecoinvent, GaBi) and flag inputs with no viable match.
  data_characteristics: Free‑form textual inputs containing industrial codes, standards, brand/trade names, chemical shorthand, agricultural qualifiers, geographic tags; mixed German/French/English; includes units and quantities; high variability and low volume per query.
  optimization_goals: Improve profile schema quality and web‑search relevance; increase matching accuracy (precision/recall) across synonyms, standards, and geographic variants; reduce false positives; correctly identify no‑match cases.
  key_challenges: Structural mismatch between unstructured shorthand and rigid database naming; need for domain knowledge to decode brands, standards, and alloy codes; synonym drift and naming evolution; handling geographic variants; detecting no‑match inputs; decomposing compositional blends; multilingual and mixed‑format inputs.
  Consultation: Focus first on enriching the schema with explicit fields for codes, standards, brand mappings, and geographic tags; this will give the optimizer concrete anchors for matching and improve web‑search relevance. Augment the knowledge base with a curated lookup table linking brand names and alloy designations to their canonical LCA identifiers, and integrate a synonym/translation layer for multilingual terms. Implement a two‑stage matcher: a high‑precision rule‑based filter using the enriched schema, followed by a fuzzy‑search fallback that leverages web search results to surface missing entries. Finally, add a confidence‑scoring mechanism that flags low‑confidence or unmapped inputs so the pipeline can safely return “no match” instead of forcing a poor match.
SCAN ADVISOR -- pipeline-aware sensitivity setup
--------------------------------------------------
  Pipeline: termnorm (v1.1)
  Steps: ['cache_lookup', 'fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching', 'llm_ranking']
  Excluded: ['llm_ranking']
  Task context: Life Cycle Assessment (LCA) terminology normalization — Normalize user‑provided material, process, and geographic de
  Calling openai/gpt-oss-120b ...

2026-03-26 10:05:36 WARNING  [api.services.search.scan_advisor] Scan advisor response truncated (finish_reason=length, max_tokens=2000). Increase max_tokens in eval_llm config.

PRIORITY AXES (ranked by importance)
----------------------------------------
  1. [HIGH] fuzzy_threshold (pipeline_param) -- step: fuzzy_matching
     Controls match strictness for shorthand terms
     Values: ['0.7', '0.85']
  2. [MEDIUM] fuzzy_scorer (pipeline_param) -- step: fuzzy_matching
     Different algorithms affect synonym detection
     Values: ['ratio', 'partial_ratio']
  3. [HIGH] query_prefix (pipeline_param) -- step: web_search
     Guides search toward LCA‑relevant sources
     Values: ['LCA material', 'ecoinvent term']
  4. [MEDIUM] query_suffix (pipeline_param) -- step: web_search
     Adds domain context to results
     Values: ['ecoinvent database', 'life cycle assessment']
  5. [MEDIUM] content_char_limit (pipeline_param) -- step: web_search
     More characters capture richer specifications
     Values: ['1200', '2000']
  6. [MEDIUM] max_sites (pipeline_param) -- step: web_search
     Broader site pool improves coverage
     Values: ['10', '15']
  7. [HIGH] profiling_schema (pipeline_param) -- step: entity_profiling
     Adds fields for no‑match detection and confidence
     Values: [[['+', '/no_match_flag', 'boolean', True, 'Indicates no viable database entry']], [['+', '/confidence_score', 'number', False, 'Match confidence 0-1']]]
  8. [MEDIUM] max_token_candidates (pipeline_param) -- step: token_matching
     More candidates increase recall for blended inputs
     Values: ['30', '40']
  9. [MEDIUM] profiling_prompt (pipeline_param) -- step: entity_profiling
     Prompt tone influences extraction detail
     Values: ['Include concise bullet list', 'Use formal technical tone']
  10. [HIGH] persona (prompt_field)
     Sets expert LCA analyst perspective
  11. [MEDIUM] thinking_style (prompt_field)
     Guides systematic decomposition of inputs
  12. [LOW] problem_description (prompt_field)
     Provides context but low impact on matching
  13. [LOW] task_intent (prompt_field)
     Clarifies goal, minor effect
  Suggested n_diagnostic: 6

--- PROPOSED SCAN VARIANTS (copy-paste into next cell) ---
scan_variants = {
    'fuzzy_threshold': ['0.7', '0.85'],
    'fuzzy_scorer': ['ratio', 'partial_ratio'],
    'query_prefix': ['LCA material', 'ecoinvent term'],
    'query_suffix': ['ecoinvent database', 'life cycle assessment'],
    'content_char_limit': ['1200', '2000'],
    'max_sites': ['10', '15'],
    'profiling_schema': [
        [['+', '/no_match_flag', 'boolean', True, 'Indicates no viable database entry']],
        [['+', '/confidence_score', 'number', False, 'Match confidence 0-1']],
    ],
    'max_token_candidates': ['30', '40'],
    'profiling_prompt': ['Include concise bullet list', 'Use formal technical tone'],
}

scan_sample_size = 10  # queries per variant (advisor recommendation)

In [5]:
#@title Scan variant config (edit suggested values or add your own)
# Schema axes: mutation tuples ("-", path), ("+", path, type, req, desc),
# ("~", old, new, type, req, desc). Non-schema axes: plain value lists.

scan_sample_size = 3  # queries per scan variant (0 = use all)

scan_variants = {
    # ── Token matching ───────────────────────────────────────────────────
    'max_token_candidates': [10, 30, 50],
    # ── Web search: query framing ────────────────────────────────────────
    'query_prefix': [
        # --- Database-oriented ---
        'ecoinvent', 'GaBi', 'ecoinvent LCA database material name',
        'material composition LCA', # 'ecoinvent equivalent', 'ecoinvent match for', 'identify LCA material for',
        'what is',# 'define', 'identify', 'describe material',
        # 'chemical composition of', 'CAS number', 'IUPAC name for',
        'technical data sheet', 'product specification', # 'manufacturer datasheet', 'material safety data sheet',
        'manufactured from', 'production process for', # 'raw material for',
        # --- Synonym / translation ---
        # 'also known as', # 'synonym for', 'equivalent material', 'alternative name for',
        # 'wikipedia', # 'material properties of',
    ],
    # ── Web search: volume knobs ─────────────────────────────────────────
    'max_sites': [3, 7, 12],
    'num_results': [5, 20, 40],
    'content_char_limit': [400, 800, 1500],
    # ── Fuzzy matching ───────────────────────────────────────────────────
    # 'fuzzy_threshold': [50, 70, 90],
    # 'fuzzy_scorer': ['ratio', 'WRatio', 'token_set_ratio'],
    # ── Entity profiling: LLM tuning ─────────────────────────────────────
    'profiling_temperature': [0.0, 0.3, 0.7],
    'raw_content_limit': [1000, 2500, 8000],
    # ── Prompt fields ────────────────────────────────────────────────────
    'thinking_style': [
          'Think step-by-step: isolate distinguishing features → compare each candidate → assign scores.',
          'Consider the most likely interpretation first, then check alternatives.',       
          'Reason by elimination: discard obviously wrong candidates, then rank the rest.',
      ],
    # ── Entity profiling: schema mutations ───────────────────────────────
    'profiling_schema': [
        # --- LCA-database-specific (original) ---
        [['+', 'geography_scope', 'array', False, 'Relevant ecoinvent/SimaPro geography codes inferred from context, e.g. GLO, RER, CH, RNA'],
         ['+', 'database_format_hint', 'string', False, "Best-guess ecoinvent-style name fragment for this entity, e.g. 'market for polyethylene, high density'"]],
        [['+', 'lca_database_names', 'array', True, "Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'"]],
        [['-', 'manufacturing_processes'], ['-', 'applications'],
         ['+', 'lca_database_names', 'array', True, 'Likely ecoinvent or GaBi database entry names for this entity using standard LCA naming conventions']],
        # [['~', 'notes', 'material_category', 'string', True, "The broad LCA material category this entity belongs to, e.g. 'polyethylene', 'brass', 'steel'"]],
        [['-', 'applications'], ['+', 'ecoinvent_candidate_names', 'array', True, 'Exact ecoinvent activity names this entity most likely maps to']],
        [['-', 'manufacturing_processes'], ['+', 'database_search_tokens', 'array', True, 'Optimized search tokens for LCA database lookup including spelling variants']],
        # [['~', 'classification_aliases', 'classification_aliases', 'array', True, 'All valid ecoinvent/GaBi naming variants including geography codes and system model suffixes']],
        # --- Minimalist: strip to core matching signals ---
        [['-', 'applications'], ['-', 'manufacturing_processes'], ['-', 'notes'], ['-', 'technical_specifications']],
        # --- Chemical identity ---
        [['+', 'cas_number', 'string', False, 'CAS registry number if identifiable from context'],
         ['+', 'chemical_formula', 'string', False, 'Chemical formula or molecular structure notation']],
        # --- Trade name decoding ---
        [['~', 'key_properties', 'trade_names', 'array', True, 'Known commercial/trade names and brand names for this material, e.g. Makrolon=polycarbonate, Delrin=POM']],
        # --- Material hierarchy (specific→generic) ---
        [['+', 'material_hierarchy', 'array', False, 'Classification chain from specific to generic, e.g. [Makrolon 2805, polycarbonate, thermoplastic, polymer]']],
        # --- Process-centric (flip perspective from material to process) ---
        [['~', 'applications', 'production_route', 'string', False, 'Primary production/manufacturing route e.g. injection molding, extrusion, casting'],
         ['~', 'notes', 'form_factor', 'string', False, 'Physical form: granulate, sheet, rod, wire, powder, liquid, film']],
        # --- Standards-focused ---
        [['+', 'applicable_standards', 'array', False, 'DIN/ISO/EN/ASTM standards that reference or define this material'],
         ['-', 'applications']],
        # # --- Geography-aware ---
        # [['+', 'supply_chain_geography', 'string', False, 'Most likely geographic origin or market region for this material']],
        # # --- Confidence / ambiguity signal ---
        # [['+', 'confidence_level', 'string', False, 'How confident the model is in the identification: high/medium/low/ambiguous'],
        #  ['+', 'ambiguity_notes', 'string', False, 'What makes this input hard to identify — abbreviation, trade name, multi-material, etc.']],
        # # --- Spelling / language variant boost ---
        # [['+', 'spelling_variants', 'array', False, 'All known spelling variants across EN/DE/FR, e.g. aluminium/aluminum, polyamid/polyamide'],
        #  ['-', 'notes']],
        # --- Werkstoff / alloy code decoding ---
        [['+', 'material_code_decoded', 'string', False, 'Decoded meaning of any material code, Werkstoff number, or alloy designation present in the input'],
         ['+', 'base_material', 'string', False, 'The fundamental base material, e.g. brass, steel, polycarbonate']],
        # --- Functional equivalence ---
        [['~', 'applications', 'functional_unit', 'string', False, 'The functional unit this material serves, e.g. structural plastic, electrical insulation, food-grade packaging'],
         ['+', 'substitutes', 'array', False, 'Materials that could serve the same functional role']],
    ],
}
scan_variants, schema_labels = resolve_scan_variants(scan_variants, svc=svc)

  max_token_candidates: [10, 30, 50]
  query_prefix: ['ecoinvent', 'GaBi', 'ecoinvent LCA database material name', 'material composition LCA', 'what is', 'technical data sheet', 'product specification', 'manufactured from', 'production process for']
  max_sites: [3, 7, 12]
  num_results: [5, 20, 40]
  content_char_limit: [400, 800, 1500]
  profiling_temperature: [0.0, 0.3, 0.7]
  raw_content_limit: [1000, 2500, 8000]
  thinking_style: ['Think step-by-step: isolate distinguishing features → compare each candidate → assign scores.', 'Consider the most likely interpretation first, then check alternatives.', 'Reason by elimination: discard obviously wrong candidates, then rank the rest.']
  profiling_schema: (baseline + 13 mutations)
    [0] (baseline)
    [1] ('+', 'geography_scope', 'array', False, 'Relevant ecoinvent/SimaPro geography codes inferred from context, e.g. GLO, RER, CH, RNA'), ('+', 'database_format_hint', 'string', False, 'Best-guess ecoinvent-style name fragment for this entity, e.g. 'market for polyethylene, high density'')
    [2] ('+', 'lca_database_names', 'array', True, 'Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'')
    [3] ('-', 'manufacturing_processes'), ('-', 'applications'), ('+', 'lca_database_names', 'array', True, 'Likely ecoinvent or GaBi database entry names for this entity using standard LCA naming conventions')
    [4] ('-', 'applications'), ('+', 'ecoinvent_candidate_names', 'array', True, 'Exact ecoinvent activity names this entity most likely maps to')
    [5] ('-', 'manufacturing_processes'), ('+', 'database_search_tokens', 'array', True, 'Optimized search tokens for LCA database lookup including spelling variants')
    [6] ('-', 'applications'), ('-', 'manufacturing_processes'), ('-', 'notes'), ('-', 'technical_specifications')
    [7] ('+', 'cas_number', 'string', False, 'CAS registry number if identifiable from context'), ('+', 'chemical_formula', 'string', False, 'Chemical formula or molecular structure notation')
    [8] ('~', 'key_properties', 'trade_names', 'array', True, 'Known commercial/trade names and brand names for this material, e.g. Makrolon=polycarbonate, Delrin=POM')
    [9] ('+', 'material_hierarchy', 'array', False, 'Classification chain from specific to generic, e.g. [Makrolon 2805, polycarbonate, thermoplastic, polymer]')
    [10] ('~', 'applications', 'production_route', 'string', False, 'Primary production/manufacturing route e.g. injection molding, extrusion, casting'), ('~', 'notes', 'form_factor', 'string', False, 'Physical form: granulate, sheet, rod, wire, powder, liquid, film')
    [11] ('+', 'applicable_standards', 'array', False, 'DIN/ISO/EN/ASTM standards that reference or define this material'), ('-', 'applications')
    [12] ('+', 'material_code_decoded', 'string', False, 'Decoded meaning of any material code, Werkstoff number, or alloy designation present in the input'), ('+', 'base_material', 'string', False, 'The fundamental base material, e.g. brass, steel, polycarbonate')
    [13] ('~', 'applications', 'functional_unit', 'string', False, 'The functional unit this material serves, e.g. structural plastic, electrical insulation, food-grade packaging'), ('+', 'substitutes', 'array', False, 'Materials that could serve the same functional role')

In [6]:
#@title Run sensitivity scan
scan_baseline_sp, scan_df, axis_profiles = await run_sensitivity_scan(
    baseline_ps, campaign_config, scan_variants, eval_data,
    scan_sample_size=scan_sample_size,
    svc=svc, experiment_id=EXPERIMENT_ID or "",
)

Active steps: cache_lookup, fuzzy_matching, web_search, entity_profiling, token_matching  Excluded: llm_ranking
  Restructured baseline fields (cached):
    persona: You are a candidate evaluation expert.
    task_intent: Rank 20 entity-name candidates by how well they match a target profile and its c...
    problem_description: Given a JSON entity profile and a core concept, score and rank candidate names o...
    instruction: 1) Extract the entity_category and key distinguishing features from the profile....
    thinking_style: Think step-by-step: isolate distinguishing features → compare each candidate → a...
    answer_format: Valid JSON only: { "reasoning": "...", "ranked_candidates": [ { "rank": 1, "cand...
  Search baseline: b730ac2e9e41 (render: 868 chars)
  Historical data: 49 results across 8 unique prompts
  Matching runs (sp_hash): 31, 3 cached results
  Scan variant coverage (31 matching runs):
    max_token_candidates     10→3 ✓  30→3 ✓  50→3 ✓
    query_prefix             9/9 values tested
      ecoinvent            →3 ✓
      GaBi                 →3 ✓
      [a]                  →3 ✓
      [b]                  →3 ✓
      what is              →3 ✓
      [c]                  →3 ✓
      [d]                  →3 ✓
      [e]                  →3 ✓
      [f]                  →3 ✓
    max_sites                3→3 ✓  7→3 ✓  12→3 ✓
    num_results              5→3 ✓  20→3 ✓  40→3 ✓
    content_char_limit       400→3 ✓  800→3 ✓  1500→3 ✓
    profiling_temperature    0.0→3 ✓  0.3→3 ✓  0.7→3 ✓
    raw_content_limit        1000→3 ✓  2500→3 ✓  8000→3 ✓
    thinking_style           3/3 values tested
      [g]                  →3 ✓
      [h]                  →3 ✓
      [i]                  →3 ✓
    profiling_schema         (not tested)
  Values:
    [a] ecoinvent LCA database material name
    [b] material composition LCA
    [c] technical data sheet
    [d] product specification
    [e] manufactured from
    [f] production process for
    [g] Think step-by-step: isolate distinguishing features → compare each candidate → assign scores.
    [h] Consider the most likely interpretation first, then check alternatives.
    [i] Reason by elimination: discard obviously wrong candidates, then rank the rest.
Running sensitivity scan...
  Baseline field values:
    persona: You are a candidate evaluation expert.
    task_intent: Rank 20 entity-name candidates by how well they match a target profile and its c...
    problem_description: Given a JSON entity profile and a core concept, score and rank candidate names o...
    instruction: 1) Extract the entity_category and key distinguishing features from the profile....
    thinking_style: Think step-by-step: isolate distinguishing features → compare each candidate → a...
    answer_format: Valid JSON only: { "reasoning": "...", "ranked_candidates": [ { "rank": 1, "cand...

  Axes: 9, variants: 44, queries/variant: 3, cached results: 363
  Estimated calls: ~132
  Evaluating baseline...
 14.3s HIT   [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75
 13.6s MISS 3/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER
 22.4s MISS 3/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 6 of 20 fetched URLs returned content (14 filtered: 13×too_short, 1×http_403)
  Baseline: 1/3 (33.3%) [cached]

======================================================================
  Axis 1/9: max_token_candidates (pipeline_param, 3 values)
======================================================================
 13.4s HIT   [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75
 17.1s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
 12.2s MISS 7/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [0] 10                                         1/3  33.3%  +0.0% [cached]
 14.1s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
 11.0s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
 11.5s MISS 6/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [1] 30                                         0/3  0.0%  -30.0% v [cached]
 12.1s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
 11.0s HIT   [token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
 11.8s MISS 8/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [2] 50                                         1/3  33.3%  +0.0% [cached]

======================================================================
  Axis 2/9: query_prefix (pipeline_param, 9 values)
======================================================================
  9.9s HIT   [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75
 11.8s MISS 3/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, copper {RER}| wire dr
 11.1s MISS 3/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [0] ecoinvent                                  1/3  33.3%  +0.0% [cached]
  9.0s HIT   [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75
  9.0s MISS 4/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER
 10.0s MISS 13/20  [token] 📖  SJRG0010-ABS/molding                           -> Glass fibre reinforced plastic | 50
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [1] GaBi                                       1/3  33.3%  +0.0% [cached]
  8.4s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
  7.2s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
 11.6s MISS 7/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [2] ecoinvent LCA database material name       0/3  0.0%  -30.0% v [cached]
 10.3s MISS 3/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
  8.1s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER
 12.3s MISS 4/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [3] material composition LCA                   0/3  0.0%  -30.0% v [cached]
  8.5s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
  8.1s MISS 3/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER
 18.3s MISS 6/20  [token] 📖  SJRG0010-ABS/molding                           -> Glass fibre reinforced plastic | 60
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [4] what is                                    0/3  0.0%  -30.0% v [cached]
  8.9s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
  8.2s HIT   [token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
 10.4s MISS --/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [5] technical data sheet                       1/3  33.3%  -1.7% v [cached]
  7.8s HIT   [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75
  6.4s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER
 18.6s MISS --/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (14 filtered: 13×too_short, 1×http_403; 2 errors)
  [6] product specification                      1/3  33.3%  -1.7% v [cached]
  8.4s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
  9.1s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
 11.2s MISS 2/20  [token] 📖  SJRG0010-ABS/molding                           -> Injection moulding {RoW}| injection
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [7] manufactured from                          0/3  0.0%  -30.0% v [cached]
  8.6s MISS 3/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
 10.5s MISS 3/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER
  8.0s MISS --/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [8] production process for                     0/3  0.0%  -31.7% v [cached]

======================================================================
  Axis 3/9: max_sites (pipeline_param, 3 values)
======================================================================
  8.0s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
  8.3s HIT   [token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
  9.3s MISS --/20  [token] 📖  SJRG0010-ABS/molding                           -> Polyethylene, low density, granulat
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [0] 3                                          1/3  33.3%  -1.7% v [cached]
  8.1s HIT   [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75
  8.5s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
  9.2s MISS 6/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [1] 7                                          1/3  33.3%  +0.0% [cached]
 10.1s HIT   [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75
  7.3s HIT   [token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
 12.6s MISS 2/20  [token] 📖  SJRG0010-ABS/molding                           -> Injection moulding {RoW}| injection
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [2] 12                                         2/3  66.7%  +30.0% ^ [cached]

======================================================================
  Axis 4/9: num_results (pipeline_param, 3 values)
======================================================================
  7.6s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
 11.1s MISS 4/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
  8.6s MISS 16/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [0] 5                                          0/3  0.0%  -30.0% v [cached]
  8.5s HIT   [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75
  9.7s MISS 5/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER
  9.0s MISS 4/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [1] 20                                         1/3  33.3%  +0.0% [cached]
  7.7s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
  6.9s HIT   [token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
 15.3s MISS 16/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [2] 40                                         1/3  33.3%  +0.0% [cached]

======================================================================
  Axis 5/9: content_char_limit (pipeline_param, 3 values)
======================================================================
  9.2s HIT   [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75
  7.7s HIT   [token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
  8.6s MISS 17/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [0] 400                                        2/3  66.7%  +30.0% ^ [cached]
  8.7s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
  6.8s HIT   [token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
 10.3s MISS 2/20  [token] 📖  SJRG0010-ABS/molding                           -> Injection moulding {RoW}| injection
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [1] 800                                        1/3  33.3%  +0.0% [cached]
  8.9s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
  8.6s HIT   [token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
 10.1s MISS 4/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [2] 1500                                       1/3  33.3%  +0.0% [cached]

======================================================================
  Axis 6/9: profiling_temperature (pipeline_param, 3 values)
======================================================================
  8.1s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
 13.1s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER
  9.3s MISS --/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [0] 0.0                                        0/3  0.0%  -31.7% v [cached]
  7.8s HIT   [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75
  7.0s HIT   [token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
  9.6s MISS 5/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [1] 0.3                                        2/3  66.7%  +30.0% ^ [cached]
 10.3s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
  7.7s HIT   [token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
 15.6s MISS 4/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [2] 0.7                                        1/3  33.3%  +0.0% [cached]

======================================================================
  Axis 7/9: raw_content_limit (pipeline_param, 3 values)
======================================================================
 16.5s MISS 2/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
 11.2s HIT   [token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
 10.6s MISS --/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 4 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403; 1 error)
  [0] 1000                                       1/3  33.3%  -1.7% v [cached]
 10.2s HIT   [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75
  7.0s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
 10.5s MISS --/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 5 of 20 fetched URLs returned content (15 filtered: 14×too_short, 1×http_403)
  [1] 2500                                       1/3  33.3%  -1.7% v [cached]
  9.9s MISS 4/4  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 50

In [7]:
#@title Scan analytics
difficulty_df = show_scan_analytics(scan_df, axis_profiles, svc)

VARIANT LEADERBOARD (all scan combos)
======================================================================

,rank,axis,variant,accuracy,delta,hits/total,errors
0,1,profiling_schema,schema(10 fields),66.7%,+30.0%,2/3,0
1,2,profiling_temperature,0.3,66.7%,+30.0%,2/3,0
2,3,content_char_limit,400,66.7%,+30.0%,2/3,0
3,4,max_sites,12,66.7%,+30.0%,2/3,0
4,5,profiling_schema,schema(11 fields),66.7%,+30.0%,2/3,0
5,6,profiling_schema,schema(11 fields),66.7%,+28.3%,2/3,0
6,7,num_results,20 (baseline),33.3%,-,1/3,0
7,8,num_results,40 (baseline),33.3%,-,1/3,0
8,9,max_token_candidates,10 (baseline),33.3%,-,1/3,0
9,10,max_token_candidates,50 (baseline),33.3%,-,1/3,0
10,11,query_prefix,ecoinvent (baseline),33.3%,-,1/3,0
11,12,query_prefix,GaBi (baseline),33.3%,-,1/3,0
12,13,profiling_temperature,0.7 (baseline),33.3%,-,1/3,0
13,14,profiling_schema,schema(13 fields) (baseline),33.3%,-,1/3,0
14,15,profiling_schema,schema(13 fields) (baseline),33.3%,-,1/3,0
15,16,profiling_schema,schema(11 fields) (baseline),33.3%,-,1/3,0
16,17,profiling_schema,schema(7 fields) (baseline),33.3%,-,1/3,0
17,18,content_char_limit,800 (baseline),33.3%,-,1/3,0
18,19,content_char_limit,1500 (baseline),33.3%,-,1/3,0
19,20,max_sites,7 (baseline),33.3%,-,1/3,0
20,21,raw_content_limit,1000,33.3%,-1.7%,1/3,0
21,22,raw_content_limit,2500,33.3%,-1.7%,1/3,0
22,23,max_sites,3,33.3%,-1.7%,1/3,0
23,24,query_prefix,product specification,33.3%,-1.7%,1/3,0
24,25,query_prefix,technical data sheet,33.3%,-1.7%,1/3,0
25,26,max_token_candidates,30,0.0%,-30.0%,0/3,0
26,27,query_prefix,ecoinvent LCA database material name,0.0%,-30.0%,0/3,0
27,28,query_prefix,what is,0.0%,-30.0%,0/3,0
28,29,profiling_schema,schema(11 fields),0.0%,-30.0%,0/3,0
29,30,query_prefix,manufactured from,0.0%,-30.0%,0/3,0
30,31,query_prefix,material composition LCA,0.0%,-30.0%,0/3,0
31,32,num_results,5,0.0%,-30.0%,0/3,0
32,33,thinking_style,Reason by elimination: discard obviously...,0.0%,-30.0%,0/3,0
33,34,thinking_style,Think step-by-step: isolate distinguishi...,0.0%,-30.0%,0/3,0
34,35,raw_content_limit,8000,0.0%,-30.0%,0/3,0
35,36,profiling_schema,schema(13 fields),0.0%,-30.0%,0/3,0
36,37,profiling_schema,schema(12 fields),0.0%,-30.0%,0/3,0
37,38,profiling_schema,schema(11 fields),0.0%,-30.0%,0/3,0
38,39,profiling_schema,schema(12 fields),0.0%,-30.0%,0/3,0
39,40,profiling_schema,schema(11 fields),0.0%,-30.0%,0/3,0
40,41,profiling_schema,schema(12 fields),0.0%,-30.0%,0/3,0
41,42,query_prefix,production process for,0.0%,-31.7%,0/3,0
42,43,profiling_temperature,0.0,0.0%,-31.7%,0/3,0
43,44,thinking_style,Consider the most likely interpretation ...,0.0%,-31.7%,0/3,0

PER-AXIS STATISTICS
======================================================================

,axis,type,variants,mean_acc,std_acc,best_acc,worst_acc,sensitivity,budget
0,max_token_candidates,pipeline_param,3,22.2%,19.2%,33.3%,0.0%,0.300,skip
1,query_prefix,pipeline_param,9,14.8%,17.6%,33.3%,0.0%,0.317,skip
2,max_sites,pipeline_param,3,44.4%,19.2%,66.7%,33.3%,0.317,skip
3,num_results,pipeline_param,3,22.2%,19.2%,33.3%,0.0%,0.300,skip
4,content_char_limit,pipeline_param,3,44.4%,19.2%,66.7%,33.3%,0.300,skip
5,profiling_temperature,pipeline_param,3,33.3%,33.3%,66.7%,0.0%,0.617,high
6,raw_content_limit,pipeline_param,3,22.2%,19.2%,33.3%,0.0%,0.283,skip
7,thinking_style,prompt_field,3,0.0%,0.0%,0.0%,0.0%,0.017,skip
8,profiling_schema,pipeline_param,14,23.8%,27.5%,66.7%,0.0%,0.600,high

QUERY DIFFICULTY (10 queries across 109 scan runs)
======================================================================
  easy: 0 (0%) | discriminating: 5 (50%) | hard: 5 (50%) | error: 0 (0%)

,query,ground_truth,hit_rate,hits/evals,error_rate,classification
0,Copper Wire/cold forming,"Metal working, average for copper product manu...",0.000000,0/4,0.0,hard
1,PC GF10 makrolon material/0,Injection moulding {RoW}| injection moulding |...,0.000000,0/4,0.0,hard
2,PA6/66 Ultramid C3U/molding,Injection moulding {RER}| injection moulding |...,0.000000,0/5,0.0,hard
3,PA 66 25% GF V0 RAL 7012/0,Injection moulding {RoW}| injection moulding |...,0.000000,0/5,0.0,hard
4,EN 10270-3-1.4568\nX7CrNi17-7 (DIN17224 4.4568...,"Sheet rolling, chromium steel {RER}| sheet rol...",0.000000,0/4,0.0,hard
5,SJRG0010-ABS/molding,Injection moulding {RER}| injection moulding |...,0.038095,4/105,0.0,discriminating
6,Kingfa NPG25,Glass fibre reinforced plastic | 75% PA66 25% ...,0.200000,1/5,0.0,discriminating
7,SJRG0013-PA/molding,Injection moulding {RER}| injection moulding |...,0.333333,1/3,0.0,discriminating
8,PA66-GF25 ULTRAMID A3UG5 RAL7035 grey,Glass fibre reinforced plastic | 75% PA66 25% ...,0.431193,47/109,0.0,discriminating
9,Stainless steel EN 10270-3/winding,"Wire drawing, steel {RER}| wire drawing, steel...",0.485714,51/105,0.0,discriminating

In [8]:
#@title Select scan winner & seed campaign
best_sp = seed_campaign_from_scan(
    scan_df, axis_profiles, scan_baseline_sp, scan_variants,
    campaign_rounds, campaign_config,
)

Selected best from 2 improving axes:
  profiling_temperature     best_delta=+30.0%  value_idx=1  acc=66.7%
  profiling_schema          best_delta=+30.0%  value_idx=0  acc=66.7%

Composed winner: sp_hash=93ae5e9f7885
Updated pipeline_params: {'steps': ['cache_lookup', 'fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching'], 'llm_ranking': '<1 fields>', 'profiling_temperature': 0.3, 'profiling_schema': '<11 fields>'}

Round    Accuracy   Rolling Avg    Trend
  search    33.3%        33.3%  -

## 4. Optimize

Two modes: **Semi-automatic** (feedback cycle with patience-based auto-stop) or **Manual** (one round at a time).

In [9]:
#@title Feedback cycle preflight
scan_context = show_feedback_preflight(
    campaign_rounds, eval_data, campaign_config,
    pipeline_params=pipeline_params,
    scan_df=scan_df,
    axis_profiles=axis_profiles,
    scan_variants=scan_variants,
    difficulty_df=locals().get("difficulty_df"),
)

======================================================================
  FEEDBACK CYCLE PRE-FLIGHT
======================================================================
  Baseline accuracy      : 33.3%
  Baseline prompt        : You are a candidate evaluation expert.

Rank 20 entity-name candidates by how we...
  ------------------------------------------------------------------
  Max rounds             : unlimited
  Candidates per round   : 5
  Queries per eval       : 15 of 984
  Improvement threshold  : 1.0%
  Patience (L1)          : 2 rounds
  L2 (refine context)    : enabled, patience=2
  L3 (modify plan)       : enabled, patience=1
  ------------------------------------------------------------------
  Candidate model        : openai/gpt-oss-120b
  Creativity             : 0.7
  Pipeline               : (default pipeline)
    Excluded             : llm_ranking
  Strategy               : SCAN-AWARE

  ROUND PIPELINE (what happens each round)
  ------------------------------------------------------------------
  1. BASELINE INPUT
     Prompt: You are a candidate evaluation expert.

Rank 20 entity-name candidates by how we...
     Accuracy: 33.3%  |  Prior results: 0
  2. FAILURE ANALYSIS
     Up to 15 failures extracted (currently 0 available)
  3. CONTEXT ASSEMBLY
     Strategy: SCAN-AWARE
     Scan leaderboard: 44 entries
     Top performer: profiling_schema         schema(10 fields)                        acc=66.7%  delta=+30.0%  hits=2/3
     Sensitivity axes: 9
     Difficulty: Query classes: easy: 0 (0%) | discriminating: 5 (50%) | hard: 5 (50%) | error: 0 (0%)
     Improving axes: 2 (profiling_temperature, profiling_schema)
     Tested values: 2 axes with per-value data
  4. LLM CANDIDATE GENERATION
     Model: openai/gpt-oss-120b  |  Temperature: 0.7
     Candidates: 5
     Output: prompt + pipeline_params_override per candidate
  5. BACKEND EVALUATION
     Queries per candidate: 15 of 984
     Scoring: accuracy
  6. WINNER SELECTION
     Criterion: best accuracy >= baseline + 1.0%
  7. LOOP CONTROL
     Patience: 2 stalls → stop  |  L2: enabled, patience=2  |  L3: enabled, patience=1
  ------------------------------------------------------------------
  Est. backend calls     : unlimited  (no max_rounds x 5c x 15q)

  SCAN CONTEXT PREVIEW (injected into LLM meta-prompt)
  ------------------------------------------------------------------
  Leaderboard:
  profiling_schema         schema(10 fields)                        acc=66.7%  delta=+30.0%  hits=2/3
    profiling_temperature    0.3                                      acc=66.7%  delta=+30.0%  hits=2/3
    content_char_limit       400                                      acc=66.7%  delta=+30.0%  hits=2/3
    max_sites                12                                       acc=66.7%  delta=+30.0%  hits=2/3
    profiling_schema         schema(11 fields)                        acc=66.7%  delta=+30.0%  hits=2/3
    profiling_schema         schema(11 fields)                        acc=66.7%  delta=+28.3%  hits=2/3
    num_results              20                                       acc=33.3%  delta=+0.0%  hits=1/3 (baseline)
    num_results              40                                       acc=33.3%  delta=+0.0%  hits=1/3 (baseline)
    max_token_candidates     10                                       acc=33.3%  delta=+0.0%  hits=1/3 (baseline)
    max_token_candidates     50                                       acc=33.3%  delta=+0.0%  hits=1/3 (baseline)
    ... 34 more
  Axis sensitivity:
  1. profiling_temperature    type=pipeline_param sensitivity=0.617  card=3  budget=high  [room: best_delta=+30.0%]
    2. profiling_schema         type=pipeline_param sensitivity=0.600  card=14  budget=high  [room: best_delta=+30.0%]
    3. query_prefix             type=pipeline_param sensitivity=0.317  card=9  budget=skip
    4. max_sites                type=pipeline_param sensitivity=0.317  card=3  budget=skip  [room: best_delta=+30.0%]
    5. max_token_candidates     type=pipeline_param sensitivity=0.300  card=3  budget=skip
    6. num_results              type=pipeline_param sensitivity=0.300  card=3  budget=skip
    7. content_char_limit       type=pipeline_param sensitivity=0.300  card=3  budget=skip  [room: best_delta=+30.0%]
    8. raw_content_limit        type=pipeline_param sensitivity=0.283  card=3  budget=skip
    9. thinking_style           type=prompt_field   sensitivity=0.017  card=3  budget=skip
  Query difficulty:
  Query classes: easy: 0 (0%) | discriminating: 5 (50%) | hard: 5 (50%) | error: 0 (0%)
  Improving axes: profiling_temperature, profiling_schema
  Tested values:
  profiling_temperature (3 values tested):
      [1] 0.3  acc=66.7%
      [2] 0.7  acc=33.3% *baseline*
      [0] 0.0  acc=0.0%
    profiling_schema (14 values tested):
      [0] schema(11 fields)  acc=66.7%
      [3] schema(10 fields)  acc=66.7%
      [8] schema(11 fields)  acc=66.7%
      [11] schema(11 fields)  acc=33.3% *baseline*
      [6] schema(7 fields)  acc=33.3% *baseline*
      [7] schema(13 fields)  acc=33.3% *baseline*
      [12] schema(13 fields)  acc=33.3% *baseline*
      [4] schema(11 fields)  acc=0.0%
      [2] schema(12 fields)  acc=0.0%
      [1] schema(13 fields)  acc=0.0%
    ... 4 more lines
======================================================================

In [10]:
#@title Run optimization (feedback cycle)
dev_reload()

campaign_rounds = await run_feedback_cycle_notebook(
    campaign_rounds, eval_data, campaign_config,
    svc=svc, pipeline_params=pipeline_params,
    scan_context=locals().get("scan_context"),
    experiment_id=EXPERIMENT_ID,
    task_context=task_context,
)

  Interrupt of cells can take up to 60 seconds!
  If a dialog pops up, click 'Cancel' and wait 20 seconds.

╔════════════════════════════════════════════════════════════════════╗
║  FEEDBACK CYCLE STARTING                                           ║
╠════════════════════════════════════════════════════════════════════╣
║  Baseline       33.3%                                              ║
║  Max rounds     999            Patience    2                       ║
║  Candidates     5                                                  ║

2026-03-26 10:05:39 INFO     [api.services.campaign.feedback_cycle] Using provided baseline (acc=0.333)
2026-03-26 10:05:39 INFO     [api.services.campaign.campaign_lifecycle] Cycle identity: cycle_be8c4d8229f6

║  Sample size    15 of 984                                          ║
║  Min detectable ±36.2% (α=0.05, 80% power)                         ║
║  Model          openai/gpt-oss-120b                                ║
║  L2 (refine)    enabled            L3 (plan)   enabled             ║
║  Scan context   YES                                                ║
║  Critique       enabled                                            ║
╚════════════════════════════════════════════════════════════════════╝

2026-03-26 10:05:41 INFO     [api.services.obs.observability_logger] Dataset 'termnorm_ground_truth': 728 items registered, 256 duplicates/empty skipped (from 984 input)
2026-03-26 10:05:41 WARNING  [api.services.obs.observability_logger] Skipping Langfuse cloud dataset registration for 984 items (rate-limit risk). Use the dedicated Langfuse sync cell instead.
2026-03-26 10:05:41 INFO     [api.services.campaign.campaign_lifecycle] Registered 728 dataset items for 'termnorm_ground_truth'
2026-03-26 10:05:41 INFO     [api.services.campaign.feedback_cycle] Feedback cycle round 0 (clean=0/999, acc=0.333, stall=0/2)
2026-03-26 10:05:41 INFO     [api.services.campaign.round_execution] Loaded 5 persisted candidates for round 0
2026-03-26 10:05:41 INFO     [api.services.prompt_eval] SP cache: 4 cached queries for 15 eval queries

  ✓ Initialized  cycle=cycle_be8c4d  samples=15  obs=ON
    Starting fresh (no prior rounds for this cycle)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ROUND 1/999                                               patience 0/2
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

├─ GENERATE ─────────────────────────────────────────────────────────────┤
│  Current best    33.3%
│  Prompt          You are a candidate evaluation expert.  Rank 20...
│  Candidates      5   Creativity: 0.7   Scan: YES   Critique: NO
│  Model           openai/gpt-oss-120b
│  Scan focus: 2 improving axes [profiling_temperature, profiling_schema]
│  Scan baseline: 33.3%
├────────────────────────────────────────────────────────────────────────┤
  ✓ 5 candidates generated (loaded from disk)
    C1: Lower profiling_temperature slightly below the ... [instruction]
    C2: Switch to a richer schema with 12 fields includ... [instruction]
    C3: Increase max_sites to allow more web‑search can... [instruction]
    C4: Raise content_char_limit to capture longer prod... [instruction]
    C5: Use a more domain‑specific query_prefix and inc... [instruction]

│  Settings diff (8 params, 7 SPs):
│                         Start   Parent  C1      C2      C3      C4      C5
│  ─── web_search ────────
│     content_char_limit  -       -       -       -       -       2000    -
│              max_sites  -       -       -       -       15      -       -
│           query_prefix  -       -       -       -       -       -       [a]
│  ─── entity_profiling ──
│       profiling_schema  -       -       -       [b]     -       -       -
│  profiling_temperature  -       -       0.2     -       -       -       -
│  ─── token_matching ────
│   max_token_candidates  -       -       -       -       -       -       25
│            llm_ranking  -       [c]     ·       ·       ·       ·       ·
│            temperature  -       0.4     ·       ·       ·       ·       ·
│
│  Values:
│    [a] material specification
│    [b] schema(12 fields, extended synonyms)
│    [c] {'prompt': 'You are a candidate evaluation expert.\n\nRank 20 entity-name candidates by how well they match a target profile and its core concept.\n\nGiven a JSON entity profile and a core concept, score and rank candidate names on semantic similarity to the profile’s distinguishing features and concept.\n\n1) Extract the entity_category and key distinguishing features from the profile. 2) Score each candidate 0-1 based on presence of those features and alignment with core_concept \'{{core_concept}}\'. 3) Return a JSON array of all 20 candidates ranked by descending relevance_score with brief rationales.\n\nThink step-by-step: isolate distinguishing features → compare each candidate → assign score → rank.\n\nValid JSON only: { "reasoning": "...", "ranked_candidates": [ { "rank": 1, "candidate": "...", "relevance_score": 0.95, "rationale": "..." }, ... ] } with exactly 20 entries.'}

├─ EVALUATE ───────────────────────────────────────── 5 × 15 = 75 calls ─┤
  [  1]   8.0s MISS 2/2    [llm] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
  [  2]  10.7s MISS 1/2    [llm] 📖  Stainless steel EN 10270-3/winding             -> Steel, zinc coated /RER
  [  3]  11.9s MISS 3/3    [llm] 📖  SJRG0010-ABS/molding                           -> Galvanized Copper | 99.6% Copper 0.
                    ⚠ web_search: 4 of 20 fetched URLs returned content (16 filtered: 15×too_short, 1×http_403)
  [  4]  11.6s MISS 2/3    [llm] 📖  Kingfa NPG25                                   -> Wire drawing, copper {RoW}| wire dr

2026-03-26 10:05:55 WARNING  [api.services.prompt_eval] backend_reranker_evaluate for PA 66 25% GF V0 RAL 7012/0: [SERVER] HTTP 500: Server error '500 Internal Server Error' for url 'http://127.0.0.1:8000/matches'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500 — Backend may be experiencing issues.

  [  5]       MISS           PA 66 25% GF V0 RAL 7012/0                     ERR: [SERVER] HTTP 500: Server error '500 Int

2026-03-26 10:05:55 WARNING  [api.services.prompt_eval] backend_reranker_evaluate failed for PA6/66 Ultramid C3U/molding:

  [  6]       MISS           PA6/66 Ultramid C3U/molding                    -> ERROR
  [  7]  10.4s MISS 11/3    [llm]  PC  GF10  makrolon material/0                  -> Ceramic tile {GLO}| market for cera
                  ⚠ web_search: 5 of 20 fetched URLs returned content (13 filtered: 4×skip_extension, 5×http_403, 3×http_429, 1×too_short; 2 errors)
  [  8]  13.4s MISS 5/5    [llm]  Copper Wire/cold forming                       -> Silver {GLO}| market for silver | C

2026-03-26 10:06:19 INFO     [api.services.prompt_eval] Graceful stop after query 8/15.
2026-03-26 10:06:19 INFO     [api.services.prompt_eval] Per-query reuse: 4/15 queries from prior runs
2026-03-26 10:06:19 INFO     [api.services.prompt_eval] Saved partial run (8/15 queries) for SP 33db05a7
2026-03-26 10:06:19 WARNING  [api.services.campaign.feedback_cycle] Feedback cycle interrupted at round 0. Completed rounds are checkpointed.

╔════════════════════════════════════════════════════════════════════╗
║  INTERRUPTED — stopped by user                                     ║
╠════════════════════════════════════════════════════════════════════╣
║  Rounds       0              Best         33.3% (round search)     ║
║  Stop reason  interrupted                                          ║
║  Resume: re-run this cell -- rounds auto-restore                   ║
║  Cycle ID     cycle_be8c4d8229f6                                   ║
╚════════════════════════════════════════════════════════════════════╝

In [ ]:
#@title 5. Results — summary, save, sync
show_campaign_summary(campaign_rounds)
show_flip_tracking(campaign_rounds)
show_lineage_chain(campaign_rounds)

# --- Persist (T2: below the fold) ---
save_campaign_winner(
    campaign_rounds, campaign_config, svc["store"], svc["backend_id"],
    experiment_id=EXPERIMENT_ID,
)
sync_langfuse(
    svc["store"], svc["backend_id"],
    dataset_name="termnorm_ground_truth",
)