# Optimization Campaign (HITL)

**Prerequisites:** TermNorm backend at `http://127.0.0.1:8000` | Groq API key in `.env` | Restart kernel after first sync

**Workflow:** Setup → Data → Explore → Optimize → Results

In [1]:
%load_ext autoreload
%autoreload 2

from campaign_lib import *

# --- Services ---
svc = await init_services()
TASK_DESCRIPTION = load_task_description(
    r"C:\Users\dsacc\OfficeAddinApps\TermNorm-excel\backend-api\config\LCA_INPUT_PATTERNS.md"
)

# --- Campaign config ---
# ALL experiment knobs live here — no hidden defaults in service code.
campaign_config = {
    "sample_size": 15,              # queries per eval step (0 = all)
    "exploration_sample_size": 10,  # queries per scan/grid point (can be smaller)
    "exploration_rate": 0.5,        # PRIMARY KNOB: 0.0=conservative, 1.0=aggressive
    "exclude_nodes": ["llm_ranking"],    # nodes to skip (e.g. ["entity_profiling"])
    # --- Backend node overrides ---
    # Override values from GET /pipeline. Flat names resolved via schema override_map.
    # See show_pipeline_snapshot() output for available params per node.
    "pipeline_overrides": {
        # web_search
        "max_sites": 20,                          # max web pages to fetch content from
        "num_results": 20,                        # search engine results to request
        "content_char_limit": 800,                # max chars per web page
        # entity_profiling
        "profiling_model": "openai/gpt-oss-120b", # entity_profiling LLM model
        "profiling_max_tokens": 4000,             # entity_profiling max output tokens
        # llm_ranking
        "ranking_model": "openai/gpt-oss-120b",   # llm_ranking LLM model
    },
    "optimization": {
        # --- Core loop ---
        "patience": 2,                   # consecutive non-improvements before stop/escalate
        "max_rounds": None,              # None = unlimited
        "n_variants": 5,                 # candidates per round
        "creativity": 0.7,               # temperature for candidate generation
        "improvement_threshold": 0.01,   # accuracy delta to count as improvement
        "seed": 42,                      # subsampling seed (reproducibility)
        "max_failures": 15,              # failure examples fed to LLM candidate generation
        # --- Escalation ---
        "degradation_threshold": 0.4,    # fraction of degraded queries to trigger escalation
        "backend_warning_threshold": 2,  # degradation resets before backend advisory
        "enable_l2": True,               # L2 refine_context on escalation
        "enable_l3": True,               # L3 modify_plan on L2 stall
        "l2_patience": 2,               # L2 stalls before L3
        "l3_patience": 1,               # L3 stalls before stop
        "l2_temperature": 0.3,           # LLM temperature for L2 transitions
        "l3_temperature": 0.5,           # LLM temperature for L3 transitions
        # --- Critique ---
        "enable_critique": True,         # critique agent between generate/evaluate
    },
    "eval_llm": {
        # "model":       "moonshotai/kimi-k2-instruct-0905",  # 10x more expensive
        "model":       "openai/gpt-oss-120b",
        "provider":    "groq",
        "temperature": 0.4,
        # --- Anthropic (cost: opus >> sonnet >> haiku) ---
        # "model": "claude-opus-4-6",
        # "model": "claude-sonnet-4-6",
        # "model": "claude-haiku-4-5-20251001",
        "max_tokens": 2000,
    },
    "pipeline_params": None        # set by configure_pipeline()
}

# --- Pipeline snapshot & params ---
pipeline_config_full = await show_pipeline_snapshot(svc)
pipeline_params = configure_pipeline(svc, campaign_config)

Backend: http://127.0.0.1:8000

2026-04-01 14:25:55 INFO     [api.services.pipeline_discovery] Parsed pipeline 'TermNorm' with 6 steps
2026-04-01 14:25:55 INFO     [api.services.campaign.campaign_init] Pipeline schema loaded: termnorm vv1.1

Pipeline: termnorm (6 nodes)
Experiment: production_historical (40 queries, 93 session terms)
Experiment : production_historical
Mappings   : 887 total, 812 with verified ground truth
Queries    : 40  |  Session terms: 93
Loaded task description: 3751 chars from LCA_INPUT_PATTERNS.md
PIPELINE SNAPSHOT: TermNorm v1.1
--------------------------------------------------
  Nodes:   ['cache_lookup', 'fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching', 'llm_ranking', 'direct_prompt']
  Schemas: ['entity_profile/1', 'llm_ranking_output/1']
  Prompts: ['entity_profiling/1', 'llm_ranking/1']
{
  "name": "TermNorm",
  "version": "v1.1",
  "description": "TermNorm AI terminology normalization pipeline",
  "required_step": "entity_profile",
  "template_variables": [
    "{{core_concept}}",
    "{{entity_profile_json}}",
    "{{matches}}"
  ],
  "dataset_name": "termnorm_ground_truth",
  "available_models": [
    "moonshotai/kimi-k2-instruct-0905",
    "meta-llama/llama-4-scout-17b-16e-instruct",
    "moonshotai/kimi-k2-instruct",
    "openai/gpt-oss-120b"
  ],
  "nodes": {
    "cache_lookup": {
      "type": "cache",
      "runtime": "frontend",
      "short_circuit": true,
      "node_role": "cache",
      "description": "Checks the cache for previously resolved queries. Short-circuits the pipeline on hit.",
      "config": {},
      "optimizer": {
        "langfuse_type": "span"
      }
    },
    "fuzzy_matching": {
      "type": "retriever",
      "runtime": "frontend",
      "short_circuit": true,
      "node_role": "candidate_source",
      "description": "Fuzzy string matching against the database index. Short-circuits on high-confidence matches, bypassing web search and LLM profiling entirely.",
      "config": {
        "threshold": 70,
        "scorer": "WRatio",
        "limit": 5
      },
      "optimizer": {
        "param_keys": [
          "fuzzy_threshold",
          "fuzzy_scorer"
        ],
        "param_descriptions": {
          "fuzzy_threshold": "Minimum similarity score (0-100) to accept a fuzzy match",
          "fuzzy_scorer": "Scoring algorithm for fuzzy string comparison"
        },
        "override_map": {
          "fuzzy_threshold": "threshold",
          "fuzzy_scorer": "scorer"
        },
        "langfuse_type": "span"
      }
    },
    "web_search": {
      "type": "tool",
      "runtime": "backend",
      "node_role": "enricher",
      "description": "Searches the web for contextual information about the input query. Retrieved content provides the primary raw context that entity_profiling uses to generate structured profiles \u00e2\u20ac\u201d the quality of web results directly determines profiling quality.",
      "config": {
        "max_sites": 7,
        "num_results": 20,
        "content_char_limit": 800,
        "fallback_keywords_limit": 8,
        "query_prefix": "",
        "query_suffix": "",
        "brave_api_timeout": 10,
        "scrape_timeout": 5,
        "http_content_limit": 50000,
        "min_page_text_length": 100,
        "max_page_text_length": 10000,
        "title_truncate_length": 100,
        "scrape_workers": 10,
        "scrape_max_retries": 1,
        "scrape_retry_delay": 1.0,
        "scrape_retry_status_codes": [
          429,
          500,
          502,
          503,
          504
        ],
        "scrape_jitter": 0.5,
        "scrape_headers": {
          "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
          "DNT": "1",
          "Upgrade-Insecure-Requests": "1",
          "Sec-Fetch-Dest": "document",
          "Sec-Fetch-Mode": "navigate",
          "Sec-Fetch-Site": "none",
          "Sec-Fetch-User": "?1"
        },
        "user_agents": [
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
          "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:138.0) Gecko/20100101 Firefox/138.0",
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:138.0) Gecko/20100101 Firefox/138.0",
          "Mozilla/5.0 (X11; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0",
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edg/136.0.0.0",
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Safari/605.1.15",
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0"
        ],
        "skip_extensions": [
          ".pdf",
          ".doc",
          ".docx",
          ".ppt",
          ".pptx",
          ".xls",
          ".xlsx"
        ],
        "skip_domains": [
          "academia.edu",
          "researchgate.net",
          "arxiv.org",
          "ieee.org",
          "linkedin.com",
          "facebook.com",
          "instagram.com",
          "twitter.com",
          "x.com"
        ],
        "search_language": "en",
        "search_country": "US",
        "accept_language": "en-US,en;q=0.9",
        "html_strip_tags": [
          "script",
          "style",
          "nav",
          "header",
          "footer"
        ],
        "min_keyword_length": 3,
        "keyword_split_chars": [
          "/",
          "-"
        ],
        "spellcheck": true,
        "result_filter": "",
        "extra_snippets": true,
        "freshness": ""
      },
      "optimizer": {
        "param_keys": [
          "max_sites",
          "num_results",
          "content_char_limit",
          "query_prefix",
          "query_suffix"
        ],
        "param_descriptions": {
          "query_prefix": "Text prepended to the input query before web search \u00e2\u20ac\u201d controls search focus, domain targeting, and terminology framing (e.g. 'LCA database' narrows to domain)",
          "query_suffix": "Text appended to the input query before web search \u00e2\u20ac\u201d adds qualifiers, constraints, or context keywords (e.g. 'material composition' adds specificity)",
          "num_results": "Number of search engine results to request",
          "max_sites": "Maximum number of web pages to fetch and extract content from",
          "content_char_limit": "Maximum characters of content to extract per web page"
        },
        "override_map": {
          "max_sites": "max_sites",
          "num_results": "num_results",
          "content_char_limit": "content_char_limit",
          "query_prefix": "query_prefix",
          "query_suffix": "query_suffix"
        },
        "observation_name": "web_search",
        "observation_mappings": [
          {
            "pipeline_key": "web_sources",
            "output_field": "sources"
          },
          {
            "pipeline_key": "web_search_status",
            "output_field": "status"
          }
        ],
        "langfuse_type": "tool"
      }
    },
    "entity_profiling": {
      "type": "generation",
      "runtime": "backend",
      "node_role": "enricher",
      "description": "LLM-driven step that generates a structured entity profile from the input query and web-sourced raw content. Produces the required pipeline output (entity_profile). Profile quality depends on both the LLM configuration and the quality of upstream web_search results.",
      "config": {
        "model": "moonshotai/kimi-k2-instruct-0905",
        "temperature": 0.3,
        "max_tokens": null,
        "raw_content_limit": 5000,
        "per_site_content_limit": 500,
        "prompt_family": "entity_profiling",
        "prompt_version": 1,
        "schema_family": "entity_profile",
        "schema_version": 1
      },
      "optimizer": {
        "param_keys": [
          "raw_content_limit",
          "profiling_temperature",
          "profiling_max_tokens",
          "profiling_prompt",
          "profiling_schema",
          "profiling_model"
        ],
        "param_descriptions": {
          "raw_content_limit": "Maximum characters of web-sourced raw content passed as context to the profiling LLM \u00e2\u20ac\u201d bounds how much of web_search output is visible to the model",
          "profiling_temperature": "LLM sampling temperature for profile generation",
          "profiling_max_tokens": "Maximum tokens in the LLM profile generation response"
        },
        "override_map": {
          "raw_content_limit": "raw_content_limit",
          "profiling_temperature": "temperature",
          "profiling_max_tokens": "max_tokens",
          "profiling_prompt": "prompt",
          "profiling_schema": "output_schema",
          "profiling_model": "model"
        },
        "input_keys": [
          "web_sources"
        ],
        "observation_name": "entity_profiling",
        "observation_mappings": [
          {
            "pipeline_key": "entity_profile",
            "output_field": null,
            "is_llm": true
          }
        ],
        "langfuse_type": "generation"
      }
    },
    "token_matching": {
      "type": "retriever",
      "runtime": "backend",
      "node_role": "candidate_source",
      "description": "Token-level retrieval matching entity profile fields against database entries. Candidate pool quality depends on the entity profile generated upstream.",
      "config": {
        "max_token_candidates": 20,
        "tokenization_regex": "[a-zA-Z0-9]+"
      },
      "optimizer": {
        "param_keys": [
          "max_token_candidates"
        ],
        "param_descriptions": {
          "max_token_candidates": "Maximum number of candidates to return from token matching"
        },
        "override_map": {
          "max_token_candidates": "max_token_candidates"
        },
        "input_keys": [
          "entity_profile"
        ],
        "observation_name": "token_matching",
        "observation_mappings": [
          {
            "pipeline_key": "token_matched_candidates",
            "output_field": "candidates"
          }
        ],
        "langfuse_type": "retriever"
      }
    },
    "llm_ranking": {
      "type": "generation",
      "runtime": "backend",
      "node_role": "ranker",
      "description": "LLM-driven re-ranking of token-matched candidates using a ranking prompt. Selects the best match from the candidate pool.",
      "config": {
        "model": "moonshotai/kimi-k2-instruct-0905",
        "temperature": 0.0,
        "max_tokens": 4000,
        "sample_size": 20,
        "debug_output_limit": 20,
        "relevance_weight_core": 0.7,
        "prompt_family": "llm_ranking",
        "prompt_version": 1,
        "schema_family": "llm_ranking_output",
        "schema_version": 1
      },
      "optimizer": {
        "param_keys": [
          "ranking_temperature",
          "ranking_max_tokens",
          "ranking_sample_size",
          "ranking_prompt",
          "ranking_schema",
          "ranking_model",
          "relevance_weight_core"
        ],
        "param_descriptions": {
          "ranking_temperature": "LLM sampling temperature for ranking",
          "ranking_max_tokens": "Maximum tokens in the LLM ranking response",
          "ranking_sample_size": "Number of candidates sampled from the pool for LLM ranking",
          "relevance_weight_core": "Weight given to core-concept relevance in ranking score"
        },
        "override_map": {
          "ranking_temperature": "temperature",
          "ranking_max_tokens": "max_tokens",
          "ranking_sample_size": "sample_size",
          "ranking_prompt": "prompt",
          "ranking_schema": "output_schema",
          "ranking_model": "model",
          "relevance_weight_core": "relevance_weight_core"
        },
        "input_keys": [
          "token_matched_candidates",
          "entity_profile"
        ],
        "observation_name": "llm_ranking",
        "observation_mappings": [
          {
            "pipeline_key": "ranked_candidates",
            "output_field": "ranked_candidates",
            "is_llm": true
          }
        ],
        "langfuse_type": "generation"
      }
    },
    "direct_prompt": {
      "type": "generation",
      "runtime": "backend",
      "node_role": "",
      "description": "Direct LLM prompt for simple queries \u00e2\u20ac\u201d bypasses the full pipeline.",
      "config": {
        "model": "moonshotai/kimi-k2-instruct-0905",
        "temperature": 0.0,
        "max_tokens": 300,
        "accept_threshold": 0.75,
        "correction_top_n": 10
      },
      "optimizer": {
        "langfuse_type": "generation"
      }
    }
  },
  "pipelines": {
    "default": [
      "cache_lookup",
      "fuzzy_matching",
      "web_search",
      "entity_profiling",
      "token_matching",
      "llm_ranking"
    ]
  },
  "cache": {
    "high_confidence_threshold": 0.8,
    "verified_methods": [
      "UserChoice",
      "DirectEdit",
      "cached",
      "fuzzy"
    ]
  },
  "llm_defaults": {
    "provider": "groq",
    "model": "moonshotai/kimi-k2-instruct-0905",
    "timeout": 60,
    "retry_attempts": 3,
    "retry_backoff_base": 2,
    "token_estimation_multiplier": 1.3,
    "token_limit": 100000,
    "seed": null,
    "logprobs": null
  },
  "resolved_schemas": {
    "entity_profile/1": {
      "family": "entity_profile",
      "version": 1,
      "description": "Entity profile extraction schema for web research pipeline",
      "fields": [
        "entity_name",
        "core_concept",
        "distinguishing_features",
        "key_properties",
        "technical_specifications",
        "alternative_names",
        "classification_aliases",
        "constituent_materials",
        "manufacturing_processes",
        "applications",
        "notes"
      ],
      "json_schema": {
        "type": "object",
        "properties": {
          "entity_name": {
            "type": "string"
          },
          "core_concept": {
            "type": "string",
            "description": "The single word that defines what this expression represents"
          },
          "distinguishing_features": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "key_properties": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "technical_specifications": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Explicit technical specs, dimensions, codes, ratings, tolerances"
          },
          "alternative_names": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "classification_aliases": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic"
          },
          "constituent_materials": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge"
          },
          "manufacturing_processes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards"
          },
          "applications": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Direct and derived applications based on product characteristics"
          },
          "notes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "entity_name",
          "core_concept",
          "distinguishing_features",
          "key_properties",
          "technical_specifications",
          "alternative_names",
          "classification_aliases",
          "constituent_materials",
          "manufacturing_processes",
          "applications",
          "notes"
        ]
      }
    },
    "llm_ranking_output/1": {
      "family": "llm_ranking_output",
      "version": 1,
      "description": "LLM ranking step output schema \u2014 structured candidate evaluation",
      "fields": [
        "profile_summary",
        "core_concept_description",
        "ranked_candidates"
      ],
      "json_schema": {
        "type": "object",
        "properties": {
          "profile_summary": {
            "type": "string",
            "description": "1-2 sentence summary of the entity profile"
          },
          "core_concept_description": {
            "type": "string",
            "description": "Description of the core concept match"
          },
          "ranked_candidates": {
            "type": "array",
            "description": "Candidates ranked by relevance score",
            "items": {
              "type": "object",
              "properties": {
                "candidate": {
                  "type": "string"
                },
                "core_concept_score": {
                  "type": "number"
                },
                "spec_score": {
                  "type": "number"
                },
                "evaluation_reasoning": {
                  "type": "string"
                },
                "key_match_factors": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "spec_gaps": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "required": [
                "candidate",
                "core_concept_score",
                "spec_score",
                "evaluation_reasoning",
                "key_match_factors"
              ]
            }
          }
        },
        "required": [
          "profile_summary",
          "core_concept_description",
          "ranked_candidates"
        ]
      }
    }
  },
  "resolved_prompts": {
    "entity_profiling/1": {
      "family": "entity_profiling",
      "version": 1,
      "description": "Extract comprehensive entity profile from web research data with US/GB spelling variants",
      "template_variables": [
        "query",
        "format_string",
        "combined_text"
      ],

In [2]:
#@title Load data & evaluation context
RUN_BASELINE = False

train_data, session_terms = prepare_datasets(
    svc["store"], svc["backend_id"],
    excel_path=r"C:\Users\dsacc\Desktop\project-TermNorm\OneDrive_2025-07-02\Austausch Beispiele\Prozessnamen\BOM-example.xlsx",
)
svc["session_terms"] = session_terms

baseline_ps, eval_data, campaign_rounds, baseline_results = await prepare_eval_context(
    svc, train_data, campaign_config, run_baseline=RUN_BASELINE,
)

==================================================
  Train              : 984 queries
  Test (processes)   : 82 queries
  Test (material)    : 165 queries
  ------------------------------------------------
  Combined queries   : 820 (deduplicated)
  Session identifiers: 94 unique targets
==================================================

Evaluation data: 984 queries

In [3]:
#@title Experiment dashboard
EXPERIMENT_ID = None  # Set to hex ID to resume (e.g. '68e2c5')

pipeline_params = show_experiment_dashboard(
    svc=svc, experiment_id=EXPERIMENT_ID,
    campaign_config=campaign_config, eval_data=eval_data,
    baseline_prompt_fields=campaign_rounds[0]["prompt_fields"].model_dump() if campaign_rounds else None,
)

========================================================================
  EXPERIMENT DASHBOARD (termnorm-local)
========================================================================
  Dataset runs: 208 total (2 77e7e77777e7, 2 be8c4d8229f6, 1 dbb05e948b53, 66 e9315d106538, 137 other)
  Best result: 66.7% (scan)

  Campaigns (most recent first):
    cycle_e9315d106538  completed    7 rounds  best=0.0%  base=0.0%
      patience=?  rounds=None  sample=15  model=openai/gpt-oss-120b

    cycle_be8c4d8229f6  interrupted  0 rounds  best=33.3%  base=33.3%
      patience=2  rounds=None  sample=15  model=openai/gpt-oss-120b

    cycle_dbb05e948b53  interrupted  0 rounds  best=33.3%  base=33.3%
      patience=2  rounds=None  sample=15  model=moonshotai/kimi-k2-instruct-09

========================================================================
  Set experiment_id="<short_id>" to see full config and diff
  Active: cycle_e2c05b4bcc16

## 3. Explore

Exploration via **Smart Search** (scan advisor + sensitivity scan).

In [4]:
#@title Task context + scan advisor
ADVISOR_MODEL = "openai/gpt-oss-120b"  # model for scan advisor LLM call

task_context = await decompose_task_context(TASK_DESCRIPTION, campaign_config, svc)

# preview_advisor_prompt(campaign_config, svc, task_description=task_context, raw=True)
# advisory, scan_variants, schema_labels = await run_scan_advisor(
#     campaign_config, svc,
#     task_description=task_context,
#     model=ADVISOR_MODEL,
# )

TASK CONTEXT DECOMPOSITION
--------------------------------------------------
  domain: Life Cycle Assessment (LCA) terminology and database normalization
  pipeline_purpose: Normalize free-form user inputs into exact, standardized entries of LCA databases (e.g., ecoinvent, GaBi) for accurate impact assessment.
  data_characteristics: Textual inputs of varying length containing industrial material codes, DIN/ISO/IEC references, brand/trade names, chemical formulas, agricultural qualifiers, geographic tags, and mixed-language terms; multilingual (German, French, English); high variability, typically dozens to hundreds of entries per project.
  optimization_goals: Maximize correct match rate (precision and recall) against ground truth, correctly flag no‑match cases, handle synonyms, variants, and geographic scopes, and minimize false positives.
  key_challenges: Structural mismatch between unstructured shorthand and rigid database naming; need for domain knowledge to decode brands, standards, and compositions; synonym and naming evolution; multiple geographic variants; composite material decomposition; recognizing inputs with no corresponding database entry.

In [5]:
#@title Scan variant config (edit suggested values or add your own)
# Schema axes: mutation tuples ("-", path), ("+", path, type, req, desc),
# ("~", old, new, type, req, desc). Non-schema axes: plain value lists.

scan_sample_size = 3  # queries per scan variant (0 = use all)

scan_variants = {
    # ── Token matching ───────────────────────────────────────────────────
    'max_token_candidates': [10, 30, 50],
    # ── Web search: query framing ────────────────────────────────────────
    'query_prefix': [
        # --- Database-oriented ---
        'ecoinvent', 'GaBi', 'ecoinvent LCA database material name',
        'material composition LCA', # 'ecoinvent equivalent', 'ecoinvent match for', 'identify LCA material for',
        'what is',# 'define', 'identify', 'describe material',
        # 'chemical composition of', 'CAS number', 'IUPAC name for',
        'technical data sheet', 'product specification', # 'manufacturer datasheet', 'material safety data sheet',
        'manufactured from', 'production process for', # 'raw material for',
        # --- Synonym / translation ---
        # 'also known as', # 'synonym for', 'equivalent material', 'alternative name for',
        # 'wikipedia', # 'material properties of',
    ],
    # ── Web search: volume knobs ─────────────────────────────────────────
    'max_sites': [3, 7, 12],
    'num_results': [5, 20, 40],
    'content_char_limit': [400, 800, 1500],
    # ── Fuzzy matching ───────────────────────────────────────────────────
    # 'fuzzy_threshold': [50, 70, 90],
    # 'fuzzy_scorer': ['ratio', 'WRatio', 'token_set_ratio'],
    # ── Entity profiling: LLM tuning ─────────────────────────────────────
    'profiling_temperature': [0.0, 0.3, 0.7],
    'raw_content_limit': [1000, 2500, 8000],
    # ── Prompt fields ────────────────────────────────────────────────────
    'thinking_style': [
          'Think step-by-step: isolate distinguishing features → compare each candidate → assign scores.',
          'Consider the most likely interpretation first, then check alternatives.',       
          'Reason by elimination: discard obviously wrong candidates, then rank the rest.',
      ],
    # ── Entity profiling: schema mutations ───────────────────────────────
    'profiling_schema': [
        # --- LCA-database-specific (original) ---
        [['+', 'geography_scope', 'array', False, 'Relevant ecoinvent/SimaPro geography codes inferred from context, e.g. GLO, RER, CH, RNA'],
         ['+', 'database_format_hint', 'string', False, "Best-guess ecoinvent-style name fragment for this entity, e.g. 'market for polyethylene, high density'"]],
        [['+', 'lca_database_names', 'array', True, "Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'"]],
        [['-', 'manufacturing_processes'], ['-', 'applications'],
         ['+', 'lca_database_names', 'array', True, 'Likely ecoinvent or GaBi database entry names for this entity using standard LCA naming conventions']],
        # [['~', 'notes', 'material_category', 'string', True, "The broad LCA material category this entity belongs to, e.g. 'polyethylene', 'brass', 'steel'"]],
        [['-', 'applications'], ['+', 'ecoinvent_candidate_names', 'array', True, 'Exact ecoinvent activity names this entity most likely maps to']],
        [['-', 'manufacturing_processes'], ['+', 'database_search_tokens', 'array', True, 'Optimized search tokens for LCA database lookup including spelling variants']],
        # [['~', 'classification_aliases', 'classification_aliases', 'array', True, 'All valid ecoinvent/GaBi naming variants including geography codes and system model suffixes']],
        # --- Minimalist: strip to core matching signals ---
        [['-', 'applications'], ['-', 'manufacturing_processes'], ['-', 'notes'], ['-', 'technical_specifications']],
        # --- Chemical identity ---
        [['+', 'cas_number', 'string', False, 'CAS registry number if identifiable from context'],
         ['+', 'chemical_formula', 'string', False, 'Chemical formula or molecular structure notation']],
        # --- Trade name decoding ---
        [['~', 'key_properties', 'trade_names', 'array', True, 'Known commercial/trade names and brand names for this material, e.g. Makrolon=polycarbonate, Delrin=POM']],
        # --- Material hierarchy (specific→generic) ---
        [['+', 'material_hierarchy', 'array', False, 'Classification chain from specific to generic, e.g. [Makrolon 2805, polycarbonate, thermoplastic, polymer]']],
        # --- Process-centric (flip perspective from material to process) ---
        [['~', 'applications', 'production_route', 'string', False, 'Primary production/manufacturing route e.g. injection molding, extrusion, casting'],
         ['~', 'notes', 'form_factor', 'string', False, 'Physical form: granulate, sheet, rod, wire, powder, liquid, film']],
        # --- Standards-focused ---
        [['+', 'applicable_standards', 'array', False, 'DIN/ISO/EN/ASTM standards that reference or define this material'],
         ['-', 'applications']],
        # # --- Geography-aware ---
        # [['+', 'supply_chain_geography', 'string', False, 'Most likely geographic origin or market region for this material']],
        # # --- Confidence / ambiguity signal ---
        # [['+', 'confidence_level', 'string', False, 'How confident the model is in the identification: high/medium/low/ambiguous'],
        #  ['+', 'ambiguity_notes', 'string', False, 'What makes this input hard to identify — abbreviation, trade name, multi-material, etc.']],
        # # --- Spelling / language variant boost ---
        # [['+', 'spelling_variants', 'array', False, 'All known spelling variants across EN/DE/FR, e.g. aluminium/aluminum, polyamid/polyamide'],
        #  ['-', 'notes']],
        # --- Werkstoff / alloy code decoding ---
        [['+', 'material_code_decoded', 'string', False, 'Decoded meaning of any material code, Werkstoff number, or alloy designation present in the input'],
         ['+', 'base_material', 'string', False, 'The fundamental base material, e.g. brass, steel, polycarbonate']],
        # --- Functional equivalence ---
        [['~', 'applications', 'functional_unit', 'string', False, 'The functional unit this material serves, e.g. structural plastic, electrical insulation, food-grade packaging'],
         ['+', 'substitutes', 'array', False, 'Materials that could serve the same functional role']],
    ],
}
scan_variants, schema_labels = resolve_scan_variants(scan_variants, svc=svc)

  max_token_candidates: [10, 30, 50]
  query_prefix: ['ecoinvent', 'GaBi', 'ecoinvent LCA database material name', 'material composition LCA', 'what is', 'technical data sheet', 'product specification', 'manufactured from', 'production process for']
  max_sites: [3, 7, 12]
  num_results: [5, 20, 40]
  content_char_limit: [400, 800, 1500]
  profiling_temperature: [0.0, 0.3, 0.7]
  raw_content_limit: [1000, 2500, 8000]
  thinking_style: ['Think step-by-step: isolate distinguishing features → compare each candidate → assign scores.', 'Consider the most likely interpretation first, then check alternatives.', 'Reason by elimination: discard obviously wrong candidates, then rank the rest.']
  profiling_schema: (baseline + 13 mutations)
    [0] (baseline)
    [1] ('+', 'geography_scope', 'array', False, 'Relevant ecoinvent/SimaPro geography codes inferred from context, e.g. GLO, RER, CH, RNA'), ('+', 'database_format_hint', 'string', False, 'Best-guess ecoinvent-style name fragment for this entity, e.g. 'market for polyethylene, high density'')
    [2] ('+', 'lca_database_names', 'array', True, 'Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'')
    [3] ('-', 'manufacturing_processes'), ('-', 'applications'), ('+', 'lca_database_names', 'array', True, 'Likely ecoinvent or GaBi database entry names for this entity using standard LCA naming conventions')
    [4] ('-', 'applications'), ('+', 'ecoinvent_candidate_names', 'array', True, 'Exact ecoinvent activity names this entity most likely maps to')
    [5] ('-', 'manufacturing_processes'), ('+', 'database_search_tokens', 'array', True, 'Optimized search tokens for LCA database lookup including spelling variants')
    [6] ('-', 'applications'), ('-', 'manufacturing_processes'), ('-', 'notes'), ('-', 'technical_specifications')
    [7] ('+', 'cas_number', 'string', False, 'CAS registry number if identifiable from context'), ('+', 'chemical_formula', 'string', False, 'Chemical formula or molecular structure notation')
    [8] ('~', 'key_properties', 'trade_names', 'array', True, 'Known commercial/trade names and brand names for this material, e.g. Makrolon=polycarbonate, Delrin=POM')
    [9] ('+', 'material_hierarchy', 'array', False, 'Classification chain from specific to generic, e.g. [Makrolon 2805, polycarbonate, thermoplastic, polymer]')
    [10] ('~', 'applications', 'production_route', 'string', False, 'Primary production/manufacturing route e.g. injection molding, extrusion, casting'), ('~', 'notes', 'form_factor', 'string', False, 'Physical form: granulate, sheet, rod, wire, powder, liquid, film')
    [11] ('+', 'applicable_standards', 'array', False, 'DIN/ISO/EN/ASTM standards that reference or define this material'), ('-', 'applications')
    [12] ('+', 'material_code_decoded', 'string', False, 'Decoded meaning of any material code, Werkstoff number, or alloy designation present in the input'), ('+', 'base_material', 'string', False, 'The fundamental base material, e.g. brass, steel, polycarbonate')
    [13] ('~', 'applications', 'functional_unit', 'string', False, 'The functional unit this material serves, e.g. structural plastic, electrical insulation, food-grade packaging'), ('+', 'substitutes', 'array', False, 'Materials that could serve the same functional role')

In [6]:
#@title Run sensitivity scan
scan_baseline_sp, scan_df, axis_profiles = await run_sensitivity_scan(
    baseline_ps, campaign_config, scan_variants, eval_data,
    scan_sample_size=scan_sample_size,
    svc=svc, experiment_id=EXPERIMENT_ID or "",
)

Active nodes: cache_lookup, fuzzy_matching, web_search, entity_profiling, token_matching  Excluded: llm_ranking
Restructured baseline fields (cached):
  persona: You are a comprehensive technical database API specialized in exhaustive entity ...
  task_intent: Extract all possible information about a given query from research data and retu...
  problem_description: Given a product or technical description query, parse unstructured research text...
  instruction: Extract ALL possible information about '{{query}}' from the research data and re...
  thinking_style: Think step by step, first gather explicit data, then infer implicit attributes, ...
  answer_format: A single JSON object matching the provided {{format_string}}, with all array fie...
Search baseline: 822ab596df90 (render: 1541 chars)
Historical data: 171 results across 17 unique prompts
Matching runs (step sequence): 128, 53 cached results
Scan variant coverage (128 matching runs):
max_token_candidates     10→28 ✓  30→24 ✓  50→15 ✓
query_prefix             9/9 values tested
  ecoinvent→9 ✓  GaBi→9 ✓  ecoinvent LCA database material name→6 ✓
  material composition LCA→16 ✓  what is→6 ✓  technical data sheet→6 ✓
  product specification→6 ✓  manufactured from→6 ✓
  production process for→6 ✓
max_sites                3→9 ✓  7→83 ✓  12→6 ✓
num_results              5→9 ✓  20→83 ✓  40→6 ✓
content_char_limit       400→9 ✓  800→83 ✓  1500→6 ✓
profiling_temperature    0.0→9 ✓  0.3→77 ✓  0.7→6 ✓
raw_content_limit        1000→9 ✓  2500→9 ✓  8000→6 ✓
thinking_style           [a]→3 ✓  [b]→3 ✓  [c]→✗
profiling_schema         14/14 values tested
  [d]→15 ✓  [e]→15 ✓  [f]→9 ✓  [g]→9 ✓  [h]→9 ✓  [i]→9 ✓  [j]→9 ✓
  [k]→9 ✓  [l]→9 ✓  [m]→9 ✓  [n]→7 ✓  [o]→6 ✓  [p]→6 ✓  [q]→6 ✓
Values:
  [a] Think step-by-step: isolate distinguishing features → compare each candidate → assign scores.
  [b] Consider the most likely interpretation first, then check alternatives.
  [c] Reason by elimination: discard obviously wrong candidates, then rank the rest.
  [d] {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "applications": {"description": "Direct and derived applications based on product characteristics", "items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "manufacturing_processes": {"description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards", "items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "manufacturing_processes", "applications", "notes"], "type": "object"}
  [e] {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "applications": {"description": "Direct and derived applications based on product characteristics", "items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "database_format_hint": {"description": "Best-guess ecoinvent-style name fragment for this entity, e.g. 'market for polyethylene, high density'", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "geography_scope": {"description": "Relevant ecoinvent/SimaPro geography codes inferred from context, e.g. GLO, RER, CH, RNA", "items": {"type": "string"}, "type": "array"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "manufacturing_processes": {"description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards", "items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "manufacturing_processes", "applications", "notes"], "type": "object"}
  [f] {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "applications": {"description": "Direct and derived applications based on product characteristics", "items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "lca_database_names": {"description": "Likely ecoinvent or GaBi database entry names that would match this entity, using standard LCA database naming conventions like 'market for X | X | cut-off, U'", "items": {"type": "string"}, "type": "array"}, "manufacturing_processes": {"description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards", "items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "manufacturing_processes", "applications", "notes", "lca_database_names"], "type": "object"}
  [g] {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "lca_database_names": {"description": "Likely ecoinvent or GaBi database entry names for this entity using standard LCA naming conventions", "items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "notes", "lca_database_names"], "type": "object"}
  [h] {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "ecoinvent_candidate_names": {"description": "Exact ecoinvent activity names this entity most likely maps to", "items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "manufacturing_processes": {"description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards", "items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "manufacturing_processes", "notes", "ecoinvent_candidate_names"], "type": "object"}
  [i] {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "applications": {"description": "Direct and derived applications based on product characteristics", "items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "database_search_tokens": {"description": "Optimized search tokens for LCA database lookup including spelling variants", "items": {"type": "string"}, "type": "array"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "applications", "notes", "database_search_tokens"], "type": "object"}
  [j] {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "key_properties": {"items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "alternative_names", "classification_aliases", "constituent_materials"], "type": "object"}
  [k] {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "applications": {"description": "Direct and derived applications based on product characteristics", "items": {"type": "string"}, "type": "array"}, "cas_number": {"description": "CAS registry number if identifiable from context", "type": "string"}, "chemical_formula": {"description": "Chemical formula or molecular structure notation", "type": "string"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "manufacturing_processes": {"description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards", "items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "manufacturing_processes", "applications", "notes"], "type": "object"}
  [l] {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "applications": {"description": "Direct and derived applications based on product characteristics", "items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "manufacturing_processes": {"description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards", "items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}, "trade_names": {"description": "Known commercial/trade names and brand names for this material, e.g. Makrolon=polycarbonate, Delrin=POM", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "manufacturing_processes", "applications", "notes", "trade_names"], "type": "object"}
  [m] {"properties": {"alternative_names": {"items": {"type": "string"}, "type": "array"}, "applications": {"description": "Direct and derived applications based on product characteristics", "items": {"type": "string"}, "type": "array"}, "classification_aliases": {"description": "Full spectrum of valid ways this entity could be referenced using expert-level terminology, from precise to generic", "items": {"type": "string"}, "type": "array"}, "constituent_materials": {"description": "All materials that make up this product, both explicit and standard/typical materials inferred from domain knowledge", "items": {"type": "string"}, "type": "array"}, "core_concept": {"description": "The single word that defines what this expression represents", "type": "string"}, "distinguishing_features": {"items": {"type": "string"}, "type": "array"}, "entity_name": {"type": "string"}, "key_properties": {"items": {"type": "string"}, "type": "array"}, "manufacturing_processes": {"description": "Both stated and inferred manufacturing processes based on product type, materials, and industry standards", "items": {"type": "string"}, "type": "array"}, "material_hierarchy": {"description": "Classification chain from specific to generic, e.g. [Makrolon 2805, polycarbonate, thermoplastic, polymer]", "items": {"type": "string"}, "type": "array"}, "notes": {"items": {"type": "string"}, "type": "array"}, "technical_specifications": {"description": "Explicit technical specs, dimensions, codes, ratings, tolerances", "items": {"type": "string"}, "type": "array"}}, "required": ["entity_name", "core_concept", "distinguishing_features", "key_properties", "technical_specifications", "alternative_names", "classification_aliases", "constituent_materials", "manufacturing_processes", "applications", "notes"], "type": "object"}

2026-04-01 14:25:59 INFO     [api.services.search.sensitivity_scanner] Pruning axis 'query_prefix': all 2 variants overlap with baseline CI — skipping 7 remaining values

  [1] GaBi                                       0/3  0.0%  +0.0% [cached]
  >> PRUNED: query_prefix — 2 variants overlap baseline CI, skipping 7 remaining

======================================================================
  Axis 2/9: max_sites (pipeline_param, 3 values)
======================================================================
 16.1s MISS 3/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
  8.9s MISS 3/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
 12.0s MISS 2/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
  [0] 3                                          0/3  0.0%  +0.0% [cached]
 10.3s MISS 3/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
 11.5s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Hot rolling, steel {RoW}| hot rolli
 15.4s MISS 2/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 6 of 20 fetched URLs returned content (13 filtered: 12×too_short, 1×http_403; 1 error)

2026-04-01 14:25:59 INFO     [api.services.search.sensitivity_scanner] Pruning axis 'max_sites': all 2 variants overlap with baseline CI — skipping 1 remaining values

  [1] 7                                          0/3  0.0%  +0.0% [cached]
  >> PRUNED: max_sites — 2 variants overlap baseline CI, skipping 1 remaining

======================================================================
  Axis 3/9: num_results (pipeline_param, 3 values)
======================================================================
 11.7s MISS 3/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
            ⚠ web_search: 1 of 5 fetched URLs returned content (4 filtered: 2×http_429, 2×skip_extension)
  9.2s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
            ⚠ web_search: 4 of 5 fetched URLs returned content (1 filtered: 1×skip_extension)
 10.4s MISS 3/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 1 of 5 fetched URLs returned content (4 filtered: 3×too_short, 1×http_403)
  [0] 5                                          0/3  0.0%  +0.0% [cached]
 10.3s MISS 3/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
 11.5s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Hot rolling, steel {RoW}| hot rolli
 15.4s MISS 2/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 6 of 20 fetched URLs returned content (13 filtered: 12×too_short, 1×http_403; 1 error)

2026-04-01 14:25:59 INFO     [api.services.search.sensitivity_scanner] Pruning axis 'num_results': all 2 variants overlap with baseline CI — skipping 1 remaining values

  [1] 20                                         0/3  0.0%  +0.0% [cached]
  >> PRUNED: num_results — 2 variants overlap baseline CI, skipping 1 remaining

======================================================================
  Axis 4/9: content_char_limit (pipeline_param, 3 values)
======================================================================
 12.6s MISS 3/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
  9.4s MISS 3/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
 13.6s MISS 3/20  [token] 📖  SJRG0010-ABS/molding                           -> Thermoforming of plastic sheets {Ro
            ⚠ web_search: 6 of 20 fetched URLs returned content (13 filtered: 13×too_short; 1 error)
  [0] 400                                        0/3  0.0%  +0.0% [cached]
 10.3s MISS 3/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
 11.5s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Hot rolling, steel {RoW}| hot rolli
 15.4s MISS 2/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 6 of 20 fetched URLs returned content (13 filtered: 12×too_short, 1×http_403; 1 error)

2026-04-01 14:25:59 INFO     [api.services.search.sensitivity_scanner] Pruning axis 'content_char_limit': all 2 variants overlap with baseline CI — skipping 1 remaining values

  [1] 800                                        0/3  0.0%  +0.0% [cached]
  >> PRUNED: content_char_limit — 2 variants overlap baseline CI, skipping 1 remaining

======================================================================
  Axis 5/9: profiling_temperature (pipeline_param, 3 values)
======================================================================
  8.1s MISS 4/20 web📖[][token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
  4.4s HIT  web📖[][token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
  6.2s MISS 3/20 web📖[][token] 📖  SJRG0010-ABS/molding                           -> Thermoforming of plastic sheets {Ro
            ⚠ web_search: 6 of 6 fetched URLs returned content
  [0] 0.0                                        1/3  33.3%  +30.0% ^ [cached]
 10.3s MISS 3/20  [token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
 11.5s MISS 2/20  [token] 📖  Stainless steel EN 10270-3/winding             -> Hot rolling, steel {RoW}| hot rolli
 15.4s MISS 2/20  [token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 6 of 20 fetched URLs returned content (13 filtered: 12×too_short, 1×http_403; 1 error)

2026-04-01 14:25:59 INFO     [api.services.search.sensitivity_scanner] Pruning axis 'profiling_temperature': all 2 variants overlap with baseline CI — skipping 1 remaining values

  [1] 0.3                                        0/3  0.0%  +0.0% [cached]
  >> PRUNED: profiling_temperature — 2 variants overlap baseline CI, skipping 1 remaining

======================================================================
  Axis 6/9: raw_content_limit (pipeline_param, 3 values)
======================================================================
  4.4s MISS 2/20 web📖[][token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 95
  6.5s MISS 2/20 web📖[][token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
  5.2s MISS 3/20 web📖[][token] 📖  SJRG0010-ABS/molding                           -> Thermoforming of plastic sheets {Ro
            ⚠ web_search: 6 of 6 fetched URLs returned content
  [0] 1000                                       0/3  0.0%  +0.0% [cached]
  6.2s MISS 3/20 web📖[][token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 50
  8.1s HIT  web📖[][token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
  5.6s MISS 2/20 web📖[][token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 6 of 6 fetched URLs returned content

2026-04-01 14:25:59 INFO     [api.services.search.sensitivity_scanner] Pruning axis 'raw_content_limit': all 2 variants overlap with baseline CI — skipping 1 remaining values

  [1] 2500                                       1/3  33.3%  +30.0% ^ [cached]
  >> PRUNED: raw_content_limit — 2 variants overlap baseline CI, skipping 1 remaining

======================================================================
  Axis 7/9: thinking_style (prompt_field, 3 values)
======================================================================
  7.7s MISS 3/20 web📖[][token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 50
  5.7s MISS 5/20 web📖[][token] 📖  Stainless steel EN 10270-3/winding             -> Metal working, average for chromium
  4.8s MISS --/20 web📖[][token] 📖  SJRG0010-ABS/molding                           -> Glass fibre reinforced plastic | 60
            ⚠ web_search: 6 of 6 fetched URLs returned content
  [0] Think step-by-step: isolate distinguishi... 0/3  0.0%  -1.7% v [cached]
  5.6s MISS 4/20 web📖[][token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
  5.3s HIT  web📖[][token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
  5.4s MISS 2/20 web📖[][token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 6 of 6 fetched URLs returned content

2026-04-01 14:25:59 INFO     [api.services.search.sensitivity_scanner] Pruning axis 'thinking_style': all 2 variants overlap with baseline CI — skipping 1 remaining values

  [1] Consider the most likely interpretation ... 1/3  33.3%  +30.0% ^ [cached]
  >> PRUNED: thinking_style — 2 variants overlap baseline CI, skipping 1 remaining

======================================================================
  Axis 8/9: profiling_schema (pipeline_param, 14 values)
======================================================================
  8.6s MISS 2/20 web📖[][token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
  3.9s MISS 2/20 web📖[][token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
  5.9s MISS 6/20 web📖[][token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 6 of 6 fetched URLs returned content
  [0] schema(11 fields)                          0/3  0.0%  +0.0% [cached]
  7.9s MISS 5/20 web📖[][token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Polyamide (Nylon) 6.6/EU-27
  5.8s MISS 2/20 web📖[][token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
  9.5s MISS 2/20 web📖[][token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 6 of 6 fetched URLs returned content

2026-04-01 14:25:59 INFO     [api.services.search.sensitivity_scanner] Pruning axis 'profiling_schema': all 2 variants overlap with baseline CI — skipping 12 remaining values

  [1] schema(13 fields)                          0/3  0.0%  +0.0% [cached]
  >> PRUNED: profiling_schema — 2 variants overlap baseline CI, skipping 12 remaining

======================================================================
  Axis 9/9: max_token_candidates (pipeline_param, 3 values)
======================================================================
  5.2s HIT  web📖[][token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 75
  4.2s HIT  web📖[][token] 📖  Stainless steel EN 10270-3/winding             -> Wire drawing, steel {RER}| wire dra
  4.0s MISS --/10 web📖[][token] 📖  SJRG0010-ABS/molding                           -> Acrylonitrile-butadiene-styrene cop
            ⚠ web_search: 6 of 6 fetched URLs returned content
  [0] 10                                         2/3  66.7%  +58.3% ^ [cached]
  4.7s MISS 2/30 web📖[][token] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Glass fibre reinforced plastic | 50
  8.8s MISS 3/30 web📖[][token] 📖  Stainless steel EN 10270-3/winding             -> Steel, chromium steel 18/8 {GLO}| m
  4.7s MISS 4/30 web📖[][token] 📖  SJRG0010-ABS/molding                           -> Thermoforming of plastic sheets {Ro
            ⚠ web_search: 6 of 6 fetched URLs returned content

2026-04-01 14:25:59 INFO     [api.services.search.sensitivity_scanner] Pruning axis 'max_token_candidates': all 2 variants overlap with baseline CI — skipping 1 remaining values

  [1] 30                                         0/3  0.0%  +0.0% [cached]
  >> PRUNED: max_token_candidates — 2 variants overlap baseline CI, skipping 1 remaining
  >> max_token_candidates: range=58.3%, best=+58.3%, worst=+0.0%, budget=high
  >> thinking_style: range=31.7%, best=+30.0%, worst=-1.7%, budget=skip
  >> query_prefix: range=30.0%, best=+30.0%, worst=+0.0%, budget=skip
  >> profiling_temperature: range=30.0%, best=+30.0%, worst=+0.0%, budget=skip
  >> raw_content_limit: range=30.0%, best=+30.0%, worst=+0.0%, budget=skip
  >> max_sites: range=0.0%, best=+0.0%, worst=+0.0%, budget=skip
  >> num_results: range=0.0%, best=+0.0%, worst=+0.0%, budget=skip
  >> content_char_limit: range=0.0%, best=+0.0%, worst=+0.0%, budget=skip
  >> profiling_schema: range=0.0%, best=+0.0%, worst=+0.0%, budget=skip

Sensitivity scan complete: 18 variants evaluated

Rank  Axis                      Type            Card  Range    Budget
----------------------------------------------------------------------
  1   max_token_candidates      pipeline_param  3     0.583    high
  2   thinking_style            prompt_field    3     0.317    skip
  3   query_prefix              pipeline_param  9     0.300    skip
  4   profiling_temperature     pipeline_param  3     0.300    skip
  5   raw_content_limit         pipeline_param  3     0.300    skip
  6   max_sites                 pipeline_param  3     0.000    skip
  7   num_results               pipeline_param  3     0.000    skip
  8   content_char_limit        pipeline_param  3     0.000    skip
  9   profiling_schema          pipeline_param  14    0.000    skip

In [7]:
#@title Scan analytics
difficulty_df = show_scan_analytics(scan_df, axis_profiles, svc)

VARIANT LEADERBOARD (all scan combos)
======================================================================

,rank,axis,variant,accuracy,delta,hits/total,errors
0,1,max_token_candidates,10,66.7%,+58.3%,2/3,0
1,2,query_prefix,ecoinvent,33.3%,+30.0%,1/3,0
2,3,raw_content_limit,2500,33.3%,+30.0%,1/3,0
3,4,profiling_temperature,0.0,33.3%,+30.0%,1/3,0
4,5,thinking_style,Consider the most likely interpretation ...,33.3%,+30.0%,1/3,0
5,6,query_prefix,GaBi (baseline),0.0%,-,0/3,0
6,7,num_results,20 (baseline),0.0%,-,0/3,0
7,8,max_sites,3 (baseline),0.0%,-,0/3,0
8,9,num_results,5 (baseline),0.0%,-,0/3,0
9,10,max_sites,7 (baseline),0.0%,-,0/3,0
10,11,profiling_temperature,0.3 (baseline),0.0%,-,0/3,0
11,12,content_char_limit,800 (baseline),0.0%,-,0/3,0
12,13,content_char_limit,400 (baseline),0.0%,-,0/3,0
13,14,raw_content_limit,1000 (baseline),0.0%,-,0/3,0
14,15,profiling_schema,schema(13 fields) (baseline),0.0%,-,0/3,0
15,16,profiling_schema,schema(11 fields) (baseline),0.0%,-,0/3,0
16,17,max_token_candidates,30 (baseline),0.0%,-,0/3,0
17,18,thinking_style,Think step-by-step: isolate distinguishi...,0.0%,-1.7%,0/3,0

PER-AXIS STATISTICS
======================================================================

,axis,type,variants,mean_acc,std_acc,best_acc,worst_acc,sensitivity,budget
0,query_prefix,pipeline_param,2,16.7%,23.6%,33.3%,0.0%,0.300,skip
1,max_sites,pipeline_param,2,0.0%,0.0%,0.0%,0.0%,0.000,skip
2,num_results,pipeline_param,2,0.0%,0.0%,0.0%,0.0%,0.000,skip
3,content_char_limit,pipeline_param,2,0.0%,0.0%,0.0%,0.0%,0.000,skip
4,profiling_temperature,pipeline_param,2,16.7%,23.6%,33.3%,0.0%,0.300,skip
5,raw_content_limit,pipeline_param,2,16.7%,23.6%,33.3%,0.0%,0.300,skip
6,thinking_style,prompt_field,2,16.7%,23.6%,33.3%,0.0%,0.317,skip
7,profiling_schema,pipeline_param,2,0.0%,0.0%,0.0%,0.0%,0.000,skip
8,max_token_candidates,pipeline_param,2,33.3%,47.1%,66.7%,0.0%,0.583,high

QUERY DIFFICULTY (10 queries across 139 scan runs)
======================================================================
  easy: 0 (0%) | discriminating: 5 (50%) | hard: 5 (50%) | error: 0 (0%)

,query,ground_truth,hit_rate,hits/evals,error_rate,classification
0,Copper Wire/cold forming,"Metal working, average for copper product manu...",0.000000,0/4,0.000000,hard
1,PC GF10 makrolon material/0,Injection moulding {RoW}| injection moulding |...,0.000000,0/4,0.000000,hard
2,PA6/66 Ultramid C3U/molding,Injection moulding {RER}| injection moulding |...,0.000000,0/5,0.000000,hard
3,PA 66 25% GF V0 RAL 7012/0,Injection moulding {RoW}| injection moulding |...,0.000000,0/5,0.000000,hard
4,EN 10270-3-1.4568\nX7CrNi17-7 (DIN17224 4.4568...,"Sheet rolling, chromium steel {RER}| sheet rol...",0.000000,0/4,0.000000,hard
5,SJRG0010-ABS/molding,Injection moulding {RER}| injection moulding |...,0.038760,5/129,0.023256,discriminating
6,Kingfa NPG25,Glass fibre reinforced plastic | 75% PA66 25% ...,0.200000,1/5,0.000000,discriminating
7,SJRG0013-PA/molding,Injection moulding {RER}| injection moulding |...,0.333333,1/3,0.000000,discriminating
8,PA66-GF25 ULTRAMID A3UG5 RAL7035 grey,Glass fibre reinforced plastic | 75% PA66 25% ...,0.364964,50/137,0.029197,discriminating
9,Stainless steel EN 10270-3/winding,"Wire drawing, steel {RER}| wire drawing, steel...",0.446154,58/130,0.015385,discriminating

In [8]:
#@title Select scan winner & seed campaign
best_sp = seed_campaign_from_scan(
    scan_df, axis_profiles, scan_baseline_sp, scan_variants,
    campaign_rounds, campaign_config,
    pipeline_schema=svc.pipeline_schema,
)

Selected best from 1 improving axes:
  max_token_candidates      best_delta=+58.3%  value_idx=0  acc=66.7%
Updated pipeline_params: {'steps': ['cache_lookup', 'fuzzy_matching', 'web_search', 'entity_profiling', 'token_matching'], 'fuzzy_matching': {'threshold': 70, 'scorer': 'WRatio'}, 'web_search': '<5 fields>', 'entity_profiling': '<5 fields>', 'token_matching': {'max_token_candidates': 20}, 'max_token_candidates': 10}

Composed winner: sp_hash=5217c2b40613

Round    Accuracy   Rolling Avg    Trend
  search     0.0%         0.0%  -

## 4. Optimize

Two modes: **Semi-automatic** (feedback cycle with patience-based auto-stop) or **Manual** (one round at a time).

In [9]:
#@title Feedback cycle preflight
scan_context = show_feedback_preflight(
    campaign_rounds, eval_data, campaign_config,
    pipeline_params=pipeline_params,
    scan_df=scan_df,
    axis_profiles=axis_profiles,
    scan_variants=scan_variants,
    difficulty_df=locals().get("difficulty_df"),
)

======================================================================
  FEEDBACK CYCLE PRE-FLIGHT
======================================================================
  Baseline accuracy      : 0.0%
  Baseline prompt        : You are a comprehensive technical database API specialized in exhaustive entity ...
  ------------------------------------------------------------------
  Max rounds             : unlimited
  Candidates per round   : 5
  Queries per eval       : 15 of 984
  Improvement threshold  : 1.0%
  Patience (L1)          : 2 rounds
  L2 (refine context)    : enabled, patience=2
  L3 (modify plan)       : enabled, patience=1
  ------------------------------------------------------------------
  Candidate model        : openai/gpt-oss-120b
  Creativity             : 0.7
  Pipeline               : (default pipeline)
    Excluded             : llm_ranking
  Strategy               : SCAN-AWARE

  ROUND PIPELINE (what happens each round)
  ------------------------------------------------------------------
  1. BASELINE INPUT
     Prompt: You are a comprehensive technical database API specialized in exhaustive entity ...
     Accuracy: 0.0%  |  Prior results: 0
  2. FAILURE ANALYSIS
     Up to 15 failures extracted (currently 0 available)
  3. CONTEXT ASSEMBLY
     Strategy: SCAN-AWARE
     Scan leaderboard: 18 entries
     Top performer: max_token_candidates     10                                       acc=66.7%  delta=+58.3%  hits=2/3
     Sensitivity axes: 9
     Difficulty: Query classes: easy: 0 (0%) | discriminating: 5 (50%) | hard: 5 (50%) | error: 0 (0%)
     Improving axes: 1 (max_token_candidates)
     Tested values: 1 axes with per-value data
  4. LLM CANDIDATE GENERATION
     Model: openai/gpt-oss-120b  |  Temperature: 0.7
     Candidates: 5
     Output: prompt + pipeline_params_override per candidate
  5. BACKEND EVALUATION
     Queries per candidate: 15 of 984
     Scoring: accuracy
  6. WINNER SELECTION
     Criterion: best accuracy >= baseline + 1.0%
  7. LOOP CONTROL
     Patience: 2 stalls → stop  |  L2: enabled, patience=2  |  L3: enabled, patience=1
  ------------------------------------------------------------------
  Est. backend calls     : unlimited  (no max_rounds x 5c x 15q)

  SCAN CONTEXT PREVIEW (injected into LLM meta-prompt)
  ------------------------------------------------------------------
  Leaderboard:
  max_token_candidates     10                                       acc=66.7%  delta=+58.3%  hits=2/3
    query_prefix             ecoinvent                                acc=33.3%  delta=+30.0%  hits=1/3
    raw_content_limit        2500                                     acc=33.3%  delta=+30.0%  hits=1/3
    profiling_temperature    0.0                                      acc=33.3%  delta=+30.0%  hits=1/3
    thinking_style           Consider the most likely interpretation ... acc=33.3%  delta=+30.0%  hits=1/3
    query_prefix             GaBi                                     acc=0.0%  delta=+0.0%  hits=0/3 (baseline)
    num_results              20                                       acc=0.0%  delta=+0.0%  hits=0/3 (baseline)
    max_sites                3                                        acc=0.0%  delta=+0.0%  hits=0/3 (baseline)
    num_results              5                                        acc=0.0%  delta=+0.0%  hits=0/3 (baseline)
    max_sites                7                                        acc=0.0%  delta=+0.0%  hits=0/3 (baseline)
    ... 8 more
  Axis sensitivity:
  1. max_token_candidates     type=pipeline_param sensitivity=0.583  card=3  budget=high  [room: best_delta=+58.3%]
    2. thinking_style           type=prompt_field   sensitivity=0.317  card=3  budget=skip  [room: best_delta=+30.0%]
    3. query_prefix             type=pipeline_param sensitivity=0.300  card=9  budget=skip  [room: best_delta=+30.0%]
    4. profiling_temperature    type=pipeline_param sensitivity=0.300  card=3  budget=skip  [room: best_delta=+30.0%]
    5. raw_content_limit        type=pipeline_param sensitivity=0.300  card=3  budget=skip  [room: best_delta=+30.0%]
    6. max_sites                type=pipeline_param sensitivity=0.000  card=3  budget=skip
    7. num_results              type=pipeline_param sensitivity=0.000  card=3  budget=skip
    8. content_char_limit       type=pipeline_param sensitivity=0.000  card=3  budget=skip
    9. profiling_schema         type=pipeline_param sensitivity=0.000  card=14  budget=skip
  Query difficulty:
  Query classes: easy: 0 (0%) | discriminating: 5 (50%) | hard: 5 (50%) | error: 0 (0%)
  Improving axes: max_token_candidates
  Tested values:
  max_token_candidates (2 values tested):
      [0] 10  acc=66.7%
      [1] 30  acc=0.0% *baseline*
======================================================================

In [10]:
#@title Run optimization (feedback cycle)
dev_reload()

campaign_rounds = await run_optimization_notebook(
    campaign_rounds, eval_data, campaign_config,
    svc=svc, pipeline_params=pipeline_params,
    scan_context=locals().get("scan_context"),
    experiment_id=EXPERIMENT_ID,
    task_context=task_context,
)

2026-04-01 14:26:00 INFO     [api.services.campaign.optimization_loop] Using provided baseline (acc=0.000)
2026-04-01 14:26:00 INFO     [api.services.campaign.campaign_lifecycle] Cycle identity: cycle_e9315d106538
2026-04-01 14:26:00 INFO     [api.services.campaign.campaign_lifecycle] Resuming cycle cycle_e9315d106538 — 7 prior round(s) on disk

  Interrupt of cells can take up to 60 seconds!
  If a dialog pops up, click 'Cancel' and wait 20 seconds.

╔════════════════════════════════════════════════════════════════════╗
║  FEEDBACK CYCLE STARTING                                           ║
╠════════════════════════════════════════════════════════════════════╣
║  Baseline       0.0%                                               ║
║  Max rounds     999            Patience    2                       ║
║  Candidates     5                                                  ║
║  Sample size    15 of 984                                          ║
║  Min detectable ±36.2% (α=0.05, 80% power)                         ║
║  Model          openai/gpt-oss-120b                                ║
║  L2 (refine)    enabled            L3 (plan)   enabled             ║
║  Scan context   YES                                                ║
║  Critique       enabled                                            ║
╚════════════════════════════════════════════════════════════════════╝

2026-04-01 14:26:02 INFO     [api.services.obs.observability_logger] Dataset 'termnorm_ground_truth': 728 items registered, 256 duplicates/empty skipped (from 984 input)
2026-04-01 14:26:02 WARNING  [api.services.obs.observability_logger] Skipping Langfuse cloud dataset registration for 984 items (rate-limit risk). Use the dedicated Langfuse sync cell instead.
2026-04-01 14:26:02 INFO     [api.services.campaign.campaign_lifecycle] Registered 728 dataset items for 'termnorm_ground_truth'
2026-04-01 14:26:02 INFO     [api.services.campaign.optimization_loop] Restored optimizer state from round 6 (critique=0 chars, task_context=6 keys, escalation_journal=0 entries, l2_round=0)
2026-04-01 14:26:02 INFO     [api.services.search.search_memory] SearchMemory refreshed: 6 new runs (total watermark: 206)
2026-04-01 14:26:02 INFO     [api.services.campaign.optimization_loop] Optimization round 0 (clean=0/999, acc=0.000, stall=2/2)
2026-04-01 14:26:02 INFO     [api.services.campaign.round_execution] Loaded 5 persisted candidates for round 0

  ✓ Initialized  cycle=cycle_e9315d  samples=15  obs=ON
    Resumed from round 7 (7 rounds cached)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ROUND 1/999                                               patience 0/2
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

├─ GENERATE ─────────────────────────────────────────────────────────────┤
│  Current best    0.0%
│  Prompt          You are a comprehensive technical database API ...
│  Candidates      8   Creativity: 0.6   Scan: YES   Critique: NO
│  Model           openai/gpt-oss-120b
│  Scan focus: 1 improving axes [max_token_candidates]
├────────────────────────────────────────────────────────────────────────┤
  ✓ 5 candidates generated (loaded from disk)
    C1: Adopt a semantic‑focused thinking style to bett... [instruction]
    C2: Prepend an LCA‑specific query prefix to steer t... [instruction]
    C3: Raise profiling temperature to 0.7 to encourage... [instruction]
    C4: Increase raw content limit to 20000 characters ... [instruction]
    C5: Expand max_sites to 10 to broaden source covera... [instruction]

│  Settings diff (6 params, 7 SPs):
│                         Start   Parent  C1      C2      C3      C4      C5
│  ─── web_search ────────
│              max_sites  -       -       -       -       -       -       10
│           query_prefix  -       -       -       LCA:    -       -       -
│  ─── entity_profiling ──
│  profiling_temperature  -       -       -       -       0.7     -       -
│      raw_content_limit  -       -       -       -       -       20000   -
│       entity_profiling  -       [a]     ·       ·       ·       ·       ·
│         thinking_style  -       -       [b]     -       -       -       -
│
│  Values:
│    [a] {'prompt': "You are a comprehensive technical database API specialized in exhaustive entity profiling.\n\nExtract all possible information about a given query from research data and return it in a prescribed JSON format, including US/GB spelling variants, a single defining conceptual word, professional classification aliases, and detailed technical attributes.\n\nGiven a product or technical description query, parse unstructured research text to retrieve explicit specifications, infer implicit materials, processes, applications, and generate exhaustive arrays with spelling variants while identifying the core activity word.\n\nExtract ALL possible information about '{{query}}' from the research data and return it in this exact JSON format: {{format_string}}. In ALL arrays, after each term, immediately add its US/GB spelling variant if different. Identify the single word that defines the conceptual essence (the activity, method, or process). Generate the full spectrum of expert-level classification aliases. Provide explicit information, implicit information, manufacturing processes, material composition, and applications & use cases, maximizing diversity (5‑10+ items per array) and prioritizing completeness.\n\nThink step by step, first gather explicit data, then infer implicit attributes, then generate spelling variants, finally select the defining word and compile the final JSON.\n\nA single JSON object matching the provided {{format_string}}, with all array fields populated with US/GB variants and a separate field for the defining word."}
│    [b] semantic_focus

├─ EVALUATE ───────────────────────────────────────── 5 × 15 = 75 calls ─┤
  [  1]  18.8s MISS 1/5    [llm] 📖  PA66-GF25 ULTRAMID A3UG5 RAL7035 grey          -> Aluminium, wrought alloy {GLO}| mar
                    ⚠ llm_ranking: Token limit error (max_tokens=4000) — retried without limit

2026-04-01 14:26:02 WARNING  [api.services.campaign.optimization_loop] Escalation 'degradation' at round 0 — target=l2, degraded_rate=100.0%

  ┌─ C1/5 ───────────────────────────────────── 0.0% [0.0%-79.3%] ─┐
  │  Adopt a semantic‑focused thinking style to...  thinking_style: semantic_focus│
  │  0/1 hits  ⚠ aborted at 1/15  composite=0.0500  ⚠ 1/1 degraded  vs baseline: +0.0%│
  │  best so far: C1 0.0%                                          │
  └────────────────────────────────────────────────────────────────┘
  ┌─ SCOREBOARD ───────────────────────────────────────────────────────────────┐
  │  #   Label    Accuracy            95% CI  Composite    Delta               │
  │  1   C1          0.0%       [0.0%-79.3%]     0.0500       ---  (aborted)   │
  └────────────────────────────────────────────────────────────────────────────┘
  ⚠ NO IMPROVEMENT  best candidate 0.0%

├─ ESCALATION ──────────────────────────────────────── degradation → l2 ─┤
│  Degraded: 100% of queries
│  llm_ranking:llm_retry: 1 occurrences
├────────────────────────────────────────────────────────────────────────┤

├─ L2 REFINE CONTEXT ─────────────────────────────────────── L2 round 0 ─┤
│  L1 stalled 2 rounds  |  acc=0.0%  best=0.0%
│  Current params: creativity=0.6, n_variants=8, sample_size=30, variant_strategy=diverse
│  LLM analyzing failure patterns...
├────────────────────────────────────────────────────────────────────────┤

2026-04-01 14:26:04 INFO     [api.services.campaign.layer_transitions] L2 refine_context: 3 param changes, task_context updated, action=probe, directive=258 chars
2026-04-01 14:26:04 INFO     [api.services.campaign.escalation] L2 requested probe — next round uses warned queries
2026-04-01 14:26:04 INFO     [api.services.campaign.escalation] L2 refine_context at round 0 (l2_round=1)
2026-04-01 14:26:04 INFO     [api.services.stores.campaign_store] Deleted cached candidates for round 1 (escalation invalidation)
2026-04-01 14:26:04 INFO     [api.services.campaign.optimization_loop] PROBE round 1: 0 warned queries (from 0 tracked)
2026-04-01 14:26:04 INFO     [api.services.campaign.optimization_loop] Optimization round 1 (clean=0/999, acc=0.000, stall=2/2, PROBE)

  ✓ L2 decision: 4 param changes, task_context updated, action=probe
    L2: The llm_ranking stage is completely unstable; adjusting temperatures and variant

  --- L2 PROMPT (sent to LLM) ---
  │ You are a prompt optimization expert.
  │
  │ The L1 inner optimization loop has stalled — candidates are no longer improving.
  │
  │ CURRENT PROMPT:
  │ ---
  │ You are a comprehensive technical database API specialized in exhaustive entity profiling.
  │
  │ Extract all possible information about a given query from research data and return it in a prescribed JSON format, including US/GB spelling variants, a single defining conceptual word, professional classification aliases, and detailed technical attributes.
  │
  │ Given a product or technical description query, parse unstructured research text to retrieve explicit specifications, infer implicit materials, processes, applications, and generate exhaustive arrays with spelling variants while identifying the core activity word.
  │
  │ Extract ALL possible information about '{{query}}' from the research data and return it in this exact JSON format: {{format_string}}. In ALL arrays, after each term, immediately add its US/GB spelling variant if different. Identify the single word that defines the conceptual essence (the activity, method, or process). Generate the full spectrum of expert-level classification aliases. Provide explicit information, implicit information, manufacturing processes, material composition, and applications & use cases, maximizing diversity (5‑10+ items per array) and prioritizing completeness.
  │
  │ Think step by step, first gather explicit data, then infer implicit attributes, then generate spelling variants, finally select the defining word and compile the final JSON.
  │
  │ A single JSON object matching the provided {{format_string}}, with all array fields populated with US/GB variants and a separate field for the defining word.
  │
  │ Shift from a purely deterministic, rule‑based extraction pipeline to a hybrid approach that first uses a high‑recall, semantic search (e.g., dense vector retrieval) to gather a broad set of candidate passages, then applies a fine‑tuned LLM for entity profiling with chain‑of‑thought prompting. Introduce a multi‑stage ranking where the first stage filters by semantic similarity, the second stage uses a lightweight classifier to flag passages with explicit specs, and a final LLM re‑ranks by completeness of the required JSON fields. Parallelize the web search and fuzzy matching steps to increase coverage, and enforce a post‑processing step that programmatically generates US/GB spelling variants rather than relying on the LLM, guaranteeing consistency and reducing token load.
  │ ---
  │
  │ CURRENT OPTIMIZER PARAMS: {"creativity": 0.6, "n_variants": 8, "sample_size": 30, "variant_strategy": "diverse"}
  │
  │
  │ TASK CONTEXT (structured domain understanding — refine if inaccurate):
  │ {
  │   "domain": "Life Cycle Assessment (LCA) terminology and database normalization",
  │   "pipeline_purpose": "Normalize free\u2011form user inputs into standardized LCA database entries (e.g., ecoinvent, GaBi) or correctly flag no\u2011match cases.",
  │   "data_characteristics": "Unstructured textual inputs containing material codes, standards, brand names, chemical formulas, qualifiers, and geographic tags; mixed English/German/French; variable volume per project.",
  │   "optimization_goals": "Maximize correct match rate while minimizing false positives; correctly identify no\u2011match cases; handle synonyms, variants, and geographic scopes; decompose composite inputs when possible.",
  │   "key_challenges": "Structural mismatch between shorthand and rigid database names; need for domain knowledge to decode brands, standards, and codes; synonym and naming evolution; multiple geographic variants; inputs with no corresponding entry; composite material decomposition.",
  │   "raw_description": "# Domain Context: Life Cycle Assessment (LCA) Terminology\n\nThis document captures the real-world input patterns and matching challenges that TermNorm's normalization pipeline must handle when working with LCA databases (ecoinvent, GaBi, etc.).\n\n## Free-form input characteristics\n\nUsers type cryptic shorthand drawn from industrial standards, trade catalogs, and chemical nomenclature. These inputs must be matched to rigidly formatted database entries.\n\n### Industrial material codes\n- Alloy designations: `CuZn36-MS-63-FS material no. 2.0335`, `EN AW-AL99,5 H14`\n- Werkstoff numbers: `2.0335`, `1.4301`\n- Temper/condition suffixes: `H14`, `T6`, `FS`\n\n### Standard references\n- DIN/ISO/IEC codes that encode material identity indirectly: `DIN 55468-1`, `IEC 60317-29`, `ISO 898-1`\n- The standard number implies a material class (e.g., ISO 898-1 = carbon steel fasteners) but doesn't name it\n\n### Brand and trade names\n- Proprietary names requiring domain knowledge to decode:\n  - `Makrolon 2805` = polycarbonate (Covestro)\n  - `Ultramid A3SK` = PA66 (BASF)\n  - `Delrin 500P` = POM/acetal (DuPont)\n- Grade suffixes (`2805`, `A3SK`) distinguish variants but don't appear in LCA databases\n\n### Chemical shorthand\n- Polymer blends with fillers: `PA66+6-GFR30` (polyamide 66/6 blend, 30% glass fiber reinforced)\n- Contact materials: `AgC3` (silver-graphite composite)\n- Truncated IUPAC names, CAS numbers, chemical formulas embedded in free text\n\n### Agricultural qualifiers\n- Farming systems: `IP` (integrated production), `\u00d6LN` (proof of ecological performance), `organic`\n- Supply chain stages: `at farm`, `at plant`, `at household`, `at regional storage`\n- These qualifiers select among variants of the same product in the database\n\n### Geographic scoping\n- ecoinvent geography codes: `{GLO}` (global), `{RER}` (Europe), `{RNA}` (North America), `{CH}` (Switzerland)\n- SimaPro-style suffixes: `/CH U`, `/RER S`\n- The same product exists as multiple geographic variants; the correct match depends on project scope\n\n### Mixed languages and formats\n- German/French/English terms mixed within a single input\n- Abbreviated units and quantities inline with material names\n- Free-text notes appended to technical identifiers\n\n## Matching challenges\n\n### Structural mismatch\nInputs are unstructured shorthand; targets are rigidly formatted database entries with fixed naming conventions (e.g., `market for polyethylene, high density | polyethylene, high density | cut-off, U - RER`). No simple string similarity bridges this gap reliably.\n\n### Domain knowledge required\n- Brand names must be decoded: `Makrolon` requires knowing it's Covestro's polycarbonate brand\n- Material composition codes don't appear in targets: `CuZn36` must be recognized as brass\n- Standards references encode identity indirectly: `ISO 898-1` implies carbon steel, not a named material\n\n### Synonym and naming evolution\n- Database entries evolve across versions: `Arsenic` becomes `Arsenic, ion`\n- Multiple valid names for the same substance: `aluminium` vs `aluminum`, `glass fibre` vs `glass fiber`\n- Abbreviations vs full names: `PP` vs `polypropylene`, `PET` vs `polyethylene terephthalate`\n\n### Geographic variants\n- Identical products exist with different geography tags\n- Selecting the right variant depends on project context, not just the input text\n\n### No-match inputs\n- Some inputs have no corresponding database entry (indicated by `--` in ground truth)\n- The pipeline must recognize when no match exists rather than forcing a low-quality match\n\n### Compositional inputs\n- Inputs describing blends or composites (`PA66+6-GFR30`) may need to be decomposed into constituent materials\n- The database may have the base polymer but not the specific filled/reinforced variant\n"
  │ }
  │ AVAILABLE PIPELINE PARAMETERS (in pipeline execution order):
  │
  │   fuzzy_matching: fuzzy_scorer, fuzzy_threshold
  │     current: {"fuzzy_threshold": "?", "fuzzy_scorer": "?"}
  │
  │   web_search: content_char_limit, max_sites, num_results, query_prefix, query_suffix
  │     current: {"query_prefix": "?", "max_sites": "?", "query_suffix": "?", "num_results": "?", "content_char_limit": "?"}
  │
  │   entity_profiling: profiling_max_tokens, profiling_model, profiling_prompt, profiling_schema, profiling_temperature, raw_content_limit
  │     current: {"profiling_prompt": "?", "raw_content_limit": "?", "profiling_schema": "?", "profiling_temperature": "?", "profiling_model": "?", "profiling_max_tokens": "?"}
  │
  │   token_matching: max_token_candidates
  │     current: {"max_token_candidates": "?"}
  │
  │   llm_ranking: ranking_max_tokens, ranking_model, ranking_prompt, ranking_sample_size, ranking_schema, ranking_temperature, relevance_weight_core
  │     current: {"ranking_schema": "?", "ranking_model": "?", "ranking_sample_size": "?", "ranking_max_tokens": "?", "ranking_prompt": "?", "relevance_weight_core": "?", "ranking_temperature": "?"}
  │
  │
  │
  │ PIPELINE STABILITY REPORT (llm_ranking):
  │
  │   Current degradation: 100% of queries (llm_ranking:llm_retry (1))
  │
  │   Tried configs and stability:
  │     Round 0: llm_ranking [defaults] | 100% degraded
  │
  │   Available llm_ranking parameters: ranking_max_tokens, ranking_model, ranking_prompt, ranking_sample_size, ranking_schema, ranking_temperature, relevance_weight_core
  │   The configurations above are all unstable. Suggest different parameter values to stabilize the pipeline.
  │
  │
  │
  │ HISTORICAL INTELLIGENCE:
  │   Axis impact rankings: profiling_schema.required (effect=0.356, consistently_impactful); raw_content_limit (effect=0.267, consistently_impactful); token_matching.max_token_candidates (effect=0.222, consistently_impactful); query_prefix (effect=0.213, consistently_impactful); entity_profiling.temperature (effect=0.208, consistently_impactful)
  │   Bottleneck distribution: token_matching: 93%; llm_ranking: 7%; unknown: 0%
  │
  │ Analyze the failure patterns from the critique and recommend changes. You can adjust:
  │ - optimizer_params (creativity, n_variants, sample_size, variant_strategy)
  │ - task_context (refine domain, pipeline_purpose, data_characteristics, optimization_goals, key_challenges)
  │ Note: L1 Generate makes the final decision on pipeline_params (query_prefix, max_sites, etc.). Your job is to set the situation so L1 makes better choices.
  │ Your "directive" field will be injected into the next candidate generation prompt as primary guidance — make it specific and actionable.
  │ Focus on what will have the biggest impact on accuracy.
  │
  │
  │ Return a JSON object with:
  │   "optimizer_params": dict of meta-setting changes (creativity, n_variants, sample_size — or {} to keep current)
  │   "task_context": dict of refined domain fields (or {} to keep current)
  │   "action": "continue" (normal L1 cycle) or "probe" (test warned queries with new settings first)
  │   "directive": 2-3 sentence instruction for the next candidate generator — what to focus on and why (this will be injected into the generation prompt as additional guidance)
  │   "rationale": 1-2 sentence explanation
  │
  │ Note: L1 Generate makes the final decision on pipeline_params. Your job is to refine the situation context and meta-settings so L1 makes better choices.
  │ Use your judgment on when to set action to "probe" vs "continue" based on the data above.
  --- END PROMPT ---

  --- L2 RESPONSE (raw JSON) ---
  │ {
  │   "optimizer_params": {
  │     "creativity": 0.4,
  │     "n_variants": 4,
  │     "sample_size": 40
  │   },
  │   "task_context": {
  │     "pipeline_purpose": "Normalize free-form LCA inputs with deterministic matching, using LLM only for entity profiling at low temperature",
  │     "key_challenges": "Reduce reliance on unstable LLM ranking, prioritize fuzzy matching and rule\u2011based ranking, ensure consistent US/GB variant generation"
  │   },
  │   "action": "probe",
  │   "directive": "Focus on lowering the entity profiling temperature and reducing the number of LLM\u2011generated variants; increase raw content limit and token candidate count to improve recall, and temporarily disable or simplify the llm_ranking stage to a deterministic filter.",
  │   "rationale": "The llm_ranking stage is completely unstable; adjusting temperatures and variant counts and emphasizing deterministic steps should improve stability."
  │ }
  --- END RESPONSE ---

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ROUND 2/999                                               patience 0/2
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

├─ GENERATE ─────────────────────────────────────────────────────────────┤
│  Current best    0.0%
│  Prompt          You are a comprehensive technical database API ...
│  Candidates      4   Creativity: 0.4   Scan: YES   Critique: NO
│  Model           openai/gpt-oss-120b
│  Scan focus: 1 improving axes [max_token_candidates]
├────────────────────────────────────────────────────────────────────────┤

2026-04-01 14:26:10 INFO     [api.services.stores.campaign_store] Saved 4 candidates for round 1 → round_0001_candidates.json

  ✓ 4 candidates generated (from LLM)
    C1: Raise max_token_candidates to broaden candidate... [instruction]
    C2: Increase raw_content_limit to allow processing ... [instruction]
    C3: Add extra fields to profiling_schema to capture... [instruction]
    C4: Switch thinking_style to a detailed chain‑of‑th... [instruction]

│  Settings diff (5 params, 6 SPs):
│                        Start   Parent  C1      C2      C3      C4
│  ─── entity_profiling ─
│      profiling_schema  -       -       -       -       [a]     -
│     raw_content_limit  -       -       -       20000   -       -
│  ─── token_matching ───
│  max_token_candidates  -       -       10      -       -       -
│      entity_profiling  -       [b]     ·       ·       ·       ·
│        thinking_style  -       -       -       -       -       [c]
│
│  Values:
│    [a] ['entity_name', 'core_concept', 'distinguishing_features', 'key_properties', 'technical_specifications', 'material_composition', 'manufacturing_processes', 'applications', 'classification_aliases']
│    [b] {'prompt': "You are a comprehensive technical database API specialized in exhaustive entity profiling.\n\nExtract all possible information about a given query from research data and return it in a prescribed JSON format, including US/GB spelling variants, a single defining conceptual word, professional classification aliases, and detailed technical attributes.\n\nGiven a product or technical description query, parse unstructured research text to retrieve explicit specifications, infer implicit materials, processes, applications, and generate exhaustive arrays with spelling variants while identifying the core activity word.\n\nExtract ALL possible information about '{{query}}' from the research data and return it in this exact JSON format: {{format_string}}. In ALL arrays, after each term, immediately add its US/GB spelling variant if different. Identify the single word that defines the conceptual essence (the activity, method, or process). Generate the full spectrum of expert-level classification aliases. Provide explicit information, implicit information, manufacturing processes, material composition, and applications & use cases, maximizing diversity (5‑10+ items per array) and prioritizing completeness.\n\nThink step by step, first gather explicit data, then infer implicit attributes, then generate spelling variants, finally select the defining word and compile the final JSON.\n\nA single JSON object matching the provided {{format_string}}, with all array fields populated with US/GB variants and a separate field for the defining word.\n\nShift from a purely deterministic, rule‑based extraction pipeline to a hybrid approach that first uses a high‑recall, semantic search (e.g., dense vector retrieval) to gather a broad set of candidate passages, then applies a fine‑tuned LLM for entity profiling with chain‑of‑thought prompting. Introduce a multi‑stage ranking where the first stage filters by semantic similarity, the second stage uses a lightweight classifier to flag passages with explicit specs, and a final LLM re‑ranks by completeness of the required JSON fields. Parallelize the web search and fuzzy matching steps to increase coverage, and enforce a post‑processing step that programmatically generates US/GB spelling variants rather than relying on the LLM, guaranteeing consistency and reducing token load."}
│    [c] detailed_chain_of_thought

├─ EVALUATE ─────────────────────────────────────────── 4 × 0 = 0 calls ─┤

  ┌─ C1/4 ────────────────────────────────────── 0.0% [0.0%-0.0%] ─┐
  │  Raise max_token_candidates to broaden cand...  max_token_candidates: 10│
  │  0/0 hits  vs baseline: +0.0%                                  │
  │  best so far: C1 0.0%                                          │
  └────────────────────────────────────────────────────────────────┘

  ┌─ C2/4 ────────────────────────────────────── 0.0% [0.0%-0.0%] ─┐
  │  Increase raw_content_limit to allow proces...  raw_content_limit: 20000│
  │  0/0 hits  vs baseline: +0.0%                                  │
  │  best so far: C1 0.0%                                          │
  └────────────────────────────────────────────────────────────────┘

  ┌─ C3/4 ────────────────────────────────────── 0.0% [0.0%-0.0%] ─┐
  │  Add extra fields to profiling_schema to ca...  pp=[profiling_schema]│
  │  0/0 hits  vs baseline: +0.0%                                  │
  │  best so far: C1 0.0%                                          │
  └────────────────────────────────────────────────────────────────┘

  ┌─ C4/4 ────────────────────────────────────── 0.0% [0.0%-0.0%] ─┐
  │  Switch thinking_style to a detailed chain‑...  thinking_style: detailed_chain_of_thought│
  │  0/0 hits  vs baseline: +0.0%                                  │
  │  best so far: C1 0.0%                                          │
  └────────────────────────────────────────────────────────────────┘
  ┌─ SCOREBOARD ───────────────────────────────────────────────────────────────┐
  │  #   Label    Accuracy            95% CI    Delta                          │
  │  1   C1          0.0%        [0.0%-0.0%]       ---  *                      │
  │  2   C2          0.0%        [0.0%-0.0%]       ---                         │
  │  3   C3          0.0%        [0.0%-0.0%]       ---                         │
  │  4   C4          0.0%        [0.0%-0.0%]       ---                         │
  └────────────────────────────────────────────────────────────────────────────┘
  ⚠ NO IMPROVEMENT  best candidate 0.0%

├─ L2 REFINE CONTEXT ─────────────────────────────────────── L2 round 1 ─┤
│  L1 stalled 2 rounds  |  acc=0.0%  best=0.0%
│  Current params: creativity=0.4, n_variants=4, sample_size=40, variant_strategy=diverse
│  LLM analyzing failure patterns...
├────────────────────────────────────────────────────────────────────────┤

2026-04-01 14:26:12 INFO     [api.services.campaign.layer_transitions] L2 refine_context: 3 param changes, task_context updated, action=probe, directive=290 chars
2026-04-01 14:26:12 INFO     [api.services.campaign.escalation] L2 requested probe — next round uses warned queries
2026-04-01 14:26:12 INFO     [api.services.campaign.escalation] L2 refine_context at round 1 (l2_round=2)
2026-04-01 14:26:12 INFO     [api.services.campaign.optimization_loop] PROBE round 2: 0 warned queries (from 0 tracked)
2026-04-01 14:26:12 INFO     [api.services.campaign.optimization_loop] Optimization round 2 (clean=1/999, acc=0.000, stall=2/2, PROBE)
2026-04-01 14:26:12 INFO     [api.services.campaign.round_execution] Loaded 5 persisted candidates for round 2
2026-04-01 14:26:12 INFO     [api.services.campaign.escalation] L3 patience exhausted (1 stalls) at round 2

  ✓ L2 decision: 4 param changes, task_context updated, action=probe
    L2: A broader candidate pool and clearer focus on decomposition and variant handling

  --- L2 PROMPT (sent to LLM) ---
  │ You are a prompt optimization expert.
  │
  │ The L1 inner optimization loop has stalled — candidates are no longer improving.
  │
  │ CURRENT PROMPT:
  │ ---
  │ You are a comprehensive technical database API specialized in exhaustive entity profiling.
  │
  │ Extract all possible information about a given query from research data and return it in a prescribed JSON format, including US/GB spelling variants, a single defining conceptual word, professional classification aliases, and detailed technical attributes.
  │
  │ Given a product or technical description query, parse unstructured research text to retrieve explicit specifications, infer implicit materials, processes, applications, and generate exhaustive arrays with spelling variants while identifying the core activity word.
  │
  │ Extract ALL possible information about '{{query}}' from the research data and return it in this exact JSON format: {{format_string}}. In ALL arrays, after each term, immediately add its US/GB spelling variant if different. Identify the single word that defines the conceptual essence (the activity, method, or process). Generate the full spectrum of expert-level classification aliases. Provide explicit information, implicit information, manufacturing processes, material composition, and applications & use cases, maximizing diversity (5‑10+ items per array) and prioritizing completeness.
  │
  │ Think step by step, first gather explicit data, then infer implicit attributes, then generate spelling variants, finally select the defining word and compile the final JSON.
  │
  │ A single JSON object matching the provided {{format_string}}, with all array fields populated with US/GB variants and a separate field for the defining word.
  │
  │ Shift from a purely deterministic, rule‑based extraction pipeline to a hybrid approach that first uses a high‑recall, semantic search (e.g., dense vector retrieval) to gather a broad set of candidate passages, then applies a fine‑tuned LLM for entity profiling with chain‑of‑thought prompting. Introduce a multi‑stage ranking where the first stage filters by semantic similarity, the second stage uses a lightweight classifier to flag passages with explicit specs, and a final LLM re‑ranks by completeness of the required JSON fields. Parallelize the web search and fuzzy matching steps to increase coverage, and enforce a post‑processing step that programmatically generates US/GB spelling variants rather than relying on the LLM, guaranteeing consistency and reducing token load.
  │ ---
  │
  │ CURRENT OPTIMIZER PARAMS: {"creativity": 0.4, "n_variants": 4, "sample_size": 40, "variant_strategy": "diverse"}
  │
  │
  │ TASK CONTEXT (structured domain understanding — refine if inaccurate):
  │ {
  │   "domain": "Life Cycle Assessment (LCA) terminology and database normalization",
  │   "pipeline_purpose": "Normalize free\u2011form user inputs into standardized LCA database entries (e.g., ecoinvent, GaBi) or correctly flag no\u2011match cases.",
  │   "data_characteristics": "Unstructured textual inputs containing material codes, standards, brand names, chemical formulas, qualifiers, and geographic tags; mixed English/German/French; variable volume per project.",
  │   "optimization_goals": "Maximize correct match rate while minimizing false positives; correctly identify no\u2011match cases; handle synonyms, variants, and geographic scopes; decompose composite inputs when possible.",
  │   "key_challenges": "Structural mismatch between shorthand and rigid database names; need for domain knowledge to decode brands, standards, and codes; synonym and naming evolution; multiple geographic variants; inputs with no corresponding entry; composite material decomposition.",
  │   "raw_description": "# Domain Context: Life Cycle Assessment (LCA) Terminology\n\nThis document captures the real-world input patterns and matching challenges that TermNorm's normalization pipeline must handle when working with LCA databases (ecoinvent, GaBi, etc.).\n\n## Free-form input characteristics\n\nUsers type cryptic shorthand drawn from industrial standards, trade catalogs, and chemical nomenclature. These inputs must be matched to rigidly formatted database entries.\n\n### Industrial material codes\n- Alloy designations: `CuZn36-MS-63-FS material no. 2.0335`, `EN AW-AL99,5 H14`\n- Werkstoff numbers: `2.0335`, `1.4301`\n- Temper/condition suffixes: `H14`, `T6`, `FS`\n\n### Standard references\n- DIN/ISO/IEC codes that encode material identity indirectly: `DIN 55468-1`, `IEC 60317-29`, `ISO 898-1`\n- The standard number implies a material class (e.g., ISO 898-1 = carbon steel fasteners) but doesn't name it\n\n### Brand and trade names\n- Proprietary names requiring domain knowledge to decode:\n  - `Makrolon 2805` = polycarbonate (Covestro)\n  - `Ultramid A3SK` = PA66 (BASF)\n  - `Delrin 500P` = POM/acetal (DuPont)\n- Grade suffixes (`2805`, `A3SK`) distinguish variants but don't appear in LCA databases\n\n### Chemical shorthand\n- Polymer blends with fillers: `PA66+6-GFR30` (polyamide 66/6 blend, 30% glass fiber reinforced)\n- Contact materials: `AgC3` (silver-graphite composite)\n- Truncated IUPAC names, CAS numbers, chemical formulas embedded in free text\n\n### Agricultural qualifiers\n- Farming systems: `IP` (integrated production), `\u00d6LN` (proof of ecological performance), `organic`\n- Supply chain stages: `at farm`, `at plant`, `at household`, `at regional storage`\n- These qualifiers select among variants of the same product in the database\n\n### Geographic scoping\n- ecoinvent geography codes: `{GLO}` (global), `{RER}` (Europe), `{RNA}` (North America), `{CH}` (Switzerland)\n- SimaPro-style suffixes: `/CH U`, `/RER S`\n- The same product exists as multiple geographic variants; the correct match depends on project scope\n\n### Mixed languages and formats\n- German/French/English terms mixed within a single input\n- Abbreviated units and quantities inline with material names\n- Free-text notes appended to technical identifiers\n\n## Matching challenges\n\n### Structural mismatch\nInputs are unstructured shorthand; targets are rigidly formatted database entries with fixed naming conventions (e.g., `market for polyethylene, high density | polyethylene, high density | cut-off, U - RER`). No simple string similarity bridges this gap reliably.\n\n### Domain knowledge required\n- Brand names must be decoded: `Makrolon` requires knowing it's Covestro's polycarbonate brand\n- Material composition codes don't appear in targets: `CuZn36` must be recognized as brass\n- Standards references encode identity indirectly: `ISO 898-1` implies carbon steel, not a named material\n\n### Synonym and naming evolution\n- Database entries evolve across versions: `Arsenic` becomes `Arsenic, ion`\n- Multiple valid names for the same substance: `aluminium` vs `aluminum`, `glass fibre` vs `glass fiber`\n- Abbreviations vs full names: `PP` vs `polypropylene`, `PET` vs `polyethylene terephthalate`\n\n### Geographic variants\n- Identical products exist with different geography tags\n- Selecting the right variant depends on project context, not just the input text\n\n### No-match inputs\n- Some inputs have no corresponding database entry (indicated by `--` in ground truth)\n- The pipeline must recognize when no match exists rather than forcing a low-quality match\n\n### Compositional inputs\n- Inputs describing blends or composites (`PA66+6-GFR30`) may need to be decomposed into constituent materials\n- The database may have the base polymer but not the specific filled/reinforced variant\n"
  │ }
  │ AVAILABLE PIPELINE PARAMETERS (in pipeline execution order):
  │
  │   fuzzy_matching: fuzzy_scorer, fuzzy_threshold
  │     current: {"fuzzy_threshold": "?", "fuzzy_scorer": "?"}
  │
  │   web_search: content_char_limit, max_sites, num_results, query_prefix, query_suffix
  │     current: {"query_prefix": "?", "max_sites": "?", "query_suffix": "?", "num_results": "?", "content_char_limit": "?"}
  │
  │   entity_profiling: profiling_max_tokens, profiling_model, profiling_prompt, profiling_schema, profiling_temperature, raw_content_limit
  │     current: {"profiling_prompt": "?", "raw_content_limit": "?", "profiling_schema": "?", "profiling_temperature": "?", "profiling_model": "?", "profiling_max_tokens": "?"}
  │
  │   token_matching: max_token_candidates
  │     current: {"max_token_candidates": "?"}
  │
  │   llm_ranking: ranking_max_tokens, ranking_model, ranking_prompt, ranking_sample_size, ranking_schema, ranking_temperature, relevance_weight_core
  │     current: {"ranking_schema": "?", "ranking_model": "?", "ranking_sample_size": "?", "ranking_max_tokens": "?", "ranking_prompt": "?", "relevance_weight_core": "?", "ranking_temperature": "?"}
  │
  │
  │
  │ HISTORICAL INTELLIGENCE:
  │   Axis impact rankings: profiling_schema.required (effect=0.356, consistently_impactful); raw_content_limit (effect=0.267, consistently_impactful); token_matching.max_token_candidates (effect=0.222, consistently_impactful); query_prefix (effect=0.213, consistently_impactful); entity_profiling.temperature (effect=0.208, consistently_impactful)
  │   Bottleneck distribution: token_matching: 93%; llm_ranking: 7%; unknown: 0%
  │
  │ Analyze the failure patterns from the critique and recommend changes. You can adjust:
  │ - optimizer_params (creativity, n_variants, sample_size, variant_strategy)
  │ - task_context (refine domain, pipeline_purpose, data_characteristics, optimization_goals, key_challenges)
  │ Note: L1 Generate makes the final decision on pipeline_params (query_prefix, max_sites, etc.). Your job is to set the situation so L1 makes better choices.
  │ Your "directive" field will be injected into the next candidate generation prompt as primary guidance — make it specific and actionable.
  │ Focus on what will have the biggest impact on accuracy.
  │
  │
  │ Return a JSON object with:
  │   "optimizer_params": dict of meta-setting changes (creativity, n_variants, sample_size — or {} to keep current)
  │   "task_context": dict of refined domain fields (or {} to keep current)
  │   "action": "continue" (normal L1 cycle) or "probe" (test warned queries with new settings first)
  │   "directive": 2-3 sentence instruction for the next candidate generator — what to focus on and why (this will be injected into the generation prompt as additional guidance)
  │   "rationale": 1-2 sentence explanation
  │
  │ Note: L1 Generate makes the final decision on pipeline_params. Your job is to refine the situation context and meta-settings so L1 makes better choices.
  │ Use your judgment on when to set action to "probe" vs "continue" based on the data above.
  --- END PROMPT ---

  --- L2 RESPONSE (raw JSON) ---
  │ {
  │   "optimizer_params": {
  │     "creativity": 0.6,
  │     "n_variants": 6,
  │     "sample_size": 80
  │   },
  │   "task_context": {
  │     "key_challenges": "Emphasize composite decomposition, synonym handling, geographic variant selection, and explicit no\u2011match detection. Require programmatic US/GB spelling variant generation and prioritize high\u2011recall semantic retrieval before filtering."
  │   },
  │   "action": "probe",
  │   "directive": "Increase the breadth of candidate generation by raising sample_size and n_variants, and guide the next prompt to prioritize high\u2011recall semantic search and richer token\u2011matching (more candidates, lower fuzzy threshold). Emphasize handling of composite materials and explicit no\u2011match cases.",
  │   "rationale": "A broader candidate pool and clearer focus on decomposition and variant handling should break the stall and improve matching accuracy."
  │ }
  --- END RESPONSE ---

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ROUND 3/999                                               patience 0/2
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

├─ GENERATE ─────────────────────────────────────────────────────────────┤
│  Current best    0.0%
│  Prompt          You are a comprehensive technical database API ...
│  Candidates      6   Creativity: 0.6   Scan: YES   Critique: NO
│  Model           openai/gpt-oss-120b
│  Scan focus: 1 improving axes [max_token_candidates]
├────────────────────────────────────────────────────────────────────────┤
  ✓ 5 candidates generated (loaded from disk)
    C1: Increase max_sites to capture more source docum... [instruction]
    C2: Raise max_token_candidates to broaden token mat... [instruction]
    C3: Increase raw_content_limit to retrieve longer e... [instruction]
    C4: Set profiling_temperature to 0.7 to encourage b... [instruction]
    C5: Add extra fields to profiling_schema to capture... [instruction]

│  Settings diff (6 params, 7 SPs):
│                         Start   Parent  C1      C2      C3      C4      C5
│  ─── web_search ────────
│              max_sites  -       -       20      -       -       -       -
│  ─── entity_profiling ──
│       profiling_schema  -       -       -       -       -       -       [a]
│  profiling_temperature  -       -       -       -       -       0.7     -
│      raw_content_limit  -       -       -       -       10      -       -
│  ─── token_matching ────
│   max_token_candidates  -       -       -       15      -       -       -
│       entity_profiling  -       [b]     ·       ·       ·       ·       ·
│
│  Values:
│    [a] {'required': ['explicit_specifications', 'implicit_materials', 'manufacturing_processes', 'material_composition', 'applications', 'geographic_scope', 'application_context']}
│    [b] {'prompt': "You are a comprehensive technical database API specialized in exhaustive entity profiling.\n\nExtract all possible information about a given query from research data and return it in a prescribed JSON format, including US/GB spelling variants, a single defining conceptual word, professional classification aliases, and detailed technical attributes.\n\nGiven a product or technical description query, parse unstructured research text to retrieve explicit specifications, infer implicit materials, processes, applications, and generate exhaustive arrays with spelling variants while identifying the core activity word.\n\nExtract ALL possible information about '{{query}}' from the research data and return it in this exact JSON format: {{format_string}}. In ALL arrays, after each term, immediately add its US/GB spelling variant if different. Identify the single word that defines the conceptual essence (the activity, method, or process). Generate the full spectrum of expert-level classification aliases. Provide explicit information, implicit information, manufacturing processes, material composition, and applications & use cases, maximizing diversity (5‑10+ items per array) and prioritizing completeness.\n\nThink step by step, first gather explicit data, then infer implicit attributes, then generate spelling variants, finally select the defining word and compile the final JSON.\n\nA single JSON object matching the provided {{format_string}}, with all array fields populated with US/GB variants and a separate field for the defining word.\n\nShift from a purely deterministic, rule‑based extraction pipeline to a hybrid approach that first uses a high‑recall, semantic search (e.g., dense vector retrieval) to gather a broad set of candidate passages, then applies a fine‑tuned LLM for entity profiling with chain‑of‑thought prompting. Introduce a multi‑stage ranking where the first stage filters by semantic similarity, the second stage uses a lightweight classifier to flag passages with explicit specs, and a final LLM re‑ranks by completeness of the required JSON fields. Parallelize the web search and fuzzy matching steps to increase coverage, and enforce a post‑processing step that programmatically generates US/GB spelling variants rather than relying on the LLM, guaranteeing consistency and reducing token load."}

├─ EVALUATE ─────────────────────────────────────────── 5 × 0 = 0 calls ─┤

  ┌─ C1/5 ────────────────────────────────────── 0.0% [0.0%-0.0%] ─┐
  │  Increase max_sites to capture more source ...  max_sites: 20  │
  │  0/0 hits  vs baseline: +0.0%                                  │
  │  best so far: C1 0.0%                                          │
  └────────────────────────────────────────────────────────────────┘

  ┌─ C2/5 ────────────────────────────────────── 0.0% [0.0%-0.0%] ─┐
  │  Raise max_token_candidates to broaden toke...  max_token_candidates: 15│
  │  0/0 hits  vs baseline: +0.0%                                  │
  │  best so far: C1 0.0%                                          │
  └────────────────────────────────────────────────────────────────┘

  ┌─ C3/5 ────────────────────────────────────── 0.0% [0.0%-0.0%] ─┐
  │  Increase raw_content_limit to retrieve lon...  raw_content_limit: 10│
  │  0/0 hits  vs baseline: +0.0%                                  │
  │  best so far: C1 0.0%                                          │
  └────────────────────────────────────────────────────────────────┘

  ┌─ C4/5 ────────────────────────────────────── 0.0% [0.0%-0.0%] ─┐
  │  Set profiling_temperature to 0.7 to encour...  profiling_temperature: 0.7│
  │  0/0 hits  vs baseline: +0.0%                                  │
  │  best so far: C1 0.0%                                          │
  └────────────────────────────────────────────────────────────────┘

  ┌─ C5/5 ────────────────────────────────────── 0.0% [0.0%-0.0%] ─┐
  │  Add extra fields to profiling_schema to ca...  pp=[profiling_schema]│
  │  0/0 hits  vs baseline: +0.0%                                  │
  │  best so far: C1 0.0%                                          │
  └────────────────────────────────────────────────────────────────┘
  ┌─ SCOREBOARD ───────────────────────────────────────────────────────────────┐
  │  #   Label    Accuracy            95% CI    Delta                          │
  │  1   C1          0.0%        [0.0%-0.0%]       ---  *                      │
  │  2   C2          0.0%        [0.0%-0.0%]       ---                         │
  │  3   C3          0.0%        [0.0%-0.0%]       ---                         │
  │  4   C4          0.0%        [0.0%-0.0%]       ---                         │
  │  5   C5          0.0%        [0.0%-0.0%]       ---                         │
  └────────────────────────────────────────────────────────────────────────────┘
  ⚠ NO IMPROVEMENT  best candidate 0.0%

╔════════════════════════════════════════════════════════════════════╗
║  OPTIMIZATION COMPLETE                                             ║
╠════════════════════════════════════════════════════════════════════╣
║  Rounds       3              Best         0.0% (round search)      ║
║  Stop reason  l3_patience_exhausted                                ║
║  Cycle ID     cycle_e9315d106538                                   ║
║  Langfuse     1760200b945024440bc7ec949abac860                     ║
╚════════════════════════════════════════════════════════════════════╝

In [ ]:
#@title 5. Results — summary, save, sync
show_campaign_summary(campaign_rounds)
show_flip_tracking(campaign_rounds)
show_lineage_chain(campaign_rounds)

# --- Persist (T2: below the fold) ---
save_campaign_winner(
    campaign_rounds, campaign_config, svc["store"], svc["backend_id"],
    experiment_id=EXPERIMENT_ID,
)
sync_langfuse(
    svc["store"], svc["backend_id"],
    dataset_name="termnorm_ground_truth",
)

CAMPAIGN SUMMARY (1 rounds)
======================================================================

,round,label,hit@1,total,accuracy,prompt_id
0,search,smart_search (scan_winner (sp_hash=5217c,0,0,0.0%,72ce39aed3c9

2026-04-01 14:26:13 INFO     [api.services.campaign.campaign_persistence] Winner saved: optimization/campaign_winner_72ce39aed3c9.json (acc=0.0%)

Need at least 2 rounds for flip tracking.
LINEAGE CHAIN
==================================================
  [72ce39aed3c9] Round search: smart_search (scan_winner (sp_hash=5217c (0.0%)

2026-04-01 14:26:21 WARNING  [api.services.obs.langfuse_client] Failed to get Langfuse dataset
Traceback (most recent call last):
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 246, in list
    _response_json = _response.json()
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Python313\Lib\json\decoder.py", line 348, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsacc\Desktop\PromptPotter\prompt-potter-optimizer\api\services\obs\langfuse_client.py", line 391, in get_dataset
    return self.client.get_dataset(name=name)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\_client\client.py", line 2444, in get_dataset
    new_items = self.api.dataset_items.list(
        dataset_name=self._url_encode(name, is_url_param=True),
        page=page,
        limit=fetch_items_page_size,
    )
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 248, in list
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 429, body: 429 - rate limit exceeded
2026-04-01 14:26:24 WARNING  [api.services.obs.langfuse_client] Failed to create Langfuse dataset item
Traceback (most recent call last):
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 96, in create
    _response_json = _response.json()
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Python313\Lib\json\decoder.py", line 348, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsacc\Desktop\PromptPotter\prompt-potter-optimizer\api\services\obs\langfuse_client.py", line 369, in create_dataset_item
    item = self.client.create_dataset_item(
        dataset_name=dataset_name,
    ...<2 lines>...
        metadata=metadata or {},
    )
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\_client\client.py", line 3345, in create_dataset_item
    return self.api.dataset_items.create(request=body)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 98, in create
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 429, body: 429 - rate limit exceeded
2026-04-01 14:26:27 WARNING  [api.services.obs.langfuse_client] Failed to create Langfuse dataset item
Traceback (most recent call last):
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 96, in create
    _response_json = _response.json()
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Python313\Lib\json\decoder.py", line 348, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsacc\Desktop\PromptPotter\prompt-potter-optimizer\api\services\obs\langfuse_client.py", line 369, in create_dataset_item
    item = self.client.create_dataset_item(
        dataset_name=dataset_name,
    ...<2 lines>...
        metadata=metadata or {},
    )
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\_client\client.py", line 3345, in create_dataset_item
    return self.api.dataset_items.create(request=body)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 98, in create
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 429, body: 429 - rate limit exceeded
2026-04-01 14:26:30 WARNING  [api.services.obs.langfuse_client] Failed to create Langfuse dataset item
Traceback (most recent call last):
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 96, in create
    _response_json = _response.json()
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Python313\Lib\json\decoder.py", line 348, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsacc\Desktop\PromptPotter\prompt-potter-optimizer\api\services\obs\langfuse_client.py", line 369, in create_dataset_item
    item = self.client.create_dataset_item(
        dataset_name=dataset_name,
    ...<2 lines>...
        metadata=metadata or {},
    )
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\_client\client.py", line 3345, in create_dataset_item
    return self.api.dataset_items.create(request=body)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 98, in create
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 429, body: 429 - rate limit exceeded
2026-04-01 14:26:33 WARNING  [api.services.obs.langfuse_client] Failed to create Langfuse dataset item
Traceback (most recent call last):
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 96, in create
    _response_json = _response.json()
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Python313\Lib\json\decoder.py", line 348, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsacc\Desktop\PromptPotter\prompt-potter-optimizer\api\services\obs\langfuse_client.py", line 369, in create_dataset_item
    item = self.client.create_dataset_item(
        dataset_name=dataset_name,
    ...<2 lines>...
        metadata=metadata or {},
    )
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\_client\client.py", line 3345, in create_dataset_item
    return self.api.dataset_items.create(request=body)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 98, in create
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 429, body: 429 - rate limit exceeded
2026-04-01 14:26:37 WARNING  [api.services.obs.langfuse_client] Failed to create Langfuse dataset item
Traceback (most recent call last):
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 96, in create
    _response_json = _response.json()
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Python313\Lib\json\decoder.py", line 348, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsacc\Desktop\PromptPotter\prompt-potter-optimizer\api\services\obs\langfuse_client.py", line 369, in create_dataset_item
    item = self.client.create_dataset_item(
        dataset_name=dataset_name,
    ...<2 lines>...
        metadata=metadata or {},
    )
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\_client\client.py", line 3345, in create_dataset_item
    return self.api.dataset_items.create(request=body)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 98, in create
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 429, body: 429 - rate limit exceeded
2026-04-01 14:26:40 WARNING  [api.services.obs.langfuse_client] Failed to create Langfuse dataset item
Traceback (most recent call last):
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 96, in create
    _response_json = _response.json()
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Python313\Lib\json\decoder.py", line 348, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsacc\Desktop\PromptPotter\prompt-potter-optimizer\api\services\obs\langfuse_client.py", line 369, in create_dataset_item
    item = self.client.create_dataset_item(
        dataset_name=dataset_name,
    ...<2 lines>...
        metadata=metadata or {},
    )
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\_client\client.py", line 3345, in create_dataset_item
    return self.api.dataset_items.create(request=body)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 98, in create
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 429, body: 429 - rate limit exceeded
2026-04-01 14:26:43 WARNING  [api.services.obs.langfuse_client] Failed to create Langfuse dataset item
Traceback (most recent call last):
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 96, in create
    _response_json = _response.json()
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Python313\Lib\json\decoder.py", line 348, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsacc\Desktop\PromptPotter\prompt-potter-optimizer\api\services\obs\langfuse_client.py", line 369, in create_dataset_item
    item = self.client.create_dataset_item(
        dataset_name=dataset_name,
    ...<2 lines>...
        metadata=metadata or {},
    )
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\_client\client.py", line 3345, in create_dataset_item
    return self.api.dataset_items.create(request=body)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 98, in create
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 429, body: 429 - rate limit exceeded
2026-04-01 14:26:46 WARNING  [api.services.obs.langfuse_client] Failed to create Langfuse dataset item
Traceback (most recent call last):
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 96, in create
    _response_json = _response.json()
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Python313\Lib\json\decoder.py", line 348, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsacc\Desktop\PromptPotter\prompt-potter-optimizer\api\services\obs\langfuse_client.py", line 369, in create_dataset_item
    item = self.client.create_dataset_item(
        dataset_name=dataset_name,
    ...<2 lines>...
        metadata=metadata or {},
    )
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\_client\client.py", line 3345, in create_dataset_item
    return self.api.dataset_items.create(request=body)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 98, in create
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 429, body: 429 - rate limit exceeded
2026-04-01 14:26:49 WARNING  [api.services.obs.langfuse_client] Failed to create Langfuse dataset item
Traceback (most recent call last):
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 96, in create
    _response_json = _response.json()
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Python313\Lib\json\decoder.py", line 348, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dsacc\Desktop\PromptPotter\prompt-potter-optimizer\api\services\obs\langfuse_client.py", line 369, in create_dataset_item
    item = self.client.create_dataset_item(
        dataset_name=dataset_name,
    ...<2 lines>...
        metadata=metadata or {},
    )
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\_client\client.py", line 3345, in create_dataset_item
    return self.api.dataset_items.create(request=body)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\dsacc\AppData\Roaming\Python\Python313\site-packages\langfuse\api\resources\dataset_items\client.py", line 98, in create
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 429, body: 429 - rate limit exceeded